In [1]:
# ============================================================
# DEMAND V3 — FOMO + TTFL + TRAFFIC + CONTACT RATE
# FULL PIPELINE FROM SCRATCH
#
# Goal:
# - Check "demand" more carefully for supply-demand analysis
# - Combine:
#   1. Supply: listing_count
#   2. FOMO: early contact rate in first N days
#   3. TTFL: time to first lead
#   4. Traffic: pageviews
#   5. CR: strict_contact / pageviews
#
# Important:
# - Filter by listing_count threshold to avoid tiny groups creating fake insights
# - Uses strict_contact only:
#   view_phone + contact_chat + contact_zalo + contact_sms
# - Keeps other_interaction only as optional all_positive metric
# ============================================================

# ============================================================
# 0. IMPORTS
# ============================================================

import os
import gc
import shutil
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import pyarrow.dataset as ds

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio

pio.renderers.default = "iframe"

# ============================================================
# 1. CONFIG — EDIT HERE IF NEEDED
# ============================================================

DIM_LISTING_PATH = "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/dim_listing"
SNAPSHOT_PATH    = "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/fact_listing_snapshot"
EVENTS_PATH      = "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2/fact_user_events"

CACHE_DIR = "/kaggle/working/demand_v3_fomo_ttfl_traffic"

FORCE_REBUILD = True

# Batch size: giảm nếu bị OOM
DIM_BATCH_SIZE      = 500_000
SNAPSHOT_BATCH_SIZE = 500_000
EVENTS_BATCH_SIZE   = 300_000

# FOMO window
FOMO_MAX_AGE_DAYS = 7

# Grouping option:
# True  = city/category/ad_type, district/category/ad_type
# False = city/category, district/category
GROUP_WITH_AD_TYPE = True

# Listing threshold để tránh group quá nhỏ
MIN_LISTINGS_CITY_GROUP = 1000
MIN_LISTINGS_HCM_GROUP  = 500

# Evidence thresholds.
# Có thể set về 0 nếu chỉ muốn dùng listing_count threshold.
MIN_PAGEVIEWS_CITY_GROUP        = 1000
MIN_EARLY_VIEWS_CITY_GROUP     = 500
MIN_ITEMS_WITH_LEAD_CITY_GROUP = 30

MIN_PAGEVIEWS_HCM_GROUP        = 500
MIN_EARLY_VIEWS_HCM_GROUP     = 300
MIN_ITEMS_WITH_LEAD_HCM_GROUP = 20

STRICT_CONTACTS = {
    "view_phone",
    "contact_chat",
    "contact_zalo",
    "contact_sms",
}

ALL_POSITIVE = STRICT_CONTACTS.union({"other_interaction"})

CATEGORY_MAP = {
    1010: "1010 - Phòng trọ / căn hộ thuê",
    1020: "1020 - Căn hộ / chung cư",
    1030: "1030 - Nhà ở",
    1040: "1040 - Đất / BĐS thương mại",
    1050: "1050 - Dự án / căn hộ mới",
}

# ============================================================
# 2. RESET CACHE
# ============================================================

if FORCE_REBUILD and os.path.exists(CACHE_DIR):
    shutil.rmtree(CACHE_DIR)

os.makedirs(CACHE_DIR, exist_ok=True)

# ============================================================
# 3. HELPERS
# ============================================================

def clean_text(x, unknown="Unknown"):
    if pd.isna(x):
        return unknown
    x = str(x).strip()
    if x == "":
        return unknown
    return x


def clean_city(x):
    if pd.isna(x):
        return "Unknown"
    x = str(x).strip()
    if x == "":
        return "Unknown"

    xl = x.lower()

    if (
        "hồ chí minh" in xl
        or "ho chi minh" in xl
        or "tp.hcm" in xl
        or "tp hcm" in xl
        or xl == "hcm"
        or xl == "tphcm"
    ):
        return "Tp Hồ Chí Minh"

    return x


def clean_district(x):
    return clean_text(x, "Unknown District")


def clean_category(x):
    if pd.isna(x):
        return "Unknown Category"
    try:
        x = int(float(x))
        return CATEGORY_MAP.get(x, str(x))
    except Exception:
        return "Unknown Category"


def safe_div(num, den):
    return num / den.replace(0, np.nan)


def acc_add(acc, key, row, metric_cols):
    if key not in acc:
        acc[key] = {c: 0.0 for c in metric_cols}

    for c in metric_cols:
        acc[key][c] += float(row[c])


def acc_to_df(acc, key_cols):
    rows = []
    for key, values in acc.items():
        row = dict(zip(key_cols, key))
        row.update(values)
        rows.append(row)
    return pd.DataFrame(rows)


def add_group_label(df, geo_col):
    df = df.copy()

    parts = [df[geo_col].astype(str), df["category_name"].astype(str)]

    if GROUP_WITH_AD_TYPE and "ad_type" in df.columns:
        parts.append(df["ad_type"].astype(str))

    label = parts[0]
    for p in parts[1:]:
        label = label + " | " + p

    df["group_label"] = label
    return df


def pct_rank(series, higher_is_better=True):
    s = series.replace([np.inf, -np.inf], np.nan)
    if s.notna().sum() <= 1:
        return pd.Series(np.nan, index=s.index)

    if higher_is_better:
        return s.rank(pct=True, ascending=True)
    else:
        # lower value should get higher score
        return s.rank(pct=True, ascending=False)


def build_score_and_segment(
    df,
    geo_col,
    min_listings,
    min_pageviews,
    min_early_views,
    min_items_with_lead,
):
    df = df.copy()

    # -----------------------------
    # Basic ratios
    # -----------------------------
    df["pageviews_per_listing"] = safe_div(
        df["pageviews"],
        df["listing_count"]
    )

    df["strict_contact_per_listing"] = safe_div(
        df["strict_contact"],
        df["listing_count"]
    )

    df["all_positive_per_listing"] = safe_div(
        df["all_positive"],
        df["listing_count"]
    )

    df["strict_contact_rate"] = safe_div(
        df["strict_contact"],
        df["pageviews"]
    )

    df["all_positive_rate"] = safe_div(
        df["all_positive"],
        df["pageviews"]
    )

    df["fomo_early_contact_rate"] = safe_div(
        df["early_contacts_24h"],
        df["early_views_24h"]
    )

    df["lead_listing_rate"] = safe_div(
        df["items_with_lead"],
        df["listing_count"]
    )

    # -----------------------------
    # Reliability filters
    # -----------------------------
    df["passes_listing_threshold"] = (
        df["listing_count"].fillna(0) >= min_listings
    )

    df["passes_evidence_threshold"] = (
        (df["pageviews"].fillna(0) >= min_pageviews)
        & (df["early_views_24h"].fillna(0) >= min_early_views)
        & (df["items_with_lead"].fillna(0) >= min_items_with_lead)
    )

    df["analysis_eligible"] = (
        df["passes_listing_threshold"]
        & df["passes_evidence_threshold"]
        & df["fomo_early_contact_rate"].notna()
        & df["strict_contact_rate"].notna()
        & df["strict_contact_per_listing"].notna()
        & df["median_ttfl_days"].notna()
    )

    # -----------------------------
    # Rank-based demand score
    # -----------------------------
    score_cols = [
        "score_fomo",
        "score_strict_cr",
        "score_contact_per_listing",
        "score_ttfl_fast",
        "score_pageviews_per_listing",
    ]

    for c in score_cols:
        df[c] = np.nan

    idx = df["analysis_eligible"]

    df.loc[idx, "score_fomo"] = pct_rank(
        df.loc[idx, "fomo_early_contact_rate"],
        higher_is_better=True
    )

    df.loc[idx, "score_strict_cr"] = pct_rank(
        df.loc[idx, "strict_contact_rate"],
        higher_is_better=True
    )

    df.loc[idx, "score_contact_per_listing"] = pct_rank(
        df.loc[idx, "strict_contact_per_listing"],
        higher_is_better=True
    )

    df.loc[idx, "score_ttfl_fast"] = pct_rank(
        df.loc[idx, "median_ttfl_days"],
        higher_is_better=False
    )

    df.loc[idx, "score_pageviews_per_listing"] = pct_rank(
        df.loc[idx, "pageviews_per_listing"],
        higher_is_better=True
    )

    weights = {
        "score_fomo": 0.25,
        "score_strict_cr": 0.25,
        "score_contact_per_listing": 0.25,
        "score_ttfl_fast": 0.20,
        "score_pageviews_per_listing": 0.05,
    }

    weighted_sum = 0
    weight_used = 0

    for c, w in weights.items():
        valid_c = df[c].notna()
        weighted_sum = weighted_sum + df[c].fillna(0) * w
        weight_used = weight_used + valid_c.astype(float) * w

    df["demand_score"] = weighted_sum / weight_used.replace(0, np.nan)

    # -----------------------------
    # Segment labels
    # -----------------------------
    valid = df[df["analysis_eligible"]].copy()

    if len(valid) == 0:
        df["demand_segment"] = np.where(
            df["passes_listing_threshold"],
            "Enough listings but weak evidence",
            "Too small / unreliable"
        )
        return add_group_label(df, geo_col)

    q = {
        "fomo_hi": valid["fomo_early_contact_rate"].quantile(0.60),
        "fomo_lo": valid["fomo_early_contact_rate"].quantile(0.40),
        "cr_hi": valid["strict_contact_rate"].quantile(0.60),
        "cr_lo": valid["strict_contact_rate"].quantile(0.40),
        "cpl_hi": valid["strict_contact_per_listing"].quantile(0.60),
        "cpl_lo": valid["strict_contact_per_listing"].quantile(0.40),
        "ttfl_fast": valid["median_ttfl_days"].quantile(0.40),
        "ttfl_slow": valid["median_ttfl_days"].quantile(0.60),
        "traffic_hi": valid["pageviews_per_listing"].quantile(0.60),
        "traffic_lo": valid["pageviews_per_listing"].quantile(0.40),
        "supply_hi": valid["listing_count"].quantile(0.60),
    }

    def label(row):
        if not row["passes_listing_threshold"]:
            return "Too small / unreliable"

        if not row["passes_evidence_threshold"]:
            return "Enough listings but weak evidence"

        if not row["analysis_eligible"]:
            return "Missing key metric"

        high_fomo = row["fomo_early_contact_rate"] >= q["fomo_hi"]
        high_cr = row["strict_contact_rate"] >= q["cr_hi"]
        high_cpl = row["strict_contact_per_listing"] >= q["cpl_hi"]
        fast_ttfl = row["median_ttfl_days"] <= q["ttfl_fast"]

        low_cr = row["strict_contact_rate"] <= q["cr_lo"]
        low_cpl = row["strict_contact_per_listing"] <= q["cpl_lo"]
        slow_ttfl = row["median_ttfl_days"] >= q["ttfl_slow"]

        high_traffic = row["pageviews_per_listing"] >= q["traffic_hi"]
        low_traffic = row["pageviews_per_listing"] <= q["traffic_lo"]
        high_supply = row["listing_count"] >= q["supply_hi"]

        if high_fomo and high_cr and high_cpl and fast_ttfl:
            return "Confirmed hot demand"

        if high_traffic and low_cr:
            return "High attention, low conversion"

        if high_fomo and fast_ttfl and low_traffic:
            return "FOMO fast but traffic thin"

        if high_supply and low_cpl and slow_ttfl:
            return "Potential oversupply / slow liquidity"

        if high_cpl and fast_ttfl:
            return "Fast liquidity"

        if low_cpl and slow_ttfl:
            return "Weak demand / slow liquidity"

        return "Normal / mixed"

    df["demand_segment"] = df.apply(label, axis=1)

    return add_group_label(df, geo_col)


def save_plot(fig, name):
    path = os.path.join(CACHE_DIR, name)
    fig.write_html(path)
    fig.show(renderer="iframe")
    print("[SAVED]", path)


# ============================================================
# 4. FIND INPUT FILES
# ============================================================

print("Available Kaggle input folders:")
for dirname, _, filenames in os.walk("/kaggle/input"):
    if filenames:
        print(dirname, "| sample:", filenames[:2])

# ============================================================
# 5. BUILD item_map FROM dim_listing
# ============================================================

print("\n[1/7] Building item_map from dim_listing...")

dim_ds = ds.dataset(DIM_LISTING_PATH, format="parquet")

dim_cols = [
    "item_id",
    "city_name",
    "district_name",
    "category",
    "ad_type",
    "posted_date",
]

item_parts = []

for i, batch in enumerate(
    dim_ds.to_batches(columns=dim_cols, batch_size=DIM_BATCH_SIZE),
    start=1
):
    df = batch.to_pandas()

    df["city_name"] = df["city_name"].map(clean_city)
    df["district_name"] = df["district_name"].map(clean_district)
    df["category_name"] = df["category"].map(clean_category)
    df["ad_type"] = df["ad_type"].map(lambda x: clean_text(x, "Unknown Ad Type"))
    df["posted_date"] = pd.to_datetime(df["posted_date"], errors="coerce")

    df = df[
        [
            "item_id",
            "city_name",
            "district_name",
            "category",
            "category_name",
            "ad_type",
            "posted_date",
        ]
    ].drop_duplicates("item_id")

    item_parts.append(df)

    if i % 10 == 0:
        print("dim_listing batches:", i)

    del df
    gc.collect()

item_map = pd.concat(item_parts, ignore_index=True).drop_duplicates("item_id")

item_map_path = os.path.join(CACHE_DIR, "item_map.parquet")
item_map.to_parquet(item_map_path, index=False)

print("item_map shape:", item_map.shape)
display(item_map.head())

# ============================================================
# 6. GROUP KEYS
# ============================================================

city_keys = ["city_name", "category_name"]
hcm_keys = ["district_name", "category_name"]

if GROUP_WITH_AD_TYPE:
    city_keys.append("ad_type")
    hcm_keys.append("ad_type")

print("City group keys:", city_keys)
print("HCM group keys:", hcm_keys)

# ============================================================
# 7. BUILD SUPPLY TABLES FROM dim_listing
# ============================================================

print("\n[2/7] Building supply tables...")

city_supply = (
    item_map
    .groupby(city_keys, dropna=False)
    .agg(listing_count=("item_id", "nunique"))
    .reset_index()
)

hcm_supply = (
    item_map[
        (item_map["city_name"] == "Tp Hồ Chí Minh")
        & (~item_map["district_name"].isin(["Unknown District", "Unmapped Item"]))
    ]
    .groupby(hcm_keys, dropna=False)
    .agg(listing_count=("item_id", "nunique"))
    .reset_index()
)

city_supply.to_parquet(os.path.join(CACHE_DIR, "city_supply.parquet"), index=False)
hcm_supply.to_parquet(os.path.join(CACHE_DIR, "hcm_supply.parquet"), index=False)

print("city_supply:", city_supply.shape)
print("hcm_supply:", hcm_supply.shape)

display(city_supply.sort_values("listing_count", ascending=False).head(20))
display(hcm_supply.sort_values("listing_count", ascending=False).head(20))

# ============================================================
# 8. SCAN fact_listing_snapshot ONCE
#    Build FOMO + item-level TTFL
# ============================================================

print("\n[3/7] Scanning fact_listing_snapshot for FOMO + TTFL...")

snap_ds = ds.dataset(SNAPSHOT_PATH, format="parquet")

item_map_for_snapshot = item_map[
    [
        "item_id",
        "city_name",
        "district_name",
        "category_name",
        "ad_type",
        "posted_date",
    ]
].copy()

city_fomo_acc = {}
hcm_fomo_acc = {}

fomo_metric_cols = [
    "early_views_24h",
    "early_contacts_24h",
    "early_snapshot_rows",
    "early_unique_items_sum_batch",
    "missing_views_rows",
    "missing_contacts_rows",
]

first_lead = {}

dq = {
    "total_snapshot_rows": 0,
    "unmapped_item_rows": 0,
    "negative_age_rows": 0,
    "missing_views_rows": 0,
    "missing_contacts_rows": 0,
    "valid_fomo_rows": 0,
    "valid_first_lead_rows": 0,
}

snapshot_cols = [
    "item_id",
    "date",
    "views_24h",
    "contacts_24h",
    "listing_age_days",
]

for i, batch in enumerate(
    snap_ds.to_batches(columns=snapshot_cols, batch_size=SNAPSHOT_BATCH_SIZE),
    start=1
):
    df = batch.to_pandas()

    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["views_24h"] = pd.to_numeric(df["views_24h"], errors="coerce")
    df["contacts_24h"] = pd.to_numeric(df["contacts_24h"], errors="coerce")
    df["listing_age_days"] = pd.to_numeric(df["listing_age_days"], errors="coerce")

    dq["total_snapshot_rows"] += len(df)
    dq["negative_age_rows"] += int((df["listing_age_days"] < 0).sum())
    dq["missing_views_rows"] += int(df["views_24h"].isna().sum())
    dq["missing_contacts_rows"] += int(df["contacts_24h"].isna().sum())

    df = df.merge(
        item_map_for_snapshot,
        on="item_id",
        how="left",
        indicator=True
    )

    df["is_mapped_item"] = df["_merge"].eq("both")
    dq["unmapped_item_rows"] += int((~df["is_mapped_item"]).sum())

    # -----------------------------
    # 8A. FOMO rows
    # Keep NaN views/contact as 0.
    # Only remove negative / invalid age.
    # -----------------------------
    valid_fomo = df[
        (df["is_mapped_item"])
        & (df["listing_age_days"].notna())
        & (df["listing_age_days"] >= 0)
        & (df["listing_age_days"] <= FOMO_MAX_AGE_DAYS)
    ].copy()

    dq["valid_fomo_rows"] += len(valid_fomo)

    if len(valid_fomo) > 0:
        valid_fomo["views_24h_clean"] = valid_fomo["views_24h"].fillna(0)
        valid_fomo["contacts_24h_clean"] = valid_fomo["contacts_24h"].fillna(0)

        # City-level FOMO
        grp = (
            valid_fomo
            .groupby(city_keys, dropna=False)
            .agg(
                early_views_24h=("views_24h_clean", "sum"),
                early_contacts_24h=("contacts_24h_clean", "sum"),
                early_snapshot_rows=("item_id", "size"),
                early_unique_items_sum_batch=("item_id", "nunique"),
                missing_views_rows=("views_24h", lambda x: x.isna().sum()),
                missing_contacts_rows=("contacts_24h", lambda x: x.isna().sum()),
            )
            .reset_index()
        )

        for _, row in grp.iterrows():
            key = tuple(row[k] for k in city_keys)
            acc_add(city_fomo_acc, key, row, fomo_metric_cols)

        # HCM district-level FOMO
        hcm_valid = valid_fomo[
            (valid_fomo["city_name"] == "Tp Hồ Chí Minh")
            & (~valid_fomo["district_name"].isin(["Unknown District", "Unmapped Item"]))
        ].copy()

        if len(hcm_valid) > 0:
            grp = (
                hcm_valid
                .groupby(hcm_keys, dropna=False)
                .agg(
                    early_views_24h=("views_24h_clean", "sum"),
                    early_contacts_24h=("contacts_24h_clean", "sum"),
                    early_snapshot_rows=("item_id", "size"),
                    early_unique_items_sum_batch=("item_id", "nunique"),
                    missing_views_rows=("views_24h", lambda x: x.isna().sum()),
                    missing_contacts_rows=("contacts_24h", lambda x: x.isna().sum()),
                )
                .reset_index()
            )

            for _, row in grp.iterrows():
                key = tuple(row[k] for k in hcm_keys)
                acc_add(hcm_fomo_acc, key, row, fomo_metric_cols)

    # -----------------------------
    # 8B. TTFL item-level
    # First lead = minimum listing_age_days where contacts_24h > 0
    # -----------------------------
    lead_rows = df[
        (df["is_mapped_item"])
        & (df["listing_age_days"].notna())
        & (df["listing_age_days"] >= 0)
        & (df["contacts_24h"].notna())
        & (df["contacts_24h"] > 0)
    ][["item_id", "listing_age_days"]].copy()

    dq["valid_first_lead_rows"] += len(lead_rows)

    if len(lead_rows) > 0:
        first_in_batch = lead_rows.groupby("item_id")["listing_age_days"].min()

        for item_id, age in first_in_batch.items():
            old = first_lead.get(item_id)
            if old is None or age < old:
                first_lead[item_id] = float(age)

    if i % 20 == 0:
        print("snapshot batches:", i)

    del df, valid_fomo
    gc.collect()

city_fomo = acc_to_df(city_fomo_acc, city_keys)
hcm_fomo = acc_to_df(hcm_fomo_acc, hcm_keys)

item_first_lead = pd.DataFrame({
    "item_id": list(first_lead.keys()),
    "time_to_first_lead_days": list(first_lead.values()),
})

city_fomo.to_parquet(os.path.join(CACHE_DIR, "city_fomo.parquet"), index=False)
hcm_fomo.to_parquet(os.path.join(CACHE_DIR, "hcm_fomo.parquet"), index=False)
item_first_lead.to_parquet(os.path.join(CACHE_DIR, "item_first_lead.parquet"), index=False)

dq_df = pd.DataFrame([dq])
dq_df["valid_fomo_rate"] = dq_df["valid_fomo_rows"] / dq_df["total_snapshot_rows"]
dq_df["valid_first_lead_rate"] = dq_df["valid_first_lead_rows"] / dq_df["total_snapshot_rows"]
dq_df.to_csv(os.path.join(CACHE_DIR, "snapshot_dq_summary.csv"), index=False)

print("city_fomo:", city_fomo.shape)
print("hcm_fomo:", hcm_fomo.shape)
print("item_first_lead:", item_first_lead.shape)
display(dq_df)

# ============================================================
# 9. BUILD TTFL GROUP TABLES
# ============================================================

print("\n[4/7] Building TTFL group tables...")

ttfl = item_first_lead.merge(
    item_map[
        [
            "item_id",
            "city_name",
            "district_name",
            "category_name",
            "ad_type",
        ]
    ],
    on="item_id",
    how="left"
)

ttfl["time_to_first_lead_days"] = pd.to_numeric(
    ttfl["time_to_first_lead_days"],
    errors="coerce"
)

ttfl = ttfl[
    (ttfl["time_to_first_lead_days"].notna())
    & (ttfl["time_to_first_lead_days"] >= 0)
].copy()

city_ttfl = (
    ttfl
    .groupby(city_keys, dropna=False)
    .agg(
        items_with_lead=("item_id", "nunique"),
        median_ttfl_days=("time_to_first_lead_days", "median"),
        mean_ttfl_days=("time_to_first_lead_days", "mean"),
        p25_ttfl_days=("time_to_first_lead_days", lambda x: x.quantile(0.25)),
        p75_ttfl_days=("time_to_first_lead_days", lambda x: x.quantile(0.75)),
    )
    .reset_index()
)

hcm_ttfl = (
    ttfl[
        (ttfl["city_name"] == "Tp Hồ Chí Minh")
        & (~ttfl["district_name"].isin(["Unknown District", "Unmapped Item"]))
    ]
    .groupby(hcm_keys, dropna=False)
    .agg(
        items_with_lead=("item_id", "nunique"),
        median_ttfl_days=("time_to_first_lead_days", "median"),
        mean_ttfl_days=("time_to_first_lead_days", "mean"),
        p25_ttfl_days=("time_to_first_lead_days", lambda x: x.quantile(0.25)),
        p75_ttfl_days=("time_to_first_lead_days", lambda x: x.quantile(0.75)),
    )
    .reset_index()
)

city_ttfl.to_parquet(os.path.join(CACHE_DIR, "city_ttfl.parquet"), index=False)
hcm_ttfl.to_parquet(os.path.join(CACHE_DIR, "hcm_ttfl.parquet"), index=False)

print("city_ttfl:", city_ttfl.shape)
print("hcm_ttfl:", hcm_ttfl.shape)

display(city_ttfl.sort_values("items_with_lead", ascending=False).head(20))
display(hcm_ttfl.sort_values("items_with_lead", ascending=False).head(20))

# ============================================================
# 10. SCAN fact_user_events FOR TRAFFIC + CONTACT RATE
# ============================================================

print("\n[5/7] Scanning fact_user_events for traffic + strict contact rate...")

events_ds = ds.dataset(EVENTS_PATH, format="parquet")

item_map_for_events = item_map[
    [
        "item_id",
        "city_name",
        "district_name",
        "category_name",
        "ad_type",
    ]
].copy()

traffic_metric_cols = [
    "pageviews",
    "strict_contact",
    "all_positive",
    "total_events",
]

city_traffic_acc = {}
hcm_traffic_acc = {}

event_cols = [
    "item_id",
    "city_name",
    "category",
    "event_type",
]

for i, batch in enumerate(
    events_ds.to_batches(columns=event_cols, batch_size=EVENTS_BATCH_SIZE),
    start=1
):
    df = batch.to_pandas()

    df = df.rename(columns={
        "city_name": "event_city_name",
        "category": "event_category",
    })

    df["event_city_name"] = df["event_city_name"].map(clean_city)
    df["event_category_name"] = df["event_category"].map(clean_category)
    df["event_type"] = df["event_type"].fillna("unknown").astype(str)

    df = df.merge(
        item_map_for_events,
        on="item_id",
        how="left"
    )

    # Prefer dim_listing metadata.
    # If item is unmapped, fallback to event city/category where available.
    df["city_name"] = df["city_name"].fillna(df["event_city_name"])
    df["category_name"] = df["category_name"].fillna(df["event_category_name"])
    df["district_name"] = df["district_name"].fillna("Unknown District")
    df["ad_type"] = df["ad_type"].fillna("Unknown Ad Type")

    df["pageviews"] = (df["event_type"] == "pageview").astype(np.int64)
    df["strict_contact"] = df["event_type"].isin(STRICT_CONTACTS).astype(np.int64)
    df["all_positive"] = df["event_type"].isin(ALL_POSITIVE).astype(np.int64)
    df["total_events"] = 1

    # City traffic
    grp = (
        df
        .groupby(city_keys, dropna=False)[traffic_metric_cols]
        .sum()
        .reset_index()
    )

    for _, row in grp.iterrows():
        key = tuple(row[k] for k in city_keys)
        acc_add(city_traffic_acc, key, row, traffic_metric_cols)

    # HCM district traffic
    hcm_df = df[
        (df["city_name"] == "Tp Hồ Chí Minh")
        & (~df["district_name"].isin(["Unknown District", "Unmapped Item"]))
    ].copy()

    if len(hcm_df) > 0:
        grp = (
            hcm_df
            .groupby(hcm_keys, dropna=False)[traffic_metric_cols]
            .sum()
            .reset_index()
        )

        for _, row in grp.iterrows():
            key = tuple(row[k] for k in hcm_keys)
            acc_add(hcm_traffic_acc, key, row, traffic_metric_cols)

    if i % 20 == 0:
        print("event batches:", i)

    del df
    gc.collect()

city_traffic = acc_to_df(city_traffic_acc, city_keys)
hcm_traffic = acc_to_df(hcm_traffic_acc, hcm_keys)

city_traffic.to_parquet(os.path.join(CACHE_DIR, "city_traffic.parquet"), index=False)
hcm_traffic.to_parquet(os.path.join(CACHE_DIR, "hcm_traffic.parquet"), index=False)

print("city_traffic:", city_traffic.shape)
print("hcm_traffic:", hcm_traffic.shape)

display(city_traffic.sort_values("pageviews", ascending=False).head(20))
display(hcm_traffic.sort_values("pageviews", ascending=False).head(20))

# ============================================================
# 11. MERGE DEMAND V3 TABLES
# ============================================================

print("\n[6/7] Merging supply + FOMO + TTFL + traffic...")

count_cols = [
    "listing_count",
    "early_views_24h",
    "early_contacts_24h",
    "early_snapshot_rows",
    "early_unique_items_sum_batch",
    "missing_views_rows",
    "missing_contacts_rows",
    "items_with_lead",
    "pageviews",
    "strict_contact",
    "all_positive",
    "total_events",
]

city_demand = (
    city_supply
    .merge(city_fomo, on=city_keys, how="outer")
    .merge(city_ttfl, on=city_keys, how="outer")
    .merge(city_traffic, on=city_keys, how="outer")
)

hcm_demand = (
    hcm_supply
    .merge(hcm_fomo, on=hcm_keys, how="outer")
    .merge(hcm_ttfl, on=hcm_keys, how="outer")
    .merge(hcm_traffic, on=hcm_keys, how="outer")
)

for df in [city_demand, hcm_demand]:
    for c in count_cols:
        if c in df.columns:
            df[c] = df[c].fillna(0)

city_demand = build_score_and_segment(
    city_demand,
    geo_col="city_name",
    min_listings=MIN_LISTINGS_CITY_GROUP,
    min_pageviews=MIN_PAGEVIEWS_CITY_GROUP,
    min_early_views=MIN_EARLY_VIEWS_CITY_GROUP,
    min_items_with_lead=MIN_ITEMS_WITH_LEAD_CITY_GROUP,
)

hcm_demand = build_score_and_segment(
    hcm_demand,
    geo_col="district_name",
    min_listings=MIN_LISTINGS_HCM_GROUP,
    min_pageviews=MIN_PAGEVIEWS_HCM_GROUP,
    min_early_views=MIN_EARLY_VIEWS_HCM_GROUP,
    min_items_with_lead=MIN_ITEMS_WITH_LEAD_HCM_GROUP,
)

city_result_path = os.path.join(CACHE_DIR, "city_demand_v3_fomo_ttfl_traffic.csv")
hcm_result_path = os.path.join(CACHE_DIR, "hcm_district_demand_v3_fomo_ttfl_traffic.csv")

city_demand.to_csv(city_result_path, index=False)
hcm_demand.to_csv(hcm_result_path, index=False)

print("[SAVED]", city_result_path)
print("[SAVED]", hcm_result_path)

# ============================================================
# 12. MAIN TABLES TO INSPECT
# ============================================================

print("\nTop confirmed / high-score city groups:")
top_city = (
    city_demand[
        city_demand["analysis_eligible"]
    ]
    .sort_values("demand_score", ascending=False)
    .head(30)
)

display(
    top_city[
        [
            "group_label",
            "listing_count",
            "pageviews",
            "strict_contact",
            "strict_contact_rate",
            "strict_contact_per_listing",
            "early_views_24h",
            "early_contacts_24h",
            "fomo_early_contact_rate",
            "items_with_lead",
            "lead_listing_rate",
            "median_ttfl_days",
            "demand_score",
            "demand_segment",
        ]
    ]
)

print("\nTop confirmed / high-score HCM district groups:")
top_hcm = (
    hcm_demand[
        hcm_demand["analysis_eligible"]
    ]
    .sort_values("demand_score", ascending=False)
    .head(30)
)

display(
    top_hcm[
        [
            "group_label",
            "listing_count",
            "pageviews",
            "strict_contact",
            "strict_contact_rate",
            "strict_contact_per_listing",
            "early_views_24h",
            "early_contacts_24h",
            "fomo_early_contact_rate",
            "items_with_lead",
            "lead_listing_rate",
            "median_ttfl_days",
            "demand_score",
            "demand_segment",
        ]
    ]
)

print("\nPotential high attention but low conversion — city:")
display(
    city_demand[
        city_demand["analysis_eligible"]
        & (city_demand["demand_segment"] == "High attention, low conversion")
    ]
    .sort_values("pageviews_per_listing", ascending=False)
    .head(20)
    [
        [
            "group_label",
            "listing_count",
            "pageviews_per_listing",
            "strict_contact_rate",
            "strict_contact_per_listing",
            "median_ttfl_days",
            "demand_segment",
        ]
    ]
)

print("\nPotential oversupply / slow liquidity — HCM:")
display(
    hcm_demand[
        hcm_demand["analysis_eligible"]
        & (hcm_demand["demand_segment"] == "Potential oversupply / slow liquidity")
    ]
    .sort_values(["listing_count", "strict_contact_per_listing"], ascending=[False, True])
    .head(20)
    [
        [
            "group_label",
            "listing_count",
            "pageviews",
            "strict_contact_rate",
            "strict_contact_per_listing",
            "median_ttfl_days",
            "demand_segment",
        ]
    ]
)

# Save key filtered tables
top_city.to_csv(os.path.join(CACHE_DIR, "top_city_confirmed_demand.csv"), index=False)
top_hcm.to_csv(os.path.join(CACHE_DIR, "top_hcm_confirmed_demand.csv"), index=False)

city_demand[
    ~city_demand["passes_listing_threshold"]
].to_csv(os.path.join(CACHE_DIR, "city_groups_too_small.csv"), index=False)

hcm_demand[
    ~hcm_demand["passes_listing_threshold"]
].to_csv(os.path.join(CACHE_DIR, "hcm_groups_too_small.csv"), index=False)

# ============================================================
# 13. PLOTS
# ============================================================

print("\n[7/7] Drawing charts...")

# -----------------------------
# 13A. City scatter: supply vs demand score
# -----------------------------
plot_city = city_demand[
    city_demand["passes_listing_threshold"]
].copy()

fig = px.scatter(
    plot_city,
    x="listing_count",
    y="demand_score",
    size="pageviews",
    color="demand_segment",
    hover_name="group_label",
    hover_data={
        "listing_count": ":,.0f",
        "pageviews": ":,.0f",
        "strict_contact": ":,.0f",
        "strict_contact_rate": ":.4f",
        "strict_contact_per_listing": ":.4f",
        "fomo_early_contact_rate": ":.4f",
        "median_ttfl_days": ":.2f",
        "items_with_lead": ":,.0f",
        "demand_score": ":.3f",
    },
    log_x=True,
    title="City Group Demand V3: Supply vs Combined Demand Score",
)

fig.update_layout(height=650)
save_plot(fig, "city_supply_vs_demand_score.html")

# -----------------------------
# 13B. HCM scatter: supply vs demand score
# -----------------------------
plot_hcm = hcm_demand[
    hcm_demand["passes_listing_threshold"]
].copy()

fig = px.scatter(
    plot_hcm,
    x="listing_count",
    y="demand_score",
    size="pageviews",
    color="demand_segment",
    hover_name="group_label",
    hover_data={
        "listing_count": ":,.0f",
        "pageviews": ":,.0f",
        "strict_contact": ":,.0f",
        "strict_contact_rate": ":.4f",
        "strict_contact_per_listing": ":.4f",
        "fomo_early_contact_rate": ":.4f",
        "median_ttfl_days": ":.2f",
        "items_with_lead": ":,.0f",
        "demand_score": ":.3f",
    },
    log_x=True,
    title="HCM District Group Demand V3: Supply vs Combined Demand Score",
)

fig.update_layout(height=650)
save_plot(fig, "hcm_supply_vs_demand_score.html")

# -----------------------------
# 13C. Top City groups by demand score
# -----------------------------
plot_top = (
    city_demand[
        city_demand["analysis_eligible"]
    ]
    .sort_values("demand_score", ascending=False)
    .head(25)
    .sort_values("demand_score", ascending=True)
)

fig = px.bar(
    plot_top,
    x="demand_score",
    y="group_label",
    orientation="h",
    color="demand_segment",
    hover_data={
        "listing_count": ":,.0f",
        "pageviews": ":,.0f",
        "strict_contact_rate": ":.4f",
        "fomo_early_contact_rate": ":.4f",
        "median_ttfl_days": ":.2f",
    },
    title="Top City Groups by Demand V3 Score",
)

fig.update_layout(height=750, yaxis_title="")
save_plot(fig, "top_city_demand_score.html")

# -----------------------------
# 13D. Top HCM groups by demand score
# -----------------------------
plot_top = (
    hcm_demand[
        hcm_demand["analysis_eligible"]
    ]
    .sort_values("demand_score", ascending=False)
    .head(25)
    .sort_values("demand_score", ascending=True)
)

fig = px.bar(
    plot_top,
    x="demand_score",
    y="group_label",
    orientation="h",
    color="demand_segment",
    hover_data={
        "listing_count": ":,.0f",
        "pageviews": ":,.0f",
        "strict_contact_rate": ":.4f",
        "fomo_early_contact_rate": ":.4f",
        "median_ttfl_days": ":.2f",
    },
    title="Top HCM District Groups by Demand V3 Score",
)

fig.update_layout(height=750, yaxis_title="")
save_plot(fig, "top_hcm_demand_score.html")

# -----------------------------
# 13E. FOMO vs TTFL map — HCM
# x high = stronger FOMO
# y low = faster lead
# -----------------------------
plot_hcm2 = hcm_demand[
    hcm_demand["analysis_eligible"]
].copy()

fig = px.scatter(
    plot_hcm2,
    x="fomo_early_contact_rate",
    y="median_ttfl_days",
    size="listing_count",
    color="demand_segment",
    hover_name="group_label",
    hover_data={
        "listing_count": ":,.0f",
        "pageviews": ":,.0f",
        "strict_contact_rate": ":.4f",
        "strict_contact_per_listing": ":.4f",
        "items_with_lead": ":,.0f",
        "demand_score": ":.3f",
    },
    title="HCM Demand Map: FOMO Rate vs Median TTFL<br>Right = stronger early demand, Lower = faster lead",
)

fig.update_yaxes(autorange="reversed")
fig.update_layout(height=650)
save_plot(fig, "hcm_fomo_vs_ttfl.html")

# -----------------------------
# 13F. Segment count
# -----------------------------
seg_city = (
    city_demand["demand_segment"]
    .value_counts()
    .reset_index()
)
seg_city.columns = ["demand_segment", "groups"]

fig = px.bar(
    seg_city,
    x="demand_segment",
    y="groups",
    title="City Group Count by Demand Segment",
)
fig.update_layout(height=500, xaxis_tickangle=-30)
save_plot(fig, "city_segment_count.html")

seg_hcm = (
    hcm_demand["demand_segment"]
    .value_counts()
    .reset_index()
)
seg_hcm.columns = ["demand_segment", "groups"]

fig = px.bar(
    seg_hcm,
    x="demand_segment",
    y="groups",
    title="HCM Group Count by Demand Segment",
)
fig.update_layout(height=500, xaxis_tickangle=-30)
save_plot(fig, "hcm_segment_count.html")

# ============================================================
# 14. OUTPUT FILES
# ============================================================

print("\nDONE. Output files:")
for f in sorted(os.listdir(CACHE_DIR)):
    print("-", os.path.join(CACHE_DIR, f))

Available Kaggle input folders:
/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/fact_listing_snapshot | sample: ['datathon_fact_listing_snapshot-000000000052.parquet', 'datathon_fact_listing_snapshot-000000000036.parquet']
/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/fact_post_contact_interactions | sample: ['datathon_fact_user_ad_interactions-000000000092.parquet', 'datathon_fact_user_ad_interactions-000000000099.parquet']
/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/dim_listing | sample: ['datathon_dim_listing-000000000012.parquet', 'datathon_dim_listing-000000000023.parquet']
/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/test | sample: ['test_users.parquet']
/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2/fact_user_events | sample: ['datathon_fact_user_events-000000000246.parquet', 'datathon_fact_user_events-000000000185.parquet']

[1/7] Building item_map from dim_listing...
dim_listing batches: 10
dim_listing batches: 20
dim_listing batches: 30
dim_listing batches: 40
item_map shape: (3107114, 7)

,item_id,city_name,district_name,category,category_name,ad_type,posted_date
0,bc8a95ba9c8c41b86fc446e58af07aacf1e98cb0a8f632...,Tp Hồ Chí Minh,Quận 3,1010,1010 - Phòng trọ / căn hộ thuê,let,2025-03-04
1,2e58d907f4986a98aa31700ae56883bbc85748932d58af...,Tp Hồ Chí Minh,Quận 8,1010,1010 - Phòng trọ / căn hộ thuê,let,2025-05-04
2,3d186c9e829ba17729a239816bcfe24c9e23bdd119f62c...,Tp Hồ Chí Minh,Quận 8,1010,1010 - Phòng trọ / căn hộ thuê,let,2025-04-17
3,e9f549a8c6b0ed5c823df7de5c0344d7b0b1777a65af61...,Tp Hồ Chí Minh,Quận 3,1010,1010 - Phòng trọ / căn hộ thuê,let,2025-07-03
4,6c30deece657bdce3cd0ab779e3dc0954ca775cd275379...,Tp Hồ Chí Minh,Quận Gò Vấp,1010,1010 - Phòng trọ / căn hộ thuê,let,2025-11-26

City group keys: ['city_name', 'category_name', 'ad_type']
HCM group keys: ['district_name', 'category_name', 'ad_type']

[2/7] Building supply tables...
city_supply: (508, 4)
hcm_supply: (200, 4)

          city_name                   category_name ad_type  listing_count
407  Tp Hồ Chí Minh        1020 - Căn hộ / chung cư    sell         733140
404  Tp Hồ Chí Minh  1010 - Phòng trọ / căn hộ thuê     let         373553
412  Tp Hồ Chí Minh       1050 - Dự án / căn hộ mới     let         325650
406  Tp Hồ Chí Minh        1020 - Căn hộ / chung cư     let         321968
408  Tp Hồ Chí Minh                    1030 - Nhà ở     let         175926
133          Hà Nội        1020 - Căn hộ / chung cư    sell         160037
411  Tp Hồ Chí Minh     1040 - Đất / BĐS thương mại    sell          99867
405  Tp Hồ Chí Minh  1010 - Phòng trọ / căn hộ thuê    sell          79612
467         Đà Nẵng        1020 - Căn hộ / chung cư    sell          57231
471         Đà Nẵng     1040 - Đất / BĐS thương mại    sell          48328
25       Bình Dương     1040 - Đất / BĐS thương mại    sell          44051
21       Bình Dương        1020 - Căn hộ / chung cư    sell          44033
131          Hà Nội  1010 - Phòng trọ / căn hộ thuê    sell          37518
466         Đà Nẵng        1020 - Căn hộ / chung cư     let          34115
137          Hà Nội     1040 - Đất / BĐS thương mại    sell          26548
130          Hà Nội  1010 - Phòng trọ / căn hộ thuê     let          26101
464         Đà Nẵng  1010 - Phòng trọ / căn hộ thuê     let          25626
227         Long An     1040 - Đất / BĐS thương mại    sell          25497
497        Đồng Nai     1040 - Đất / BĐS thương mại    sell          23023
493        Đồng Nai        1020 - Căn hộ / chung cư    sell          20277

         district_name                   category_name ad_type  listing_count
147      Quận Bình Tân        1020 - Căn hộ / chung cư    sell          90354
156        Quận Gò Vấp        1020 - Căn hộ / chung cư    sell          84777
75             Quận 12        1020 - Căn hộ / chung cư    sell          71540
193  Thành phố Thủ Đức        1020 - Căn hộ / chung cư    sell          70658
183       Quận Tân Phú        1020 - Căn hộ / chung cư    sell          59114
161        Quận Gò Vấp       1050 - Dự án / căn hộ mới     let          51298
135    Quận Bình Thạnh  1010 - Phòng trọ / căn hộ thuê     let          46815
174      Quận Tân Bình        1020 - Căn hộ / chung cư    sell          46272
138    Quận Bình Thạnh        1020 - Căn hộ / chung cư    sell          45568
120             Quận 7        1020 - Căn hộ / chung cư    sell          44566
190  Thành phố Thủ Đức  1010 - Phòng trọ / căn hộ thuê     let          43253
155        Quận Gò Vấp        1020 - Căn hộ / chung cư     let          43087
192  Thành phố Thủ Đức        1020 - Căn hộ / chung cư     let          40158
171      Quận Tân Bình  1010 - Phòng trọ / căn hộ thuê     let          38143
143    Quận Bình Thạnh       1050 - Dự án / căn hộ mới     let          36278
188       Quận Tân Phú       1050 - Dự án / căn hộ mới     let          36094
129             Quận 8        1020 - Căn hộ / chung cư    sell          35458
117             Quận 7  1010 - Phòng trọ / căn hộ thuê     let          33907
179      Quận Tân Bình       1050 - Dự án / căn hộ mới     let          32785
198  Thành phố Thủ Đức       1050 - Dự án / căn hộ mới     let          31300

[3/7] Scanning fact_listing_snapshot for FOMO + TTFL...
snapshot batches: 20
snapshot batches: 40
snapshot batches: 60
city_fomo: (447, 9)
hcm_fomo: (198, 9)
item_first_lead: (480023, 2)

,total_snapshot_rows,unmapped_item_rows,negative_age_rows,missing_views_rows,missing_contacts_rows,valid_fomo_rows,valid_first_lead_rows,valid_fomo_rate,valid_first_lead_rate
0,19762167,447987,35,9288229,17421114,3834996,2288366,0.194057,0.115795

[4/7] Building TTFL group tables...
city_ttfl: (437, 8)
hcm_ttfl: (198, 8)

,city_name,category_name,ad_type,items_with_lead,median_ttfl_days,mean_ttfl_days,p25_ttfl_days,p75_ttfl_days
354,Tp Hồ Chí Minh,1020 - Căn hộ / chung cư,sell,111016,0.0,14.769114,0.0,6.00
359,Tp Hồ Chí Minh,1050 - Dự án / căn hộ mới,let,59506,0.0,12.285064,0.0,2.00
353,Tp Hồ Chí Minh,1020 - Căn hộ / chung cư,let,52334,1.0,12.937307,0.0,5.00
351,Tp Hồ Chí Minh,1010 - Phòng trọ / căn hộ thuê,let,46111,1.0,23.613238,0.0,10.00
355,Tp Hồ Chí Minh,1030 - Nhà ở,let,27006,1.0,16.478634,0.0,8.00
358,Tp Hồ Chí Minh,1040 - Đất / BĐS thương mại,sell,18665,0.0,22.072917,0.0,16.00
123,Hà Nội,1020 - Căn hộ / chung cư,sell,15347,0.0,15.142960,0.0,8.00
352,Tp Hồ Chí Minh,1010 - Phòng trọ / căn hộ thuê,sell,14954,0.0,22.004614,0.0,12.00
401,Đà Nẵng,1020 - Căn hộ / chung cư,sell,8382,0.0,8.951205,0.0,3.00
21,Bình Dương,1020 - Căn hộ / chung cư,sell,7768,0.0,14.588182,0.0,8.00
405,Đà Nẵng,1040 - Đất / BĐS thương mại,sell,7470,0.0,11.124900,0.0,5.00
25,Bình Dương,1040 - Đất / BĐS thương mại,sell,6846,0.0,17.157756,0.0,11.00
121,Hà Nội,1010 - Phòng trọ / căn hộ thuê,sell,5340,0.0,12.225094,0.0,2.00
400,Đà Nẵng,1020 - Căn hộ / chung cư,let,4938,0.0,8.137708,0.0,3.00
426,Đồng Nai,1040 - Đất / BĐS thương mại,sell,4781,0.0,19.925120,0.0,15.00
202,Long An,1040 - Đất / BĐS thương mại,sell,4514,0.0,19.394772,0.0,13.75
128,Hà Nội,1050 - Dự án / căn hộ mới,let,4393,0.0,10.534031,0.0,2.00
120,Hà Nội,1010 - Phòng trọ / căn hộ thuê,let,4024,1.0,14.860338,0.0,7.00
19,Bình Dương,1010 - Phòng trọ / căn hộ thuê,sell,3624,0.0,26.799669,0.0,11.00
398,Đà Nẵng,1010 - Phòng trọ / căn hộ thuê,let,3409,1.0,11.367556,0.0,4.00

,district_name,category_name,ad_type,items_with_lead,median_ttfl_days,mean_ttfl_days,p25_ttfl_days,p75_ttfl_days
146,Quận Bình Tân,1020 - Căn hộ / chung cư,sell,13444,0.0,13.105326,0.0,5.0
192,Thành phố Thủ Đức,1020 - Căn hộ / chung cư,sell,12063,0.0,16.636160,0.0,9.0
155,Quận Gò Vấp,1020 - Căn hộ / chung cư,sell,11948,0.0,13.301473,0.0,5.0
74,Quận 12,1020 - Căn hộ / chung cư,sell,10747,0.0,14.187680,0.0,6.0
182,Quận Tân Phú,1020 - Căn hộ / chung cư,sell,8571,0.0,13.477307,0.0,5.0
160,Quận Gò Vấp,1050 - Dự án / căn hộ mới,let,8287,0.0,9.314589,0.0,2.0
137,Quận Bình Thạnh,1020 - Căn hộ / chung cư,sell,7253,0.0,12.590652,0.0,5.0
197,Thành phố Thủ Đức,1050 - Dự án / căn hộ mới,let,7145,0.0,15.690693,0.0,4.0
173,Quận Tân Bình,1020 - Căn hộ / chung cư,sell,6944,0.0,14.069988,0.0,6.0
154,Quận Gò Vấp,1020 - Căn hộ / chung cư,let,6770,0.0,8.300148,0.0,4.0
191,Thành phố Thủ Đức,1020 - Căn hộ / chung cư,let,6762,1.0,11.999704,0.0,7.0
187,Quận Tân Phú,1050 - Dự án / căn hộ mới,let,6207,0.0,9.438376,0.0,2.0
189,Thành phố Thủ Đức,1010 - Phòng trọ / căn hộ thuê,let,6072,2.0,30.702240,0.0,16.0
142,Quận Bình Thạnh,1050 - Dự án / căn hộ mới,let,5874,0.0,15.670242,0.0,2.0
119,Quận 7,1020 - Căn hộ / chung cư,sell,5730,0.0,16.897208,0.0,8.0
178,Quận Tân Bình,1050 - Dự án / căn hộ mới,let,5424,0.0,10.435656,0.0,2.0
128,Quận 8,1020 - Căn hộ / chung cư,sell,5348,0.0,13.890987,0.0,6.0
145,Quận Bình Tân,1020 - Căn hộ / chung cư,let,5326,1.0,8.403117,0.0,4.0
196,Thành phố Thủ Đức,1040 - Đất / BĐS thương mại,sell,4920,0.0,18.368902,0.0,14.0
151,Quận Bình Tân,1050 - Dự án / căn hộ mới,let,4781,0.0,13.735202,0.0,3.0

[5/7] Scanning fact_user_events for traffic + strict contact rate...
event batches: 20
event batches: 40
event batches: 60
event batches: 80
event batches: 100
event batches: 120
event batches: 140
event batches: 160
event batches: 180
event batches: 200
event batches: 220
event batches: 240
event batches: 260
event batches: 280
event batches: 300
event batches: 320
event batches: 340
event batches: 360
event batches: 380
event batches: 400
event batches: 420
event batches: 440
event batches: 460
event batches: 480
event batches: 500
event batches: 520
event batches: 540
event batches: 560
event batches: 580
event batches: 600
event batches: 620
event batches: 640
event batches: 660
event batches: 680
event batches: 700
event batches: 720
event batches: 740
event batches: 760
event batches: 780
event batches: 800
event batches: 820
event batches: 840
event batches: 860
event batches: 880
event batches: 900
event batches: 920
event batches: 940
event batches: 960
event batches: 980
event batches: 1000
city_traffic: (718, 7)
hcm_traffic: (198, 7)

,city_name,category_name,ad_type,pageviews,strict_contact,all_positive,total_events
393,Tp Hồ Chí Minh,1050 - Dự án / căn hộ mới,let,15608238.0,1022855.0,18488811.0,34097049.0
385,Tp Hồ Chí Minh,1020 - Căn hộ / chung cư,sell,10476748.0,1000669.0,17603284.0,28080032.0
384,Tp Hồ Chí Minh,1020 - Căn hộ / chung cư,let,9679102.0,852031.0,14820751.0,24499853.0
381,Tp Hồ Chí Minh,1010 - Phòng trọ / căn hộ thuê,let,5475713.0,448119.0,9459645.0,14935358.0
387,Tp Hồ Chí Minh,1030 - Nhà ở,let,3269164.0,265340.0,3531408.0,6800572.0
382,Tp Hồ Chí Minh,1010 - Phòng trọ / căn hộ thuê,sell,1874434.0,161257.0,3658122.0,5532556.0
391,Tp Hồ Chí Minh,1040 - Đất / BĐS thương mại,sell,1517807.0,174530.0,1766930.0,3284737.0
145,Hà Nội,1020 - Căn hộ / chung cư,sell,1048685.0,101589.0,1783115.0,2831800.0
437,Đà Nẵng,1020 - Căn hộ / chung cư,sell,1034340.0,73625.0,1178692.0,2213032.0
29,Bình Dương,1020 - Căn hộ / chung cư,sell,840414.0,69628.0,1345768.0,2186182.0
443,Đà Nẵng,1040 - Đất / BĐS thương mại,sell,829592.0,59175.0,793087.0,1622679.0
153,Hà Nội,1050 - Dự án / căn hộ mới,let,813003.0,72157.0,979449.0,1792452.0
392,Tp Hồ Chí Minh,1050 - Dự án / căn hộ mới,Unknown Ad Type,676740.0,46492.0,985072.0,1661812.0
445,Đà Nẵng,1050 - Dự án / căn hộ mới,let,673715.0,63736.0,852908.0,1526623.0
436,Đà Nẵng,1020 - Căn hộ / chung cư,let,638691.0,66792.0,975343.0,1614034.0
433,Đà Nẵng,1010 - Phòng trọ / căn hộ thuê,let,595040.0,46349.0,1239256.0,1834296.0
35,Bình Dương,1040 - Đất / BĐS thương mại,sell,548525.0,58715.0,676890.0,1225415.0
144,Hà Nội,1020 - Căn hộ / chung cư,let,434378.0,69699.0,692663.0,1127041.0
142,Hà Nội,1010 - Phòng trọ / căn hộ thuê,sell,417795.0,43360.0,820200.0,1237995.0
141,Hà Nội,1010 - Phòng trọ / căn hộ thuê,let,410406.0,49573.0,736590.0,1146996.0

,district_name,category_name,ad_type,pageviews,strict_contact,all_positive,total_events
187,Thành phố Thủ Đức,1050 - Dự án / căn hộ mới,let,2037976.0,138825.0,2729011.0,4766987.0
151,Quận Gò Vấp,1050 - Dự án / căn hộ mới,let,1889803.0,114741.0,2014263.0,3904066.0
133,Quận Bình Thạnh,1050 - Dự án / căn hộ mới,let,1826744.0,120555.0,2249295.0,4076039.0
168,Quận Tân Bình,1050 - Dự án / căn hộ mới,let,1285604.0,84304.0,1526868.0,2812472.0
182,Thành phố Thủ Đức,1020 - Căn hộ / chung cư,sell,1156111.0,117318.0,2114154.0,3270265.0
145,Quận Gò Vấp,1020 - Căn hộ / chung cư,let,1144256.0,99860.0,1650582.0,2794838.0
68,Quận 12,1020 - Căn hộ / chung cư,sell,1107237.0,86854.0,1803626.0,2910863.0
142,Quận Bình Tân,1050 - Dự án / căn hộ mới,let,1104987.0,70026.0,1108734.0,2213721.0
181,Thành phố Thủ Đức,1020 - Căn hộ / chung cư,let,1089876.0,97612.0,1904647.0,2994523.0
115,Quận 7,1050 - Dự án / căn hộ mới,let,1080405.0,68126.0,1328260.0,2408665.0
177,Quận Tân Phú,1050 - Dự án / căn hộ mới,let,1065560.0,69863.0,1188518.0,2254078.0
73,Quận 12,1050 - Dự án / căn hộ mới,let,1047413.0,65174.0,1152172.0,2199585.0
137,Quận Bình Tân,1020 - Căn hộ / chung cư,sell,984487.0,97820.0,1544923.0,2529410.0
67,Quận 12,1020 - Căn hộ / chung cư,let,973553.0,70628.0,1382161.0,2355714.0
146,Quận Gò Vấp,1020 - Căn hộ / chung cư,sell,960317.0,106790.0,1571020.0,2531337.0
136,Quận Bình Tân,1020 - Căn hộ / chung cư,let,862754.0,67321.0,1149819.0,2012573.0
127,Quận Bình Thạnh,1020 - Căn hộ / chung cư,let,800048.0,71196.0,1306047.0,2106095.0
179,Thành phố Thủ Đức,1010 - Phòng trọ / căn hộ thuê,let,796637.0,68845.0,1502839.0,2299476.0
56,Quận 10,1050 - Dự án / căn hộ mới,let,778999.0,49475.0,967072.0,1746071.0
124,Quận 8,1050 - Dự án / căn hộ mới,let,688479.0,43840.0,769010.0,1457489.0

[6/7] Merging supply + FOMO + TTFL + traffic...
[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/city_demand_v3_fomo_ttfl_traffic.csv
[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_district_demand_v3_fomo_ttfl_traffic.csv

Top confirmed / high-score city groups:

,group_label,listing_count,pageviews,strict_contact,strict_contact_rate,strict_contact_per_listing,early_views_24h,early_contacts_24h,fomo_early_contact_rate,items_with_lead,lead_listing_rate,median_ttfl_days,demand_score,demand_segment
202,Hà Nội | 1020 - Căn hộ / chung cư | let,19676.0,434378.0,69699.0,0.160457,3.542336,220162.0,39043.0,0.177338,3390.0,0.172291,0.0,0.906180,Confirmed hot demand
205,Hà Nội | 1030 - Nhà ở | let,13734.0,167352.0,27401.0,0.163733,1.995122,76463.0,14904.0,0.194918,2485.0,0.180938,0.0,0.855618,Confirmed hot demand
616,Tp Hồ Chí Minh | 1040 - Đất / BĐS thương mại |...,99867.0,1517807.0,174530.0,0.114988,1.747624,546239.0,79816.0,0.146119,18665.0,0.186899,0.0,0.795506,Confirmed hot demand
25,Bà Rịa - Vũng Tàu | 1040 - Đất / BĐS thương mạ...,10547.0,195940.0,20182.0,0.103001,1.913530,72849.0,8949.0,0.122843,2275.0,0.215701,0.0,0.776966,Confirmed hot demand
270,Hải Phòng | 1020 - Căn hộ / chung cư | let,1031.0,12872.0,2273.0,0.176585,2.204656,4592.0,675.0,0.146995,110.0,0.106693,1.0,0.770225,Normal / mixed
346,Long An | 1040 - Đất / BĐS thương mại | sell,25497.0,354567.0,41226.0,0.116271,1.616896,125321.0,17571.0,0.140208,4514.0,0.177040,0.0,0.767978,Confirmed hot demand
704,Đà Nẵng | 1020 - Căn hộ / chung cư | let,34115.0,638691.0,66792.0,0.104576,1.957848,411590.0,43155.0,0.104849,4938.0,0.144746,0.0,0.764045,Confirmed hot demand
750,Đồng Nai | 1040 - Đất / BĐS thương mại | sell,23023.0,363334.0,38934.0,0.107158,1.691092,137913.0,17377.0,0.126000,4781.0,0.207662,0.0,0.752247,Confirmed hot demand
199,Hà Nội | 1010 - Phòng trọ / căn hộ thuê | let,26101.0,410406.0,49573.0,0.120790,1.899276,183826.0,25780.0,0.140241,4024.0,0.154170,1.0,0.735393,Normal / mixed
713,Đà Nẵng | 1050 - Dự án / căn hộ mới | let,5803.0,673715.0,63736.0,0.094604,10.983285,349362.0,28467.0,0.081483,1509.0,0.260038,0.0,0.711798,Fast liquidity
19,Bà Rịa - Vũng Tàu | 1020 - Căn hộ / chung cư |...,3667.0,125649.0,11169.0,0.088890,3.045814,47693.0,4533.0,0.095045,809.0,0.220616,0.0,0.705056,Fast liquidity
650,Tây Ninh | 1040 - Đất / BĐS thương mại | sell,8000.0,120394.0,12156.0,0.100968,1.519500,45933.0,5275.0,0.114841,1607.0,0.200875,0.0,0.696629,Normal / mixed
68,Bình Thuận | 1040 - Đất / BĐS thương mại | sell,3429.0,37934.0,4425.0,0.116650,1.290464,13767.0,1654.0,0.120142,640.0,0.186643,0.0,0.694382,FOMO fast but traffic thin
39,Bình Dương | 1040 - Đất / BĐS thương mại | sell,44051.0,548525.0,58715.0,0.107042,1.332887,216323.0,26135.0,0.120815,6846.0,0.155411,0.0,0.690449,FOMO fast but traffic thin
18,Bà Rịa - Vũng Tàu | 1020 - Căn hộ / chung cư |...,1026.0,33966.0,3684.0,0.108461,3.590643,14193.0,1304.0,0.091876,221.0,0.215400,1.0,0.682584,Normal / mixed
607,Tp Hồ Chí Minh | 1010 - Phòng trọ / căn hộ thu...,79612.0,1874434.0,161257.0,0.086030,2.025536,698656.0,69993.0,0.100182,14954.0,0.187836,0.0,0.682584,Fast liquidity
211,Hà Nội | 1050 - Dự án / căn hộ mới | let,18819.0,813003.0,72157.0,0.088754,3.834263,364334.0,30749.0,0.084398,4393.0,0.233434,0.0,0.682022,Fast liquidity
610,Tp Hồ Chí Minh | 1020 - Căn hộ / chung cư | sell,733140.0,10476748.0,1000669.0,0.095513,1.364908,4616290.0,545984.0,0.118273,111016.0,0.151425,0.0,0.662921,FOMO fast but traffic thin
613,Tp Hồ Chí Minh | 1030 - Nhà ở | sell,9255.0,115961.0,13038.0,0.112434,1.408752,48395.0,7622.0,0.157496,1417.0,0.153106,1.0,0.661236,Normal / mixed
209,Hà Nội | 1040 - Đất / BĐS thương mại | sell,26548.0,239006.0,28004.0,0.117169,1.054844,97594.0,12542.0,0.128512,3323.0,0.125170,0.0,0.657303,FOMO fast but traffic thin
365,Lâm Đồng | 1020 - Căn hộ / chung cư | sell,4131.0,89535.0,8020.0,0.089574,1.941419,23167.0,2758.0,0.119049,600.0,0.145243,1.0,0.650000,Normal / mixed
30,Bình Dương | 1010 - Phòng trọ / căn hộ thuê | ...,17568.0,274024.0,25754.0,0.093984,1.465961,100841.0,10053.0,0.099692,3624.0,0.206284,0.0,0.644382,Normal / mixed
371,Lâm Đồng | 1040 - Đất / BĐS thương mại | sell,9499.0,115541.0,13226.0,0.114470,1.392357,31716.0,4425.0,0.139519,1472.0,0.154964,1.0,0.642135,Normal / mixed
615,Tp Hồ Chí Minh | 1040 - Đất / BĐS thương mại |...,3504.0,125903.0,11464.0,0.091054,3.271689,49012.0,4669.0,0.095262,794.0,0.226598,1.0,0.641573,Normal / mixed
477,Quảng Nam | 1040 - Đất / BĐS thương mại | sell,6596.0,138365.0,12117.0,0.087573,1.837022,53764.0,5251.0,0.097668,1333.0,0.202092,0.0,0.639888,Fast liquidity
337,Long An | 1010 - Phòng trọ / căn hộ thuê | sell,1636.0,22069.0,2041.0,0.092483,1.247555,8266.0,1060.0,0.128236,517.0,0.316015,0.0,0.634831,FOMO fast but traffic thin
292,Hậu Giang | 1040 - Đất / BĐS thương mại | sell,1295.0,20517.0,1834.0,0.089389,1.416216,6712.0,684.0,0.101907,260.0,0.200772,0.0,0.632022,Normal / mixed
710,Đà Nẵng | 1040 - Đất / BĐS thương mại | let,1862.0,32757.0,3612.0,0.110267,1.939850,15925.0,1473.0,0.092496,363.0,0.194952,1.0,0.629213,Normal / mixed
200,Hà Nội | 1010 - Phòng trọ / căn hộ thuê | sell,37518.0,417795.0,43360.0,0.103783,1.155712,203379.0,23379.0,0.114953,5340.0,0.142332,0.0,0.619101,FOMO fast but traffic thin
588,Thừa Thiên Huế | 1040 - Đất / BĐS thương mại |...,1869.0,31166.0,2748.0,0.088173,1.470305,13066.0,1316.0,0.100719,271.0,0.144997,0.0,0.618539,Normal / mixed

Top confirmed / high-score HCM district groups:

,group_label,listing_count,pageviews,strict_contact,strict_contact_rate,strict_contact_per_listing,early_views_24h,early_contacts_24h,fomo_early_contact_rate,items_with_lead,lead_listing_rate,median_ttfl_days,demand_score,demand_segment
55,Quận 10 | 1010 - Phòng trọ / căn hộ thuê | sell,1382,57101.0,5998.0,0.105042,4.340087,23066.0,2842.0,0.123212,403.0,0.291606,0.0,0.814437,Confirmed hot demand
187,Quận Tân Phú | 1040 - Đất / BĐS thương mại | sell,1154,18496.0,2308.0,0.124784,2.000000,8775.0,1494.0,0.170256,223.0,0.193241,0.0,0.791901,FOMO fast but traffic thin
92,Quận 4 | 1020 - Căn hộ / chung cư | let,2463,161315.0,16341.0,0.101299,6.634592,78592.0,8257.0,0.105062,519.0,0.210719,0.0,0.779225,Confirmed hot demand
46,Quận 1 | 1010 - Phòng trọ / căn hộ thuê | sell,1291,27830.0,3297.0,0.118469,2.553834,10328.0,1380.0,0.133617,265.0,0.205267,0.0,0.776056,Confirmed hot demand
64,Quận 11 | 1010 - Phòng trọ / căn hộ thuê | sell,1065,36599.0,3580.0,0.097817,3.361502,15512.0,1951.0,0.125774,257.0,0.241315,0.0,0.770423,Confirmed hot demand
176,Quận Tân Bình | 1030 - Nhà ở | sell,614,6946.0,1062.0,0.152894,1.729642,3022.0,612.0,0.202515,96.0,0.156352,0.0,0.761268,FOMO fast but traffic thin
84,Quận 3 | 1020 - Căn hộ / chung cư | sell,14486,198638.0,25989.0,0.130836,1.794077,89020.0,14613.0,0.164154,2230.0,0.153942,0.0,0.759859,FOMO fast but traffic thin
48,Quận 1 | 1020 - Căn hộ / chung cư | sell,10267,138952.0,18160.0,0.130693,1.768774,58028.0,9826.0,0.169332,1444.0,0.140645,0.0,0.759155,FOMO fast but traffic thin
178,Quận Tân Bình | 1040 - Đất / BĐS thương mại | ...,626,8862.0,1088.0,0.122771,1.738019,4131.0,736.0,0.178165,121.0,0.193291,0.0,0.755282,FOMO fast but traffic thin
7,Huyện Bình Chánh | 1040 - Đất / BĐS thương mại...,7027,176657.0,18254.0,0.103330,2.597695,53480.0,6826.0,0.127636,1540.0,0.219155,0.0,0.745775,Confirmed hot demand
25,Huyện Củ Chi | 1040 - Đất / BĐS thương mại | sell,18097,266539.0,32481.0,0.121862,1.794828,97888.0,14127.0,0.144318,3037.0,0.167818,0.0,0.745423,FOMO fast but traffic thin
16,Huyện Cần Giờ | 1040 - Đất / BĐS thương mại | ...,1306,32823.0,3474.0,0.105840,2.660031,9402.0,1119.0,0.119017,309.0,0.236600,0.0,0.740141,Confirmed hot demand
136,Quận Bình Thạnh | 1010 - Phòng trọ / căn hộ th...,3897,117695.0,11853.0,0.100709,3.041570,46670.0,5271.0,0.112942,930.0,0.238645,0.0,0.738732,Confirmed hot demand
82,Quận 3 | 1010 - Phòng trọ / căn hộ thuê | sell,551,19484.0,1837.0,0.094282,3.333938,7624.0,903.0,0.118442,131.0,0.237750,0.0,0.738028,Confirmed hot demand
197,Thành phố Thủ Đức | 1040 - Đất / BĐS thương mạ...,26448,316248.0,41865.0,0.132380,1.582917,123527.0,20902.0,0.169210,4920.0,0.186025,0.0,0.727817,FOMO fast but traffic thin
133,Quận 8 | 1040 - Đất / BĐS thương mại | sell,929,19720.0,1972.0,0.100000,2.122713,6042.0,843.0,0.139523,223.0,0.240043,0.0,0.715141,Normal / mixed
172,Quận Tân Bình | 1010 - Phòng trọ / căn hộ thuê...,3014,69854.0,7048.0,0.100896,2.338421,29794.0,3646.0,0.122374,597.0,0.198076,0.0,0.710915,Confirmed hot demand
154,Quận Gò Vấp | 1010 - Phòng trọ / căn hộ thuê |...,2445,83199.0,7993.0,0.096071,3.269121,35702.0,3677.0,0.102991,507.0,0.207362,0.0,0.703169,Fast liquidity
102,Quận 5 | 1020 - Căn hộ / chung cư | sell,7044,89767.0,10907.0,0.121503,1.548410,39516.0,5669.0,0.143461,970.0,0.137706,0.0,0.690141,FOMO fast but traffic thin
138,Quận Bình Thạnh | 1020 - Căn hộ / chung cư | sell,45568,569873.0,67784.0,0.118946,1.487535,267220.0,40010.0,0.149727,7253.0,0.159169,0.0,0.688028,FOMO fast but traffic thin
79,Quận 12 | 1040 - Đất / BĐS thương mại | sell,13730,215114.0,23361.0,0.108598,1.701457,78543.0,10743.0,0.136779,2480.0,0.180626,0.0,0.684155,FOMO fast but traffic thin
160,Quận Gò Vấp | 1040 - Đất / BĐS thương mại | sell,2866,44284.0,5479.0,0.123724,1.911724,17124.0,2850.0,0.166433,530.0,0.184927,1.0,0.682042,Normal / mixed
151,Quận Bình Tân | 1040 - Đất / BĐS thương mại | ...,7031,99604.0,11119.0,0.111632,1.581425,36217.0,5136.0,0.141812,1305.0,0.185607,0.0,0.680282,FOMO fast but traffic thin
182,Quận Tân Phú | 1020 - Căn hộ / chung cư | let,28104,650345.0,63080.0,0.096995,2.244520,367383.0,39636.0,0.107887,4007.0,0.142578,0.0,0.670070,Confirmed hot demand
34,Huyện Hóc Môn | 1040 - Đất / BĐS thương mại | ...,9906,187132.0,18298.0,0.097781,1.847163,67214.0,8300.0,0.123486,2013.0,0.203210,0.0,0.668310,Normal / mixed
56,Quận 10 | 1020 - Căn hộ / chung cư | let,11554,292342.0,31718.0,0.108496,2.745196,136037.0,16665.0,0.122503,1729.0,0.149645,1.0,0.667254,Normal / mixed
142,Quận Bình Thạnh | 1040 - Đất / BĐS thương mại ...,1498,19621.0,2585.0,0.131747,1.725634,6563.0,1139.0,0.173549,312.0,0.208278,1.0,0.663028,Normal / mixed
165,Quận Phú Nhuận | 1020 - Căn hộ / chung cư | sell,24097,242877.0,31266.0,0.128732,1.297506,126677.0,19294.0,0.152309,3511.0,0.145703,0.0,0.662676,FOMO fast but traffic thin
158,Quận Gò Vấp | 1030 - Nhà ở | sell,701,11408.0,1302.0,0.114130,1.857347,5121.0,798.0,0.155829,117.0,0.166904,1.0,0.658803,Normal / mixed
174,Quận Tân Bình | 1020 - Căn hộ / chung cư | sell,46272,569641.0,65594.0,0.115150,1.417574,262962.0,37733.0,0.143492,6944.0,0.150069,0.0,0.658099,FOMO fast but traffic thin

Potential high attention but low conversion — city:

,group_label,listing_count,pageviews_per_listing,strict_contact_rate,strict_contact_per_listing,median_ttfl_days,demand_segment
41,Bình Dương | 1050 - Dự án / căn hộ mới | let,4186.0,81.071667,0.072963,5.915194,0.0,"High attention, low conversion"
618,Tp Hồ Chí Minh | 1050 - Dự án / căn hộ mới | let,325650.0,47.929489,0.065533,3.140964,0.0,"High attention, low conversion"
167,Cần Thơ | 1050 - Dự án / căn hộ mới | let,3103.0,36.121818,0.060177,2.173703,0.0,"High attention, low conversion"
11,An Giang | 1040 - Đất / BĐS thương mại | sell,1042.0,32.221689,0.057841,1.863724,0.0,"High attention, low conversion"
16,Bà Rịa - Vũng Tàu | 1010 - Phòng trọ / căn hộ ...,1295.0,29.535135,0.076265,2.252510,0.0,"High attention, low conversion"
471,Quảng Nam | 1020 - Căn hộ / chung cư | sell,1004.0,26.564741,0.064077,1.702191,0.0,"High attention, low conversion"
296,Khánh Hòa | 1010 - Phòng trọ / căn hộ thuê | let,2540.0,25.054331,0.077375,1.938583,1.0,"High attention, low conversion"
136,Bến Tre | 1040 - Đất / BĐS thương mại | sell,1633.0,24.287814,0.078060,1.895897,0.0,"High attention, low conversion"
596,Tiền Giang | 1020 - Căn hộ / chung cư | sell,2006.0,23.899302,0.046848,1.119641,0.0,"High attention, low conversion"
663,Vĩnh Long | 1020 - Căn hộ / chung cư | sell,1755.0,23.245584,0.045740,1.063248,0.0,"High attention, low conversion"
701,Đà Nẵng | 1010 - Phòng trọ / căn hộ thuê | let,25626.0,23.220167,0.077892,1.808671,1.0,"High attention, low conversion"
602,Tiền Giang | 1040 - Đất / BĐS thương mại | sell,4171.0,23.114841,0.073715,1.703908,0.0,"High attention, low conversion"
165,Cần Thơ | 1040 - Đất / BĐS thương mại | sell,9267.0,22.876120,0.056096,1.283263,0.0,"High attention, low conversion"
156,Cần Thơ | 1010 - Phòng trọ / căn hộ thuê | sell,1572.0,22.508270,0.056129,1.263359,0.0,"High attention, low conversion"
644,Tây Ninh | 1020 - Căn hộ / chung cư | sell,2712.0,22.016962,0.069720,1.535029,0.0,"High attention, low conversion"
159,Cần Thơ | 1020 - Căn hộ / chung cư | sell,15299.0,20.825413,0.045090,0.939016,0.0,"High attention, low conversion"
669,Vĩnh Long | 1040 - Đất / BĐS thương mại | sell,2667.0,20.551556,0.063600,1.307087,0.0,"High attention, low conversion"
271,Hải Phòng | 1020 - Căn hộ / chung cư | sell,2435.0,20.550308,0.064229,1.319918,0.0,"High attention, low conversion"
277,Hải Phòng | 1040 - Đất / BĐS thương mại | sell,2223.0,19.908232,0.063901,1.272155,0.0,"High attention, low conversion"
582,Thừa Thiên Huế | 1020 - Căn hộ / chung cư | sell,1279.0,19.086787,0.066852,1.275997,0.0,"High attention, low conversion"

Potential oversupply / slow liquidity — HCM:

,group_label,listing_count,pageviews,strict_contact_rate,strict_contact_per_listing,median_ttfl_days,demand_segment
135,Quận Bình Thạnh | 1010 - Phòng trọ / căn hộ th...,46815,623163.0,0.087581,1.165802,1.0,Potential oversupply / slow liquidity
190,Thành phố Thủ Đức | 1010 - Phòng trọ / căn hộ ...,43253,796637.0,0.086420,1.591682,2.0,Potential oversupply / slow liquidity
171,Quận Tân Bình | 1010 - Phòng trọ / căn hộ thuê...,38143,466844.0,0.081006,0.991453,1.0,Potential oversupply / slow liquidity
117,Quận 7 | 1010 - Phòng trọ / căn hộ thuê | let,33907,509190.0,0.083912,1.260123,2.0,Potential oversupply / slow liquidity
180,Quận Tân Phú | 1010 - Phòng trọ / căn hộ thuê ...,29439,362770.0,0.079681,0.981895,1.0,Potential oversupply / slow liquidity
153,Quận Gò Vấp | 1010 - Phòng trọ / căn hộ thuê |...,27757,393002.0,0.058598,0.829665,1.0,Potential oversupply / slow liquidity
162,Quận Phú Nhuận | 1010 - Phòng trọ / căn hộ thu...,22974,247845.0,0.073994,0.798250,2.0,Potential oversupply / slow liquidity
194,Thành phố Thủ Đức | 1030 - Nhà ở | let,20963,368827.0,0.089869,1.581167,1.0,Potential oversupply / slow liquidity
54,Quận 10 | 1010 - Phòng trọ / căn hộ thuê | let,20886,308465.0,0.082405,1.217035,1.0,Potential oversupply / slow liquidity
45,Quận 1 | 1010 - Phòng trọ / căn hộ thuê | let,19578,186315.0,0.088291,0.840229,1.0,Potential oversupply / slow liquidity
81,Quận 3 | 1010 - Phòng trọ / căn hộ thuê | let,16435,203881.0,0.094383,1.170855,1.0,Potential oversupply / slow liquidity
49,Quận 1 | 1030 - Nhà ở | let,16344,203763.0,0.094899,1.183125,1.0,Potential oversupply / slow liquidity
126,Quận 8 | 1010 - Phòng trọ / căn hộ thuê | let,15359,265475.0,0.074327,1.284719,1.0,Potential oversupply / slow liquidity
184,Quận Tân Phú | 1030 - Nhà ở | let,13850,264256.0,0.074821,1.427581,1.0,Potential oversupply / slow liquidity
148,Quận Bình Tân | 1030 - Nhà ở | let,12704,233060.0,0.079310,1.454975,1.0,Potential oversupply / slow liquidity
175,Quận Tân Bình | 1030 - Nhà ở | let,12451,235891.0,0.084162,1.594490,1.0,Potential oversupply / slow liquidity
144,Quận Bình Tân | 1010 - Phòng trọ / căn hộ thuê...,12330,273079.0,0.066098,1.463909,1.0,Potential oversupply / slow liquidity

[7/7] Drawing charts...

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/city_supply_vs_demand_score.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_supply_vs_demand_score.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/top_city_demand_score.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/top_hcm_demand_score.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_fomo_vs_ttfl.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/city_segment_count.html

[SAVED] /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_segment_count.html

DONE. Output files:
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_demand_v3_fomo_ttfl_traffic.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_fomo.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_groups_too_small.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_segment_count.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_supply.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_supply_vs_demand_score.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_traffic.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/city_ttfl.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_district_demand_v3_fomo_ttfl_traffic.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_fomo.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_fomo_vs_ttfl.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_groups_too_small.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_segment_count.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_supply.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_supply_vs_demand_score.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_traffic.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/hcm_ttfl.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/item_first_lead.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/item_map.parquet
- /kaggle/working/demand_v3_fomo_ttfl_traffic/snapshot_dq_summary.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/top_city_confirmed_demand.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/top_city_demand_score.html
- /kaggle/working/demand_v3_fomo_ttfl_traffic/top_hcm_confirmed_demand.csv
- /kaggle/working/demand_v3_fomo_ttfl_traffic/top_hcm_demand_score.html