In [1]:
# ============================================================
# DATATHON 2026 — HALF-MONTH USER RETENTION / COHORT ANALYSIS
# ============================================================
# Ý tưởng:
# - Bucket nửa tháng:
#     H1 = ngày 01 -> 15
#     H2 = ngày 16 -> cuối tháng
# - Mỗi user có cohort = bucket đầu tiên user xuất hiện
# - Retention +k = user cohort đó có active lại ở bucket cohort + k hay không
#
# Output:
# - Retention heatmap
# - Average retention curve
# - Cohort size chart
# - Survival / return-after curve
# - Optional: city/category switching sau cohort
#
# Chạy 1 cell từ đầu tới cuối.
# ============================================================

import os
import sys
import subprocess
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np

# ============================================================
# 0. CONFIG
# ============================================================

# Sửa path này nếu dataset của bạn nằm chỗ khác
DATA_ROOT_CANDIDATES = [
    "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2",
    "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1",
    "/kaggle/input/datasets/luquang231/datathonvinu",
    "/kaggle/input/datathon2026-2",
    "/kaggle/input/datathon2026-1",
]

EVENTS_SUBDIR = "fact_user_events"

OUTPUT_DIR = "/kaggle/working/user_retention_half_month"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# login: đo retention user thật tốt hơn
# non-login: không khuyến nghị vì user_id đổi theo session
# all: nếu muốn gom cả login + non-login
LOGIN_MODE = "login"       # "login" | "non-login" | "all"

# Active definition:
# None = user active nếu có bất kỳ event nào trong bucket
# Hoặc set list event_type nếu chỉ muốn active = contact/pageview gì đó
ACTIVE_EVENT_TYPES = None
# Ví dụ:
# ACTIVE_EVENT_TYPES = ["pageview"]
# ACTIVE_EVENT_TYPES = ["view_phone", "contact_chat", "contact_zalo", "contact_sms"]

# Optional date filter. Để None thì auto dùng toàn bộ data.
START_DATE = None          # ví dụ "2024-09-01"
END_DATE = None            # ví dụ "2026-05-31"

# Nếu OOM, giảm threads xuống 1 hoặc 2
DUCKDB_MEMORY_LIMIT = "6GB"
DUCKDB_THREADS = 2
DUCKDB_MAX_TEMP_DIR_SIZE = "80GB"

# Switching analysis nặng hơn vì phải tính city/category mode theo user-bucket.
# Nếu bị OOM, đổi thành False.
DO_SWITCH_ANALYSIS = True

# Positive/contact event sets để thống kê thêm trong retention table
POSITIVE_EVENT_TYPES = [
    "view_phone", "contact_chat", "other_interaction", "contact_zalo", "contact_sms"
]
STRICT_CONTACT_EVENT_TYPES = [
    "view_phone", "contact_chat", "contact_zalo", "contact_sms"
]

# ============================================================
# 1. SETUP
# ============================================================

try:
    import duckdb
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "duckdb"])
    import duckdb

try:
    import plotly.express as px
    import plotly.graph_objects as go
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "plotly"])
    import plotly.express as px
    import plotly.graph_objects as go


def find_events_path():
    for root in DATA_ROOT_CANDIDATES:
        p = os.path.join(root, EVENTS_SUBDIR)
        if os.path.exists(p):
            return p
    
    # fallback: scan /kaggle/input
    for base, dirs, files in os.walk("/kaggle/input"):
        if os.path.basename(base) == EVENTS_SUBDIR:
            return base
    
    raise FileNotFoundError(
        "Không tìm thấy fact_user_events. Hãy sửa DATA_ROOT_CANDIDATES hoặc EVENTS_SUBDIR."
    )


EVENTS_PATH = find_events_path()
EVENTS_GLOB = os.path.join(EVENTS_PATH, "*.parquet").replace("\\", "/")

print("EVENTS_PATH:", EVENTS_PATH)
print("EVENTS_GLOB:", EVENTS_GLOB)
print("OUTPUT_DIR :", OUTPUT_DIR)

duckdb_path = os.path.join(OUTPUT_DIR, "retention_half_month.duckdb")
tmp_dir = os.path.join(OUTPUT_DIR, "duckdb_tmp")
os.makedirs(tmp_dir, exist_ok=True)

if os.path.exists(duckdb_path):
    os.remove(duckdb_path)

con = duckdb.connect(duckdb_path)

con.execute(f"PRAGMA threads={DUCKDB_THREADS}")
con.execute(f"PRAGMA memory_limit='{DUCKDB_MEMORY_LIMIT}'")
con.execute(f"PRAGMA temp_directory='{tmp_dir}'")
con.execute(f"PRAGMA max_temp_directory_size='{DUCKDB_MAX_TEMP_DIR_SIZE}'")
con.execute("SET preserve_insertion_order=false")

# ============================================================
# 2. SQL FILTERS
# ============================================================

def sql_str_list(values):
    return ", ".join(["'" + str(v).replace("'", "''").lower() + "'" for v in values])

login_filter_sql = ""
if LOGIN_MODE == "login":
    login_filter_sql = "AND LOWER(TRIM(CAST(is_login AS VARCHAR))) = 'login'"
elif LOGIN_MODE == "non-login":
    login_filter_sql = "AND LOWER(TRIM(CAST(is_login AS VARCHAR))) = 'non-login'"
elif LOGIN_MODE == "all":
    login_filter_sql = ""
else:
    raise ValueError("LOGIN_MODE phải là 'login', 'non-login', hoặc 'all'.")

active_filter_sql = ""
if ACTIVE_EVENT_TYPES is not None:
    active_filter_sql = f"""
    AND LOWER(TRIM(CAST(event_type AS VARCHAR))) IN ({sql_str_list(ACTIVE_EVENT_TYPES)})
    """

date_filter_sql = ""
if START_DATE is not None:
    date_filter_sql += f" AND event_date >= DATE '{START_DATE}' "
if END_DATE is not None:
    date_filter_sql += f" AND event_date <= DATE '{END_DATE}' "

positive_sql = sql_str_list(POSITIVE_EVENT_TYPES)
strict_contact_sql = sql_str_list(STRICT_CONTACT_EVENT_TYPES)

# ============================================================
# 3. QUICK DATA RANGE CHECK
# ============================================================

range_query = f"""
WITH src AS (
    SELECT
        COALESCE(
            TRY_CAST(date AS DATE),
            CAST(event_ts AS DATE)
        ) AS event_date,
        LOWER(TRIM(CAST(is_login AS VARCHAR))) AS is_login_clean
    FROM read_parquet('{EVENTS_GLOB}')
    WHERE COALESCE(TRY_CAST(date AS DATE), CAST(event_ts AS DATE)) IS NOT NULL
)
SELECT
    MIN(event_date) AS min_date,
    MAX(event_date) AS max_date,
    COUNT(*) AS total_rows,
    SUM(CASE WHEN is_login_clean = 'login' THEN 1 ELSE 0 END) AS login_rows,
    SUM(CASE WHEN is_login_clean = 'non-login' THEN 1 ELSE 0 END) AS non_login_rows
FROM src
"""

data_range_df = con.execute(range_query).df()
display(data_range_df)

data_range_df.to_csv(
    os.path.join(OUTPUT_DIR, "00_data_range_check.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 4. BUILD USER x HALF-MONTH BUCKET ACTIVITY
# ============================================================

print("\n[1/8] Building user_bucket_activity...")

create_user_bucket_activity_query = f"""
CREATE OR REPLACE TABLE user_bucket_activity AS
WITH src AS (
    SELECT
        CAST(user_id AS VARCHAR) AS user_id,

        COALESCE(
            TRY_CAST(date AS DATE),
            CAST(event_ts AS DATE)
        ) AS event_date,

        LOWER(TRIM(CAST(event_type AS VARCHAR))) AS event_type_clean,

        CASE
            WHEN city_name IS NULL OR TRIM(CAST(city_name AS VARCHAR)) = ''
            THEN NULL
            ELSE TRIM(CAST(city_name AS VARCHAR))
        END AS city_name_clean,

        TRY_CAST(category AS INTEGER) AS category_clean,

        LOWER(TRIM(CAST(is_login AS VARCHAR))) AS is_login_clean

    FROM read_parquet('{EVENTS_GLOB}')
    WHERE user_id IS NOT NULL
        {login_filter_sql}
        {active_filter_sql}
),
base AS (
    SELECT
        user_id,
        event_date,
        event_type_clean,
        city_name_clean,
        category_clean,

        CAST(
            EXTRACT(YEAR FROM event_date) * 24
            + (EXTRACT(MONTH FROM event_date) - 1) * 2
            + CASE
                WHEN EXTRACT(DAY FROM event_date) <= 15 THEN 0
                ELSE 1
              END
            AS BIGINT
        ) AS bucket_id

    FROM src
    WHERE event_date IS NOT NULL
        {date_filter_sql}
)
SELECT
    user_id,
    bucket_id,

    COUNT(*) AS events,
    SUM(CASE WHEN event_type_clean IN ({positive_sql}) THEN 1 ELSE 0 END) AS positive_events,
    SUM(CASE WHEN event_type_clean IN ({strict_contact_sql}) THEN 1 ELSE 0 END) AS strict_contact_events,

    COUNT(DISTINCT city_name_clean) AS distinct_cities_seen,
    COUNT(DISTINCT category_clean) AS distinct_categories_seen

FROM base
GROUP BY user_id, bucket_id
"""

con.execute(create_user_bucket_activity_query)

activity_summary_df = con.execute("""
SELECT
    COUNT(*) AS user_bucket_rows,
    COUNT(DISTINCT user_id) AS users,
    MIN(bucket_id) AS min_bucket_id,
    MAX(bucket_id) AS max_bucket_id,
    SUM(events) AS total_events,
    SUM(positive_events) AS total_positive_events,
    SUM(strict_contact_events) AS total_strict_contact_events
FROM user_bucket_activity
""").df()

display(activity_summary_df)
activity_summary_df.to_csv(
    os.path.join(OUTPUT_DIR, "01_user_bucket_activity_summary.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 5. BUILD BUCKET CALENDAR
# ============================================================

print("\n[2/8] Building bucket calendar...")

con.execute("""
CREATE OR REPLACE TABLE bucket_calendar AS
WITH lim AS (
    SELECT
        MIN(bucket_id) AS min_bucket_id,
        MAX(bucket_id) AS max_bucket_id
    FROM user_bucket_activity
),
ids AS (
    SELECT r.bucket_id
    FROM lim
    CROSS JOIN LATERAL range(
        CAST(min_bucket_id AS BIGINT),
        CAST(max_bucket_id + 1 AS BIGINT)
    ) AS r(bucket_id)
),
parts AS (
    SELECT
        bucket_id,
        CAST(FLOOR(bucket_id / 24) AS INTEGER) AS yy,
        CAST(FLOOR((bucket_id % 24) / 2) + 1 AS INTEGER) AS mm,
        CAST(bucket_id % 2 AS INTEGER) AS half_idx
    FROM ids
),
starts AS (
    SELECT
        bucket_id,
        yy,
        mm,
        half_idx,
        CAST(
            CAST(yy AS VARCHAR)
            || '-'
            || LPAD(CAST(mm AS VARCHAR), 2, '0')
            || '-01'
            AS DATE
        )
        + CASE
            WHEN half_idx = 1 THEN INTERVAL '15 days'
            ELSE INTERVAL '0 days'
          END AS bucket_start
    FROM parts
)
SELECT
    bucket_id,
    CAST(bucket_start AS DATE) AS bucket_start,

    CASE
        WHEN half_idx = 0 THEN CAST(bucket_start + INTERVAL '14 days' AS DATE)
        ELSE CAST(DATE_TRUNC('month', bucket_start) + INTERVAL '1 month' - INTERVAL '1 day' AS DATE)
    END AS bucket_end,

    STRFTIME(bucket_start, '%Y-%m')
        || CASE WHEN half_idx = 0 THEN '-H1' ELSE '-H2' END AS bucket_label,

    half_idx
FROM starts
ORDER BY bucket_id
""")

bucket_calendar_df = con.execute("SELECT * FROM bucket_calendar ORDER BY bucket_id").df()
display(bucket_calendar_df)

bucket_calendar_df.to_csv(
    os.path.join(OUTPUT_DIR, "02_bucket_calendar.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 6. COHORT = FIRST ACTIVE BUCKET OF USER
# ============================================================

print("\n[3/8] Building user cohorts...")

con.execute("""
CREATE OR REPLACE TABLE user_cohort AS
SELECT
    user_id,
    MIN(bucket_id) AS cohort_bucket_id
FROM user_bucket_activity
GROUP BY user_id
""")

con.execute("""
CREATE OR REPLACE TABLE cohort_sizes AS
SELECT
    c.cohort_bucket_id,
    bc.bucket_label AS cohort_label,
    bc.bucket_start AS cohort_start,
    bc.bucket_end AS cohort_end,
    COUNT(*) AS cohort_users
FROM user_cohort c
LEFT JOIN bucket_calendar bc
    ON c.cohort_bucket_id = bc.bucket_id
GROUP BY
    c.cohort_bucket_id,
    bc.bucket_label,
    bc.bucket_start,
    bc.bucket_end
ORDER BY c.cohort_bucket_id
""")

cohort_sizes_df = con.execute("SELECT * FROM cohort_sizes ORDER BY cohort_bucket_id").df()
display(cohort_sizes_df)

cohort_sizes_df.to_csv(
    os.path.join(OUTPUT_DIR, "03_cohort_sizes.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 7. EXACT RETENTION MATRIX
# ============================================================

print("\n[4/8] Building exact retention table...")

con.execute("""
CREATE OR REPLACE TABLE retention_counts AS
SELECT
    c.cohort_bucket_id,
    uba.bucket_id - c.cohort_bucket_id AS bucket_offset,

    COUNT(*) AS active_users,
    SUM(uba.events) AS events,
    SUM(uba.positive_events) AS positive_events,
    SUM(uba.strict_contact_events) AS strict_contact_events,

    AVG(uba.events) AS mean_events_per_active_user,
    AVG(uba.positive_events) AS mean_positive_events_per_active_user,
    AVG(uba.strict_contact_events) AS mean_strict_contact_events_per_active_user

FROM user_bucket_activity uba
JOIN user_cohort c
    ON uba.user_id = c.user_id
WHERE uba.bucket_id >= c.cohort_bucket_id
GROUP BY
    c.cohort_bucket_id,
    uba.bucket_id - c.cohort_bucket_id
""")

con.execute("""
CREATE OR REPLACE TABLE retention_long AS
WITH maxb AS (
    SELECT MAX(bucket_id) AS max_bucket_id
    FROM bucket_calendar
),
grid AS (
    SELECT
        cs.cohort_bucket_id,
        r.bucket_offset
    FROM cohort_sizes cs
    CROSS JOIN maxb
    CROSS JOIN LATERAL range(
        0,
        CAST(maxb.max_bucket_id - cs.cohort_bucket_id + 1 AS BIGINT)
    ) AS r(bucket_offset)
)
SELECT
    g.cohort_bucket_id,
    bc0.bucket_label AS cohort_label,
    bc0.bucket_start AS cohort_start,
    bc0.bucket_end AS cohort_end,

    g.bucket_offset,
    '+' || CAST(g.bucket_offset AS VARCHAR) AS offset_label,

    g.cohort_bucket_id + g.bucket_offset AS active_bucket_id,
    bc1.bucket_label AS active_bucket_label,
    bc1.bucket_start AS active_bucket_start,
    bc1.bucket_end AS active_bucket_end,

    cs.cohort_users,

    COALESCE(rc.active_users, 0) AS active_users,
    COALESCE(rc.events, 0) AS events,
    COALESCE(rc.positive_events, 0) AS positive_events,
    COALESCE(rc.strict_contact_events, 0) AS strict_contact_events,

    COALESCE(rc.active_users, 0) * 1.0 / NULLIF(cs.cohort_users, 0) AS retention_rate,

    rc.mean_events_per_active_user,
    rc.mean_positive_events_per_active_user,
    rc.mean_strict_contact_events_per_active_user

FROM grid g
JOIN cohort_sizes cs
    ON g.cohort_bucket_id = cs.cohort_bucket_id
LEFT JOIN retention_counts rc
    ON g.cohort_bucket_id = rc.cohort_bucket_id
    AND g.bucket_offset = rc.bucket_offset
LEFT JOIN bucket_calendar bc0
    ON g.cohort_bucket_id = bc0.bucket_id
LEFT JOIN bucket_calendar bc1
    ON g.cohort_bucket_id + g.bucket_offset = bc1.bucket_id
ORDER BY
    g.cohort_bucket_id,
    g.bucket_offset
""")

retention_long_df = con.execute("SELECT * FROM retention_long").df()
display(retention_long_df.head(30))

retention_long_df.to_csv(
    os.path.join(OUTPUT_DIR, "04_retention_long_exact.csv"),
    index=False,
    encoding="utf-8-sig"
)

# Pivot matrix
retention_matrix_df = retention_long_df.pivot(
    index="cohort_label",
    columns="offset_label",
    values="retention_rate"
)

# Giữ thứ tự cohort đúng theo thời gian
cohort_order = cohort_sizes_df.sort_values("cohort_bucket_id")["cohort_label"].tolist()
offset_order = (
    retention_long_df[["bucket_offset", "offset_label"]]
    .drop_duplicates()
    .sort_values("bucket_offset")["offset_label"]
    .tolist()
)

retention_matrix_df = retention_matrix_df.reindex(index=cohort_order, columns=offset_order)

retention_matrix_df.to_csv(
    os.path.join(OUTPUT_DIR, "05_retention_matrix_exact.csv"),
    encoding="utf-8-sig"
)

display(retention_matrix_df)

# ============================================================
# 8. SURVIVAL / RETURN-AFTER RETENTION
# ============================================================
# exact retention +k = có active đúng ở bucket +k
# survival +k = user có quay lại ít nhất 1 lần ở bucket +k hoặc sau đó
# Với BĐS, survival thường hữu ích hơn vì user không nhất thiết active mỗi nửa tháng.

print("\n[5/8] Building survival / return-after table...")

con.execute("""
CREATE OR REPLACE TABLE user_max_offset AS
SELECT
    c.user_id,
    c.cohort_bucket_id,
    MAX(uba.bucket_id - c.cohort_bucket_id) AS max_observed_offset
FROM user_cohort c
JOIN user_bucket_activity uba
    ON c.user_id = uba.user_id
GROUP BY
    c.user_id,
    c.cohort_bucket_id
""")

con.execute("""
CREATE OR REPLACE TABLE max_offset_dist AS
SELECT
    cohort_bucket_id,
    max_observed_offset AS bucket_offset,
    COUNT(*) AS users_with_last_seen_here
FROM user_max_offset
GROUP BY
    cohort_bucket_id,
    max_observed_offset
""")

con.execute("""
CREATE OR REPLACE TABLE survival_long AS
WITH maxb AS (
    SELECT MAX(bucket_id) AS max_bucket_id
    FROM bucket_calendar
),
grid AS (
    SELECT
        cs.cohort_bucket_id,
        r.bucket_offset
    FROM cohort_sizes cs
    CROSS JOIN maxb
    CROSS JOIN LATERAL range(
        0,
        CAST(maxb.max_bucket_id - cs.cohort_bucket_id + 1 AS BIGINT)
    ) AS r(bucket_offset)
),
base AS (
    SELECT
        g.cohort_bucket_id,
        g.bucket_offset,
        COALESCE(d.users_with_last_seen_here, 0) AS users_with_last_seen_here
    FROM grid g
    LEFT JOIN max_offset_dist d
        ON g.cohort_bucket_id = d.cohort_bucket_id
        AND g.bucket_offset = d.bucket_offset
),
surv AS (
    SELECT
        cohort_bucket_id,
        bucket_offset,
        SUM(users_with_last_seen_here) OVER (
            PARTITION BY cohort_bucket_id
            ORDER BY bucket_offset DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS survival_users
    FROM base
)
SELECT
    s.cohort_bucket_id,
    bc.bucket_label AS cohort_label,
    s.bucket_offset,
    '+' || CAST(s.bucket_offset AS VARCHAR) AS offset_label,
    cs.cohort_users,
    s.survival_users,
    s.survival_users * 1.0 / NULLIF(cs.cohort_users, 0) AS survival_rate
FROM surv s
JOIN cohort_sizes cs
    ON s.cohort_bucket_id = cs.cohort_bucket_id
LEFT JOIN bucket_calendar bc
    ON s.cohort_bucket_id = bc.bucket_id
ORDER BY
    s.cohort_bucket_id,
    s.bucket_offset
""")

survival_long_df = con.execute("SELECT * FROM survival_long").df()
display(survival_long_df.head(30))

survival_long_df.to_csv(
    os.path.join(OUTPUT_DIR, "06_survival_return_after_long.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 9. WEIGHTED AVG RETENTION CURVES
# ============================================================

print("\n[6/8] Building average curves...")

avg_exact_df = con.execute("""
SELECT
    bucket_offset,
    '+' || CAST(bucket_offset AS VARCHAR) AS offset_label,
    SUM(active_users) AS active_users,
    SUM(cohort_users) AS eligible_cohort_users,
    SUM(active_users) * 1.0 / NULLIF(SUM(cohort_users), 0) AS weighted_retention_rate,
    AVG(retention_rate) AS unweighted_mean_retention_rate
FROM retention_long
GROUP BY bucket_offset
ORDER BY bucket_offset
""").df()

avg_survival_df = con.execute("""
SELECT
    bucket_offset,
    '+' || CAST(bucket_offset AS VARCHAR) AS offset_label,
    SUM(survival_users) AS survival_users,
    SUM(cohort_users) AS eligible_cohort_users,
    SUM(survival_users) * 1.0 / NULLIF(SUM(cohort_users), 0) AS weighted_survival_rate,
    AVG(survival_rate) AS unweighted_mean_survival_rate
FROM survival_long
GROUP BY bucket_offset
ORDER BY bucket_offset
""").df()

display(avg_exact_df)
display(avg_survival_df)

avg_exact_df.to_csv(
    os.path.join(OUTPUT_DIR, "07_avg_exact_retention_curve.csv"),
    index=False,
    encoding="utf-8-sig"
)

avg_survival_df.to_csv(
    os.path.join(OUTPUT_DIR, "08_avg_survival_return_after_curve.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 10. OPTIONAL: CITY / CATEGORY SWITCHING
# ============================================================

switch_avg_df = None
switch_long_df = None

if DO_SWITCH_ANALYSIS:
    print("\n[7/8] Building city/category switching analysis...")

    # Dominant city per user-bucket
    con.execute(f"""
    CREATE OR REPLACE TABLE user_bucket_city_pref AS
    WITH src AS (
        SELECT
            CAST(user_id AS VARCHAR) AS user_id,

            COALESCE(
                TRY_CAST(date AS DATE),
                CAST(event_ts AS DATE)
            ) AS event_date,

            CASE
                WHEN city_name IS NULL OR TRIM(CAST(city_name AS VARCHAR)) = ''
                THEN NULL
                ELSE TRIM(CAST(city_name AS VARCHAR))
            END AS city_name_clean

        FROM read_parquet('{EVENTS_GLOB}')
        WHERE user_id IS NOT NULL
            {login_filter_sql}
            {active_filter_sql}
    ),
    base AS (
        SELECT
            user_id,
            city_name_clean,

            CAST(
                EXTRACT(YEAR FROM event_date) * 24
                + (EXTRACT(MONTH FROM event_date) - 1) * 2
                + CASE
                    WHEN EXTRACT(DAY FROM event_date) <= 15 THEN 0
                    ELSE 1
                  END
                AS BIGINT
            ) AS bucket_id

        FROM src
        WHERE event_date IS NOT NULL
            AND city_name_clean IS NOT NULL
            {date_filter_sql}
    ),
    cnt AS (
        SELECT
            user_id,
            bucket_id,
            city_name_clean,
            COUNT(*) AS n_events
        FROM base
        GROUP BY user_id, bucket_id, city_name_clean
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY user_id, bucket_id
                ORDER BY n_events DESC, city_name_clean
            ) AS rn
        FROM cnt
    )
    SELECT
        user_id,
        bucket_id,
        city_name_clean AS city_mode,
        n_events AS city_mode_events
    FROM ranked
    WHERE rn = 1
    """)

    # Dominant category per user-bucket
    con.execute(f"""
    CREATE OR REPLACE TABLE user_bucket_category_pref AS
    WITH src AS (
        SELECT
            CAST(user_id AS VARCHAR) AS user_id,

            COALESCE(
                TRY_CAST(date AS DATE),
                CAST(event_ts AS DATE)
            ) AS event_date,

            TRY_CAST(category AS INTEGER) AS category_clean

        FROM read_parquet('{EVENTS_GLOB}')
        WHERE user_id IS NOT NULL
            {login_filter_sql}
            {active_filter_sql}
    ),
    base AS (
        SELECT
            user_id,
            category_clean,

            CAST(
                EXTRACT(YEAR FROM event_date) * 24
                + (EXTRACT(MONTH FROM event_date) - 1) * 2
                + CASE
                    WHEN EXTRACT(DAY FROM event_date) <= 15 THEN 0
                    ELSE 1
                  END
                AS BIGINT
            ) AS bucket_id

        FROM src
        WHERE event_date IS NOT NULL
            AND category_clean IS NOT NULL
            {date_filter_sql}
    ),
    cnt AS (
        SELECT
            user_id,
            bucket_id,
            category_clean,
            COUNT(*) AS n_events
        FROM base
        GROUP BY user_id, bucket_id, category_clean
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY user_id, bucket_id
                ORDER BY n_events DESC, category_clean
            ) AS rn
        FROM cnt
    )
    SELECT
        user_id,
        bucket_id,
        category_clean AS category_mode,
        n_events AS category_mode_events
    FROM ranked
    WHERE rn = 1
    """)

    con.execute("""
    CREATE OR REPLACE TABLE user_cohort_pref AS
    SELECT
        c.user_id,
        c.cohort_bucket_id,
        city.city_mode AS cohort_city_mode,
        cat.category_mode AS cohort_category_mode
    FROM user_cohort c
    LEFT JOIN user_bucket_city_pref city
        ON c.user_id = city.user_id
        AND c.cohort_bucket_id = city.bucket_id
    LEFT JOIN user_bucket_category_pref cat
        ON c.user_id = cat.user_id
        AND c.cohort_bucket_id = cat.bucket_id
    """)

    con.execute("""
    CREATE OR REPLACE TABLE switch_long AS
    SELECT
        c.cohort_bucket_id,
        bc.bucket_label AS cohort_label,

        uba.bucket_id - c.cohort_bucket_id AS bucket_offset,
        '+' || CAST(uba.bucket_id - c.cohort_bucket_id AS VARCHAR) AS offset_label,

        COUNT(*) AS active_user_buckets,

        SUM(
            CASE
                WHEN cp.cohort_city_mode IS NOT NULL
                     AND city.city_mode IS NOT NULL
                THEN 1 ELSE 0
            END
        ) AS city_comparable_users,

        SUM(
            CASE
                WHEN cp.cohort_city_mode IS NOT NULL
                     AND city.city_mode IS NOT NULL
                     AND city.city_mode <> cp.cohort_city_mode
                THEN 1 ELSE 0
            END
        ) AS city_switched_users,

        SUM(
            CASE
                WHEN cp.cohort_category_mode IS NOT NULL
                     AND cat.category_mode IS NOT NULL
                THEN 1 ELSE 0
            END
        ) AS category_comparable_users,

        SUM(
            CASE
                WHEN cp.cohort_category_mode IS NOT NULL
                     AND cat.category_mode IS NOT NULL
                     AND cat.category_mode <> cp.cohort_category_mode
                THEN 1 ELSE 0
            END
        ) AS category_switched_users

    FROM user_bucket_activity uba
    JOIN user_cohort c
        ON uba.user_id = c.user_id
    LEFT JOIN user_cohort_pref cp
        ON uba.user_id = cp.user_id
    LEFT JOIN user_bucket_city_pref city
        ON uba.user_id = city.user_id
        AND uba.bucket_id = city.bucket_id
    LEFT JOIN user_bucket_category_pref cat
        ON uba.user_id = cat.user_id
        AND uba.bucket_id = cat.bucket_id
    LEFT JOIN bucket_calendar bc
        ON c.cohort_bucket_id = bc.bucket_id
    WHERE uba.bucket_id >= c.cohort_bucket_id
    GROUP BY
        c.cohort_bucket_id,
        bc.bucket_label,
        uba.bucket_id - c.cohort_bucket_id
    ORDER BY
        c.cohort_bucket_id,
        bucket_offset
    """)

    switch_long_df = con.execute("""
    SELECT
        *,
        city_switched_users * 1.0 / NULLIF(city_comparable_users, 0) AS city_switch_rate,
        category_switched_users * 1.0 / NULLIF(category_comparable_users, 0) AS category_switch_rate
    FROM switch_long
    """).df()

    switch_avg_df = con.execute("""
    SELECT
        bucket_offset,
        '+' || CAST(bucket_offset AS VARCHAR) AS offset_label,

        SUM(city_switched_users) AS city_switched_users,
        SUM(city_comparable_users) AS city_comparable_users,
        SUM(city_switched_users) * 1.0 / NULLIF(SUM(city_comparable_users), 0) AS city_switch_rate,

        SUM(category_switched_users) AS category_switched_users,
        SUM(category_comparable_users) AS category_comparable_users,
        SUM(category_switched_users) * 1.0 / NULLIF(SUM(category_comparable_users), 0) AS category_switch_rate

    FROM switch_long
    GROUP BY bucket_offset
    ORDER BY bucket_offset
    """).df()

    display(switch_long_df.head(30))
    display(switch_avg_df)

    switch_long_df.to_csv(
        os.path.join(OUTPUT_DIR, "09_switch_city_category_long.csv"),
        index=False,
        encoding="utf-8-sig"
    )

    switch_avg_df.to_csv(
        os.path.join(OUTPUT_DIR, "10_switch_city_category_avg_curve.csv"),
        index=False,
        encoding="utf-8-sig"
    )

# ============================================================
# 11. VISUALIZATION
# ============================================================

print("\n[8/8] Plotting charts...")

def save_plotly(fig, name):
    html_path = os.path.join(OUTPUT_DIR, f"{name}.html")
    fig.write_html(html_path)
    print("[SAVE HTML]", html_path)

    # PNG optional, nếu Kaggle thiếu kaleido thì bỏ qua
    try:
        png_path = os.path.join(OUTPUT_DIR, f"{name}.png")
        fig.write_image(png_path, scale=2)
        print("[SAVE PNG ]", png_path)
    except Exception as e:
        print(f"[SKIP PNG] {name}: {str(e)[:120]}")

# ----------------------------
# 11.1 Retention heatmap
# ----------------------------

heatmap_df = retention_matrix_df.copy()

# Text chỉ hiển thị % nếu số cohort/offset không quá dày
show_text = (heatmap_df.shape[0] <= 30 and heatmap_df.shape[1] <= 35)

fig_heatmap = px.imshow(
    heatmap_df,
    aspect="auto",
    color_continuous_scale="Blues",
    zmin=0,
    zmax=1,
    text_auto=".1%" if show_text else False,
    title=f"Half-month User Retention Heatmap — LOGIN_MODE={LOGIN_MODE}"
)

fig_heatmap.update_layout(
    xaxis_title="Bucket offset from first seen cohort",
    yaxis_title="User cohort first seen bucket",
    height=max(500, 26 * len(heatmap_df.index)),
    width=max(900, 55 * len(heatmap_df.columns)),
)

fig_heatmap.show()
save_plotly(fig_heatmap, "01_retention_heatmap_exact")

# ----------------------------
# 11.2 Average exact retention curve
# ----------------------------

fig_avg_exact = px.line(
    avg_exact_df,
    x="offset_label",
    y="weighted_retention_rate",
    markers=True,
    title="Weighted Average Exact Retention by Half-month Offset",
    hover_data={
        "active_users": ":,",
        "eligible_cohort_users": ":,",
        "weighted_retention_rate": ":.2%",
        "unweighted_mean_retention_rate": ":.2%",
    }
)

fig_avg_exact.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Weighted exact retention rate",
    yaxis_tickformat=".0%",
    height=500,
    width=1000
)

fig_avg_exact.show()
save_plotly(fig_avg_exact, "02_avg_exact_retention_curve")

# ----------------------------
# 11.3 Survival / return-after curve
# ----------------------------

fig_avg_survival = px.line(
    avg_survival_df,
    x="offset_label",
    y="weighted_survival_rate",
    markers=True,
    title="Weighted Survival / Return-after Rate by Half-month Offset",
    hover_data={
        "survival_users": ":,",
        "eligible_cohort_users": ":,",
        "weighted_survival_rate": ":.2%",
        "unweighted_mean_survival_rate": ":.2%",
    }
)

fig_avg_survival.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Return-after / survival rate",
    yaxis_tickformat=".0%",
    height=500,
    width=1000
)

fig_avg_survival.show()
save_plotly(fig_avg_survival, "03_avg_survival_return_after_curve")

# ----------------------------
# 11.4 Cohort size
# ----------------------------

fig_cohort = px.bar(
    cohort_sizes_df,
    x="cohort_label",
    y="cohort_users",
    title="New User Cohort Size by Half-month Bucket",
    hover_data={
        "cohort_start": True,
        "cohort_end": True,
        "cohort_users": ":,",
    }
)

fig_cohort.update_layout(
    xaxis_title="First seen bucket",
    yaxis_title="New users",
    height=500,
    width=1000
)

fig_cohort.show()
save_plotly(fig_cohort, "04_cohort_size_by_bucket")

# ----------------------------
# 11.5 Active users by bucket
# ----------------------------

active_by_bucket_df = con.execute("""
SELECT
    bc.bucket_label,
    bc.bucket_start,
    bc.bucket_end,
    COUNT(DISTINCT uba.user_id) AS active_users,
    SUM(uba.events) AS events,
    SUM(uba.positive_events) AS positive_events,
    SUM(uba.strict_contact_events) AS strict_contact_events
FROM user_bucket_activity uba
LEFT JOIN bucket_calendar bc
    ON uba.bucket_id = bc.bucket_id
GROUP BY
    bc.bucket_label,
    bc.bucket_start,
    bc.bucket_end
ORDER BY
    bc.bucket_start
""").df()

active_by_bucket_df.to_csv(
    os.path.join(OUTPUT_DIR, "11_active_users_by_bucket.csv"),
    index=False,
    encoding="utf-8-sig"
)

fig_active = px.line(
    active_by_bucket_df,
    x="bucket_label",
    y="active_users",
    markers=True,
    title="Active Users by Half-month Bucket",
    hover_data={
        "bucket_start": True,
        "bucket_end": True,
        "active_users": ":,",
        "events": ":,",
        "positive_events": ":,",
        "strict_contact_events": ":,",
    }
)

fig_active.update_layout(
    xaxis_title="Half-month bucket",
    yaxis_title="Active users",
    height=500,
    width=1000
)

fig_active.show()
save_plotly(fig_active, "05_active_users_by_bucket")

# ----------------------------
# 11.6 Switching curve
# ----------------------------

if DO_SWITCH_ANALYSIS and switch_avg_df is not None:
    switch_plot_df = switch_avg_df.melt(
        id_vars=["bucket_offset", "offset_label"],
        value_vars=["city_switch_rate", "category_switch_rate"],
        var_name="switch_type",
        value_name="switch_rate"
    )

    switch_plot_df["switch_type"] = switch_plot_df["switch_type"].map({
        "city_switch_rate": "Dominant city changed",
        "category_switch_rate": "Dominant category changed"
    })

    fig_switch = px.line(
        switch_plot_df,
        x="offset_label",
        y="switch_rate",
        color="switch_type",
        markers=True,
        title="Among Retained Users: City / Category Switching vs First-seen Bucket",
        hover_data={
            "bucket_offset": True,
            "switch_rate": ":.2%",
        }
    )

    fig_switch.update_layout(
        xaxis_title="Bucket offset",
        yaxis_title="Switch rate among comparable active users",
        yaxis_tickformat=".0%",
        height=500,
        width=1000
    )

    fig_switch.show()
    save_plotly(fig_switch, "06_city_category_switching_curve")

# ============================================================
# 12. PRINT INTERPRETATION GUIDE
# ============================================================

print("\nDONE.")
print("Output folder:", OUTPUT_DIR)

print("""
CÁCH ĐỌC NHANH:

1) 01_retention_heatmap_exact.html
   - Mỗi row = nhóm user xuất hiện lần đầu ở một bucket nửa tháng.
   - +0 = chính bucket đầu tiên, luôn gần 100%.
   - +1 = sau nửa tháng kế tiếp còn active bao nhiêu %.
   - +2 = sau 1 tháng còn active bao nhiêu %.
   - +4 = sau 2 tháng còn active bao nhiêu %.

2) 02_avg_exact_retention_curve.html
   - Retention đúng tại từng offset.
   - Nếu +1 rớt mạnh: user vào xem một lần rồi biến mất nhanh.
   - Nếu +2/+3 còn cao: user có chu kỳ tìm BĐS dài hơn.

3) 03_avg_survival_return_after_curve.html
   - User có quay lại ít nhất một lần từ offset đó trở đi không.
   - Metric này hợp với BĐS hơn exact retention, vì người tìm nhà không nhất thiết tuần nào/nửa tháng nào cũng vào.

4) 04_cohort_size_by_bucket.html
   - Bucket nào kéo được nhiều user mới.
   - Nếu cohort lớn nhưng retention thấp: acquisition tốt nhưng giữ chân yếu.

5) 05_active_users_by_bucket.html
   - Tổng active users theo timeline nửa tháng.
   - Dùng để nhìn seasonality / trend tăng giảm tổng thể.

6) 06_city_category_switching_curve.html
   - Trong số user còn quay lại, bao nhiêu % đổi city/category chính so với bucket đầu tiên.
   - Nếu city_switch_rate tăng theo offset: user ban đầu search một khu, sau đó mở rộng/đổi địa bàn.
   - Nếu category_switch_rate tăng: user đang đổi nhu cầu, ví dụ từ thuê phòng sang chung cư/nhà ở.
""")

print("Important CSV files:")
for f in sorted(os.listdir(OUTPUT_DIR)):
    if f.endswith(".csv"):
        print("-", f)

con.close()

EVENTS_PATH: /kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2/fact_user_events
EVENTS_GLOB: /kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2/fact_user_events/*.parquet
OUTPUT_DIR : /kaggle/working/user_retention_half_month

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date  total_rows   login_rows  non_login_rows
0 2025-11-09 2026-04-09   161731336  102098089.0      59633247.0

[1/8] Building user_bucket_activity...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,user_bucket_rows,users,min_bucket_id,max_bucket_id,total_events,total_positive_events,total_strict_contact_events
0,2199205,994892,48620,48630,102098089.0,52197966.0,4126786.0

[2/8] Building bucket calendar...

    bucket_id bucket_start bucket_end bucket_label  half_idx
0       48620   2025-11-01 2025-11-15   2025-11-H1         0
1       48621   2025-11-16 2025-11-30   2025-11-H2         1
2       48622   2025-12-01 2025-12-15   2025-12-H1         0
3       48623   2025-12-16 2025-12-31   2025-12-H2         1
4       48624   2026-01-01 2026-01-15   2026-01-H1         0
5       48625   2026-01-16 2026-01-31   2026-01-H2         1
6       48626   2026-02-01 2026-02-15   2026-02-H1         0
7       48627   2026-02-16 2026-02-28   2026-02-H2         1
8       48628   2026-03-01 2026-03-15   2026-03-H1         0
9       48629   2026-03-16 2026-03-31   2026-03-H2         1
10      48630   2026-04-01 2026-04-15   2026-04-H1         0

[3/8] Building user cohorts...

    cohort_bucket_id cohort_label cohort_start cohort_end  cohort_users
0              48620   2025-11-H1   2025-11-01 2025-11-15        148644
1              48621   2025-11-H2   2025-11-16 2025-11-30        159470
2              48622   2025-12-H1   2025-12-01 2025-12-15        107478
3              48623   2025-12-H2   2025-12-16 2025-12-31         86390
4              48624   2026-01-H1   2026-01-01 2026-01-15         76381
5              48625   2026-01-H2   2026-01-16 2026-01-31         66209
6              48626   2026-02-H1   2026-02-01 2026-02-15         45275
7              48627   2026-02-H2   2026-02-16 2026-02-28         67461
8              48628   2026-03-H1   2026-03-01 2026-03-15        100126
9              48629   2026-03-H2   2026-03-16 2026-03-31         90680
10             48630   2026-04-H1   2026-04-01 2026-04-15         46778

[4/8] Building exact retention table...

,cohort_bucket_id,cohort_label,cohort_start,cohort_end,bucket_offset,offset_label,active_bucket_id,active_bucket_label,active_bucket_start,active_bucket_end,cohort_users,active_users,events,positive_events,strict_contact_events,retention_rate,mean_events_per_active_user,mean_positive_events_per_active_user,mean_strict_contact_events_per_active_user
0,48620,2025-11-H1,2025-11-01,2025-11-15,0,+0,48620,2025-11-H1,2025-11-01,2025-11-15,148644,148644,6019324.0,3227589.0,243619.0,1.000000,40.494901,21.713550,1.638943
1,48620,2025-11-H1,2025-11-01,2025-11-15,1,+1,48621,2025-11-H2,2025-11-16,2025-11-30,148644,79031,6672790.0,3707673.0,245789.0,0.531680,84.432564,46.914160,3.110033
2,48620,2025-11-H1,2025-11-01,2025-11-15,2,+2,48622,2025-12-H1,2025-12-01,2025-12-15,148644,61434,4571411.0,2375659.0,192000.0,0.413296,74.411743,38.670101,3.125305
3,48620,2025-11-H1,2025-11-01,2025-11-15,3,+3,48623,2025-12-H2,2025-12-16,2025-12-31,148644,52761,3463297.0,1592187.0,174394.0,0.354949,65.641231,30.177347,3.305358
4,48620,2025-11-H1,2025-11-01,2025-11-15,4,+4,48624,2026-01-H1,2026-01-01,2026-01-15,148644,46705,2753109.0,1237414.0,147334.0,0.314207,58.946772,26.494251,3.154566
5,48620,2025-11-H1,2025-11-01,2025-11-15,5,+5,48625,2026-01-H2,2026-01-16,2026-01-31,148644,42131,2653001.0,1320412.0,131074.0,0.283436,62.970283,31.340628,3.111106
6,48620,2025-11-H1,2025-11-01,2025-11-15,6,+6,48626,2026-02-H1,2026-02-01,2026-02-15,148644,32168,1487445.0,729567.0,61222.0,0.216410,46.239897,22.679899,1.903196
7,48620,2025-11-H1,2025-11-01,2025-11-15,7,+7,48627,2026-02-H2,2026-02-16,2026-02-28,148644,34312,1726044.0,841003.0,70042.0,0.230833,50.304383,24.510463,2.041327
8,48620,2025-11-H1,2025-11-01,2025-11-15,8,+8,48628,2026-03-H1,2026-03-01,2026-03-15,148644,41347,3414313.0,1858315.0,157300.0,0.278161,82.577043,44.944373,3.804387
9,48620,2025-11-H1,2025-11-01,2025-11-15,9,+9,48629,2026-03-H2,2026-03-16,2026-03-31,148644,39995,3318137.0,1721723.0,167727.0,0.269066,82.963795,43.048456,4.193699
10,48620,2025-11-H1,2025-11-01,2025-11-15,10,+10,48630,2026-04-H1,2026-04-01,2026-04-15,148644,29769,1746451.0,912534.0,90085.0,0.200270,58.666767,30.653835,3.026135
11,48621,2025-11-H2,2025-11-16,2025-11-30,0,+0,48621,2025-11-H2,2025-11-16,2025-11-30,159470,159470,5987782.0,3518489.0,225195.0,1.000000,37.548015,22.063642,1.412146
12,48621,2025-11-H2,2025-11-16,2025-11-30,1,+1,48622,2025-12-H1,2025-12-01,2025-12-15,159470,49829,2563602.0,1372072.0,93905.0,0.312466,51.447992,27.535612,1.884545
13,48621,2025-11-H2,2025-11-16,2025-11-30,2,+2,48623,2025-12-H2,2025-12-16,2025-12-31,159470,37045,1565623.0,736040.0,61961.0,0.232301,42.262735,19.868808,1.672587
14,48621,2025-11-H2,2025-11-16,2025-11-30,3,+3,48624,2026-01-H1,2026-01-01,2026-01-15,159470,31202,1190352.0,544587.0,47589.0,0.195661,38.149862,17.453593,1.525191
15,48621,2025-11-H2,2025-11-16,2025-11-30,4,+4,48625,2026-01-H2,2026-01-16,2026-01-31,159470,27337,1116303.0,554280.0,40512.0,0.171424,40.834876,20.275817,1.481948
16,48621,2025-11-H2,2025-11-16,2025-11-30,5,+5,48626,2026-02-H1,2026-02-01,2026-02-15,159470,19674,672347.0,327662.0,23017.0,0.123371,34.174393,16.654569,1.169920
17,48621,2025-11-H2,2025-11-16,2025-11-30,6,+6,48627,2026-02-H2,2026-02-16,2026-02-28,159470,21850,828223.0,394696.0,24419.0,0.137016,37.904943,18.063890,1.117574
18,48621,2025-11-H2,2025-11-16,2025-11-30,7,+7,48628,2026-03-H1,2026-03-01,2026-03-15,159470,27333,1413538.0,742662.0,46169.0,0.171399,51.715436,27.170892,1.689130
19,48621,2025-11-H2,2025-11-16,2025-11-30,8,+8,48629,2026-03-H2,2026-03-16,2026-03-31,159470,26216,1296621.0,638035.0,46200.0,0.164395,49.459147,24.337618,1.762283
20,48621,2025-11-H2,2025-11-16,2025-11-30,9,+9,48630,2026-04-H1,2026-04-01,2026-04-15,159470,17169,666650.0,334306.0,24888.0,0.107663,38.828703,19.471489,1.449589
21,48622,2025-12-H1,2025-12-01,2025-12-15,0,+0,48622,2025-12-H1,2025-12-01,2025-12-15,107478,107478,3787742.0,2114628.0,159508.0,1.000000,35.242022,19.674985,1.484099
22,48622,2025-12-H1,2025-12-01,2025-12-15,1,+1,48623,2025-12-H2,2025-12-16,2025-12-31,107478,29669,1394082.0,651391.0,55142.0,0.276047,46.987832,21.955273,1.858573
23,48622,2025-12-H1,2025-12-01,2025-12-15,2,+2,48624,2026-01-H1,2026-01-01,2026-01-15,107478,20975,846418.0,382588.0,30891.0,0.195156,40.353659,18.240191,1.472753
24,48622,2025-12-H1,2025-12-01,2025-12-15,3,+3,48625,2026-01-H2,2026-01-16,2026-01-31,107478,17355,715826.0,343983.0,24971.0,0.161475,41.246096,19.820398,1.438836
25,48622,2025-12-H1,2025-12-01,2025-12-15,4,+4,48626,2026-02-H1,2026-02-01,2026-02-15,107478,12014,416330.0,198805.0,13858.0,0.111781,34.653737,16.547778,1.153488
26,48622,2025-12-H1,2025-12-01,2025-12-15,5,+5,48627,2026-02-H2,2026-02-16,2026-02-28,107478,13681,544335.0,257438.0,15875.0,0.127291,39.787662,18.817192,1.160368
27,48622,2025-12-H1,2025-12-01,2025-12-15,6,+6,48628,2026-03-H1,2026-03-01,2026-03-15,107478,16835,881271.0,452879.0,29524.0,0.156637,52.347550,26.901040,1.753727
28,48622,2025-12-H1,2025-12-01,2025-12-15,7,+7,48629,2026-03-H2,2026-03-16,2026-03-31,107478,15589,753149.0,364016.0,26994.0,0.145044,48.312849,23.350824,1.731606
29,48622,2025-12-H1,2025-12-01,2025-12-15,8,+8,48630,2026-04-H1,2026-04-01,2026-04-15,107478,10087,389430.0,192906.0,14150.0,0.093852,38.607118,19.124219,1.402796

offset_label,+0,+1,+2,+3,+4,+5,+6,+7,+8,+9,+10
cohort_label,,,,,,,,,,,
2025-11-H1,1.0,0.531680,0.413296,0.354949,0.314207,0.283436,0.216410,0.230833,0.278161,0.269066,0.20027
2025-11-H2,1.0,0.312466,0.232301,0.195661,0.171424,0.123371,0.137016,0.171399,0.164395,0.107663,NaN
2025-12-H1,1.0,0.276047,0.195156,0.161475,0.111781,0.127291,0.156637,0.145044,0.093852,NaN,NaN
2025-12-H2,1.0,0.260447,0.180877,0.120940,0.130339,0.157657,0.146047,0.088401,NaN,NaN,NaN
2026-01-H1,1.0,0.245624,0.138699,0.140755,0.167110,0.148375,0.089368,NaN,NaN,NaN,NaN
2026-01-H2,1.0,0.201589,0.169025,0.184295,0.159102,0.097283,NaN,NaN,NaN,NaN,NaN
2026-02-H1,1.0,0.249917,0.221955,0.176698,0.104716,NaN,NaN,NaN,NaN,NaN,NaN
2026-02-H2,1.0,0.299566,0.191740,0.107306,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-H1,1.0,0.269550,0.126680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-03-H2,1.0,0.200562,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026-04-H1,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

[5/8] Building survival / return-after table...

,cohort_bucket_id,cohort_label,bucket_offset,offset_label,cohort_users,survival_users,survival_rate
0,48620,2025-11-H1,0,+0,148644,148644.0,1.000000
1,48620,2025-11-H1,1,+1,148644,111825.0,0.752301
2,48620,2025-11-H1,2,+2,148644,97992.0,0.659240
3,48620,2025-11-H1,3,+3,148644,89112.0,0.599499
4,48620,2025-11-H1,4,+4,148644,81395.0,0.547583
5,48620,2025-11-H1,5,+5,148644,74604.0,0.501897
6,48620,2025-11-H1,6,+6,148644,67979.0,0.457328
7,48620,2025-11-H1,7,+7,148644,63272.0,0.425661
8,48620,2025-11-H1,8,+8,148644,57333.0,0.385707
9,48620,2025-11-H1,9,+9,148644,46678.0,0.314025
10,48620,2025-11-H1,10,+10,148644,29769.0,0.200270
11,48621,2025-11-H2,0,+0,159470,159470.0,1.000000
12,48621,2025-11-H2,1,+1,159470,91740.0,0.575281
13,48621,2025-11-H2,2,+2,159470,78245.0,0.490657
14,48621,2025-11-H2,3,+3,159470,69338.0,0.434803
15,48621,2025-11-H2,4,+4,159470,61674.0,0.386744
16,48621,2025-11-H2,5,+5,159470,54578.0,0.342246
17,48621,2025-11-H2,6,+6,159470,49729.0,0.311839
18,48621,2025-11-H2,7,+7,159470,43277.0,0.271380
19,48621,2025-11-H2,8,+8,159470,32448.0,0.203474
20,48621,2025-11-H2,9,+9,159470,17169.0,0.107663
21,48622,2025-12-H1,0,+0,107478,107478.0,1.000000
22,48622,2025-12-H1,1,+1,107478,56021.0,0.521232
23,48622,2025-12-H1,2,+2,107478,46420.0,0.431902
24,48622,2025-12-H1,3,+3,107478,40351.0,0.375435
25,48622,2025-12-H1,4,+4,107478,35132.0,0.326876
26,48622,2025-12-H1,5,+5,107478,31775.0,0.295642
27,48622,2025-12-H1,6,+6,107478,27353.0,0.254499
28,48622,2025-12-H1,7,+7,107478,19848.0,0.184670
29,48622,2025-12-H1,8,+8,107478,10087.0,0.093852

[6/8] Building average curves...

,bucket_offset,offset_label,active_users,eligible_cohort_users,weighted_retention_rate,unweighted_mean_retention_rate
0,0,+0,994892.0,994892.0,1.000000,1.000000
1,1,+1,289837.0,948114.0,0.305698,0.284745
2,2,+2,192533.0,857434.0,0.224546,0.207748
3,3,+3,149958.0,757308.0,0.198015,0.180260
4,4,+4,125355.0,689847.0,0.181714,0.165526
5,5,+5,106880.0,644572.0,0.165815,0.156235
6,6,+6,90296.0,578363.0,0.156123,0.149096
7,7,+7,84871.0,501982.0,0.169072,0.158919
8,8,+8,77650.0,415592.0,0.186842,0.178803
9,9,+9,57164.0,308114.0,0.185529,0.188364
10,10,+10,29769.0,148644.0,0.200270,0.200270

,bucket_offset,offset_label,survival_users,eligible_cohort_users,weighted_survival_rate,unweighted_mean_survival_rate
0,0,+0,994892.0,994892.0,1.000000,1.000000
1,1,+1,460119.0,948114.0,0.485299,0.455387
2,2,+2,350740.0,857434.0,0.409058,0.375046
3,3,+3,287926.0,757308.0,0.380197,0.334017
4,4,+4,242271.0,689847.0,0.351195,0.304245
5,5,+5,203557.0,644572.0,0.315802,0.279511
6,6,+6,167673.0,578363.0,0.289910,0.259153
7,7,+7,134034.0,501982.0,0.267010,0.242528
8,8,+8,99868.0,415592.0,0.240303,0.227678
9,9,+9,63847.0,308114.0,0.207219,0.210844
10,10,+10,29769.0,148644.0,0.200270,0.200270

[7/8] Building city/category switching analysis...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,cohort_bucket_id,cohort_label,bucket_offset,offset_label,active_user_buckets,city_comparable_users,city_switched_users,category_comparable_users,category_switched_users,city_switch_rate,category_switch_rate
0,48620,2025-11-H1,0,+0,148644,148623.0,0.0,148644.0,0.0,0.000000,0.000000
1,48620,2025-11-H1,1,+1,79031,79023.0,10044.0,79031.0,22849.0,0.127102,0.289114
2,48620,2025-11-H1,2,+2,61434,61432.0,9050.0,61434.0,20152.0,0.147317,0.328027
3,48620,2025-11-H1,3,+3,52761,52759.0,8548.0,52761.0,18922.0,0.162020,0.358636
4,48620,2025-11-H1,4,+4,46705,46702.0,7870.0,46705.0,17103.0,0.168515,0.366192
5,48620,2025-11-H1,5,+5,42131,42126.0,7179.0,42131.0,15849.0,0.170417,0.376184
6,48620,2025-11-H1,6,+6,32168,32163.0,5775.0,32168.0,12403.0,0.179554,0.385570
7,48620,2025-11-H1,7,+7,34312,34310.0,6149.0,34312.0,13402.0,0.179219,0.390592
8,48620,2025-11-H1,8,+8,41347,41344.0,7002.0,41347.0,16113.0,0.169360,0.389702
9,48620,2025-11-H1,9,+9,39995,39992.0,6997.0,39995.0,15846.0,0.174960,0.396200
10,48620,2025-11-H1,10,+10,29769,29766.0,5035.0,29769.0,11625.0,0.169153,0.390507
11,48621,2025-11-H2,0,+0,159470,159453.0,0.0,159470.0,0.0,0.000000,0.000000
12,48621,2025-11-H2,1,+1,49829,49826.0,7875.0,49829.0,16345.0,0.158050,0.328022
13,48621,2025-11-H2,2,+2,37045,37036.0,7102.0,37045.0,14585.0,0.191759,0.393710
14,48621,2025-11-H2,3,+3,31202,31197.0,6493.0,31202.0,13070.0,0.208129,0.418883
15,48621,2025-11-H2,4,+4,27337,27335.0,5921.0,27337.0,11884.0,0.216609,0.434722
16,48621,2025-11-H2,5,+5,19674,19673.0,4603.0,19674.0,8840.0,0.233975,0.449324
17,48621,2025-11-H2,6,+6,21850,21848.0,4848.0,21850.0,9891.0,0.221897,0.452677
18,48621,2025-11-H2,7,+7,27333,27331.0,5828.0,27333.0,12416.0,0.213238,0.454249
19,48621,2025-11-H2,8,+8,26216,26215.0,5828.0,26216.0,12291.0,0.222315,0.468836
20,48621,2025-11-H2,9,+9,17169,17167.0,3755.0,17169.0,7989.0,0.218734,0.465315
21,48622,2025-12-H1,0,+0,107478,107460.0,0.0,107478.0,0.0,0.000000,0.000000
22,48622,2025-12-H1,1,+1,29669,29663.0,4840.0,29669.0,9626.0,0.163166,0.324446
23,48622,2025-12-H1,2,+2,20975,20973.0,4121.0,20975.0,8193.0,0.196491,0.390608
24,48622,2025-12-H1,3,+3,17355,17352.0,3668.0,17355.0,7239.0,0.211388,0.417113
25,48622,2025-12-H1,4,+4,12014,12012.0,2696.0,12014.0,5118.0,0.224442,0.426003
26,48622,2025-12-H1,5,+5,13681,13679.0,3077.0,13681.0,6030.0,0.224943,0.440757
27,48622,2025-12-H1,6,+6,16835,16832.0,3552.0,16835.0,7487.0,0.211027,0.444728
28,48622,2025-12-H1,7,+7,15589,15584.0,3373.0,15589.0,7095.0,0.216440,0.455129
29,48622,2025-12-H1,8,+8,10087,10084.0,2092.0,10087.0,4674.0,0.207457,0.463369

,bucket_offset,offset_label,city_switched_users,city_comparable_users,city_switch_rate,category_switched_users,category_comparable_users,category_switch_rate
0,0,+0,0.0,994755.0,0.000000,0.0,994892.0,0.000000
1,1,+1,43268.0,289802.0,0.149302,89940.0,289837.0,0.310312
2,2,+2,34357.0,192514.0,0.178465,70592.0,192533.0,0.366649
3,3,+3,28998.0,149942.0,0.193395,59174.0,149958.0,0.394604
4,4,+4,24958.0,125343.0,0.199118,50893.0,125355.0,0.405991
5,5,+5,21559.0,106870.0,0.201731,44613.0,106880.0,0.417412
6,6,+6,18418.0,90284.0,0.204001,38515.0,90296.0,0.426542
7,7,+7,16976.0,84862.0,0.200042,36383.0,84871.0,0.428686
8,8,+8,14922.0,77643.0,0.192187,33078.0,77650.0,0.425988
9,9,+9,10752.0,57159.0,0.188107,23835.0,57164.0,0.416958
10,10,+10,5035.0,29766.0,0.169153,11625.0,29769.0,0.390507

[8/8] Plotting charts...

[SAVE HTML] /kaggle/working/user_retention_half_month/01_retention_heatmap_exact.html
[SKIP PNG] 01_retention_heatmap_exact:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

[SAVE HTML] /kaggle/working/user_retention_half_month/02_avg_exact_retention_curve.html
[SKIP PNG] 02_avg_exact_retention_curve:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

[SAVE HTML] /kaggle/working/user_retention_half_month/03_avg_survival_return_after_curve.html
[SKIP PNG] 03_avg_survival_return_after_curve:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

[SAVE HTML] /kaggle/working/user_retention_half_month/04_cohort_size_by_bucket.html
[SKIP PNG] 04_cohort_size_by_bucket:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

[SAVE HTML] /kaggle/working/user_retention_half_month/05_active_users_by_bucket.html
[SKIP PNG] 05_active_users_by_bucket:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

[SAVE HTML] /kaggle/working/user_retention_half_month/06_city_category_switching_curve.html
[SKIP PNG] 06_city_category_switching_curve:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip insta

DONE.
Output folder: /kaggle/working/user_retention_half_month

CÁCH ĐỌC NHANH:

1) 01_retention_heatmap_exact.html
   - Mỗi row = nhóm user xuất hiện lần đầu ở một bucket nửa tháng.
   - +0 = chính bucket đầu tiên, luôn gần 100%.
   - +1 = sau nửa tháng kế tiếp còn active bao nhiêu %.
   - +2 = sau 1 tháng còn active bao nhiêu %.
   - +4 = sau 2 tháng còn active bao nhiêu %.

2) 02_avg_exact_retention_curve.html
   - Retention đúng tại từng offset.
   - Nếu +1 rớt mạnh: user vào xem một lần rồi biến mất nhanh.
   - Nếu +2/+3 còn cao: user có chu kỳ tìm BĐS dài hơn.

3) 03_avg_survival_return_after_curve.html
   - User có quay lại ít nhất một lần từ offset đó trở đi không.
   - Metric này hợp với BĐS hơn exact retention, vì người tìm nhà không nhất thiết tuần nào/nửa tháng nào cũng vào.

4) 04_cohort_size_by_bucket.html
   - Bucket nào kéo được nhiều user mới.
   - Nếu cohort lớn nhưng retention thấp: acquisition tốt nhưng giữ chân yếu.

5) 05_active_users_by_bucket.html
   - Tổng active users theo timeline nửa tháng.
   - Dùng để nhìn seasonality / trend tăng giảm tổng thể.

6) 06_city_category_switching_curve.html
   - Trong số user còn quay lại, bao nhiêu % đổi city/category chính so với bucket đầu tiên.
   - Nếu city_switch_rate tăng theo offset: user ban đầu search một khu, sau đó mở rộng/đổi địa bàn.
   - Nếu category_switch_rate tăng: user đang đổi nhu cầu, ví dụ từ thuê phòng sang chung cư/nhà ở.

Important CSV files:
- 00_data_range_check.csv
- 01_user_bucket_activity_summary.csv
- 02_bucket_calendar.csv
- 03_cohort_sizes.csv
- 04_retention_long_exact.csv
- 05_retention_matrix_exact.csv
- 06_survival_return_after_long.csv
- 07_avg_exact_retention_curve.csv
- 08_avg_survival_return_after_curve.csv
- 09_switch_city_category_long.csv
- 10_switch_city_category_avg_curve.csv
- 11_active_users_by_bucket.csv

# **check thêm thuê với mua**, check coi sell hay let & check có coi nhiều city hông (nhiều city -> cò) (đã có chuyển city & category)

**user & cò**

In [1]:
# ============================================================
# DATATHON 2026 — LOW-DISK RETENTION DEEP DIVE
# sell vs let + multi-city behavior
# ============================================================
# Fix lỗi:
# IOException: No space left on device / duckdb_tmp
#
# Idea:
# - Không tạo bảng combo lớn user x bucket x city x category x ad_type x seller_type
# - Scan từng parquet file
# - Aggregate nhỏ theo từng chiều riêng:
#     user_bucket overall
#     user_bucket_city
#     user_bucket_category
#     user_bucket_ad_type
# - Merge lại sau
#
# Output:
# - Switch city/category/sell-let
# - Retention by first-seen let/sell
# - City switch vs multi-city diagnosis
# ============================================================

import os
import sys
import glob
import shutil
import subprocess
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
from IPython.display import display

# ============================================================
# 0. CONFIG
# ============================================================

OUTPUT_DIR = "/kaggle/working/retention_lowdisk_sell_let_multicity"

# Xóa output cũ để dọn duckdb_tmp đã làm đầy disk
if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)

os.makedirs(OUTPUT_DIR, exist_ok=True)

PARTS_DIR = os.path.join(OUTPUT_DIR, "parts")
os.makedirs(PARTS_DIR, exist_ok=True)

# Dataset của bạn đang tách:
# Datathon2026_1: dim_listing
# Datathon2026_2: fact_user_events
SEARCH_ROOTS = [
    "/kaggle/input",
    "/kaggle/input/Datathon2026_1",
    "/kaggle/input/Datathon2026_2",
    "/kaggle/input/datathon2026-1",
    "/kaggle/input/datathon2026-2",
    "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1",
    "/kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2",
    "/kaggle/input/datasets/luquang231/datathonvinu",
]

EVENTS_DIR_NAMES = ["fact_user_events"]
DIM_DIR_NAMES = ["dim_listing_raw_clean", "dim_listing_clean", "dim_listing"]

LOGIN_MODE = "login"       # "login" | "non-login" | "all"

START_DATE = None
END_DATE = None

# Nếu muốn train window:
# START_DATE = "2025-11-09"
# END_DATE = "2026-04-09"

ACTIVE_EVENT_TYPES = None
# ACTIVE_EVENT_TYPES = ["pageview"]
# ACTIVE_EVENT_TYPES = ["view_phone", "contact_chat", "contact_zalo", "contact_sms"]

POSITIVE_EVENT_TYPES = [
    "view_phone", "contact_chat", "other_interaction", "contact_zalo", "contact_sms"
]

STRICT_CONTACT_EVENT_TYPES = [
    "view_phone", "contact_chat", "contact_zalo", "contact_sms"
]

DUCKDB_MEMORY_LIMIT = "4GB"
DUCKDB_THREADS = 1

# Giới hạn temp thấp để nó không ăn hết disk
DUCKDB_MAX_TEMP_DIR_SIZE = "6GB"

# Nếu chỉ test nhanh, set số nhỏ, ví dụ 20.
# Chạy full thì để None.
MAX_EVENT_FILES = None

# ============================================================
# 1. SETUP
# ============================================================

try:
    import duckdb
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "duckdb"])
    import duckdb

try:
    import plotly.express as px
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "plotly"])
    import plotly.express as px


def find_existing_subdir_anywhere(target_names, search_roots):
    for root in search_roots:
        if not os.path.exists(root):
            continue
        for name in target_names:
            p = os.path.join(root, name)
            if os.path.exists(p):
                return p

    for root in search_roots:
        if not os.path.exists(root):
            continue
        for base, dirs, files in os.walk(root):
            for name in target_names:
                if name in dirs:
                    return os.path.join(base, name)

    raise FileNotFoundError(f"Không tìm thấy folder nào trong list: {target_names}")


def sql_str_list(values):
    return ", ".join(["'" + str(v).replace("'", "''").lower() + "'" for v in values])


EVENTS_PATH = find_existing_subdir_anywhere(EVENTS_DIR_NAMES, SEARCH_ROOTS)
DIM_PATH = find_existing_subdir_anywhere(DIM_DIR_NAMES, SEARCH_ROOTS)

EVENT_FILES = sorted(glob.glob(os.path.join(EVENTS_PATH, "*.parquet")))
DIM_GLOB = os.path.join(DIM_PATH, "*.parquet").replace("\\", "/")

if MAX_EVENT_FILES is not None:
    EVENT_FILES = EVENT_FILES[:MAX_EVENT_FILES]

print("EVENTS_PATH:", EVENTS_PATH)
print("DIM_PATH   :", DIM_PATH)
print("EVENT_FILES:", len(EVENT_FILES))
print("OUTPUT_DIR :", OUTPUT_DIR)

duckdb_path = os.path.join(OUTPUT_DIR, "retention_lowdisk.duckdb")
tmp_dir = os.path.join(OUTPUT_DIR, "duckdb_tmp")
os.makedirs(tmp_dir, exist_ok=True)

con = duckdb.connect(duckdb_path)
con.execute(f"PRAGMA threads={DUCKDB_THREADS}")
con.execute(f"PRAGMA memory_limit='{DUCKDB_MEMORY_LIMIT}'")
con.execute(f"PRAGMA temp_directory='{tmp_dir}'")
con.execute(f"PRAGMA max_temp_directory_size='{DUCKDB_MAX_TEMP_DIR_SIZE}'")
con.execute("SET preserve_insertion_order=false")

login_filter_sql = ""
if LOGIN_MODE == "login":
    login_filter_sql = "AND LOWER(TRIM(CAST(e.is_login AS VARCHAR))) = 'login'"
elif LOGIN_MODE == "non-login":
    login_filter_sql = "AND LOWER(TRIM(CAST(e.is_login AS VARCHAR))) = 'non-login'"
elif LOGIN_MODE == "all":
    login_filter_sql = ""
else:
    raise ValueError("LOGIN_MODE phải là login / non-login / all")

active_filter_sql = ""
if ACTIVE_EVENT_TYPES is not None:
    active_filter_sql = f"""
    AND LOWER(TRIM(CAST(e.event_type AS VARCHAR))) IN ({sql_str_list(ACTIVE_EVENT_TYPES)})
    """

date_filter_sql = ""
if START_DATE is not None:
    date_filter_sql += f" AND event_date >= DATE '{START_DATE}' "
if END_DATE is not None:
    date_filter_sql += f" AND event_date <= DATE '{END_DATE}' "

positive_sql = sql_str_list(POSITIVE_EVENT_TYPES)
strict_sql = sql_str_list(STRICT_CONTACT_EVENT_TYPES)

# ============================================================
# 2. BUILD DIM LITE
# ============================================================

print("\n[1/8] Build dim_lite...")

con.execute(f"""
CREATE OR REPLACE TABLE dim_lite AS
SELECT
    CAST(item_id AS VARCHAR) AS item_id,

    TRY_CAST(category AS INTEGER) AS dim_category,

    CASE
        WHEN city_name IS NULL OR TRIM(CAST(city_name AS VARCHAR)) = ''
        THEN NULL
        ELSE TRIM(CAST(city_name AS VARCHAR))
    END AS dim_city_name,

    CASE
        WHEN LOWER(TRIM(CAST(ad_type AS VARCHAR))) IN ('sell', 'let')
        THEN LOWER(TRIM(CAST(ad_type AS VARCHAR)))
        ELSE NULL
    END AS ad_type_clean

FROM read_parquet('{DIM_GLOB}')
WHERE item_id IS NOT NULL
""")

dim_df = con.execute("""
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT item_id) AS items,
    SUM(CASE WHEN ad_type_clean = 'sell' THEN 1 ELSE 0 END) AS sell_items,
    SUM(CASE WHEN ad_type_clean = 'let' THEN 1 ELSE 0 END) AS let_items,
    SUM(CASE WHEN ad_type_clean IS NULL THEN 1 ELSE 0 END) AS unknown_ad_type_items
FROM dim_lite
""").df()

display(dim_df)
dim_df.to_csv(os.path.join(OUTPUT_DIR, "00_dim_check.csv"), index=False, encoding="utf-8-sig")

# ============================================================
# 3. PER-FILE AGGREGATION
# ============================================================

print("\n[2/8] Per-file aggregation...")

def qpath(p):
    return p.replace("\\", "/").replace("'", "''")


for i, fp in enumerate(EVENT_FILES):
    fp_sql = qpath(fp)

    ub_out = qpath(os.path.join(PARTS_DIR, f"ub_{i:04d}.parquet"))
    city_out = qpath(os.path.join(PARTS_DIR, f"city_{i:04d}.parquet"))
    cat_out = qpath(os.path.join(PARTS_DIR, f"cat_{i:04d}.parquet"))
    ad_out = qpath(os.path.join(PARTS_DIR, f"ad_{i:04d}.parquet"))

    print(f"[{i+1}/{len(EVENT_FILES)}] {os.path.basename(fp)}")

    base_cte = f"""
    WITH src AS (
        SELECT
            CAST(e.user_id AS VARCHAR) AS user_id,

            COALESCE(
                TRY_CAST(e.date AS DATE),
                CAST(e.event_ts AS DATE)
            ) AS event_date,

            LOWER(TRIM(CAST(e.event_type AS VARCHAR))) AS event_type_clean,

            COALESCE(
                CASE
                    WHEN e.city_name IS NULL OR TRIM(CAST(e.city_name AS VARCHAR)) = ''
                    THEN NULL
                    ELSE TRIM(CAST(e.city_name AS VARCHAR))
                END,
                d.dim_city_name
            ) AS city_clean,

            COALESCE(
                TRY_CAST(e.category AS INTEGER),
                d.dim_category
            ) AS category_clean,

            d.ad_type_clean AS ad_type_clean

        FROM read_parquet('{fp_sql}') e
        LEFT JOIN dim_lite d
            ON CAST(e.item_id AS VARCHAR) = d.item_id
        WHERE e.user_id IS NOT NULL
            {login_filter_sql}
            {active_filter_sql}
    ),
    base AS (
        SELECT
            user_id,
            event_type_clean,
            city_clean,
            category_clean,
            ad_type_clean,

            CAST(
                EXTRACT(YEAR FROM event_date) * 24
                + (EXTRACT(MONTH FROM event_date) - 1) * 2
                + CASE
                    WHEN EXTRACT(DAY FROM event_date) <= 15 THEN 0
                    ELSE 1
                  END
                AS BIGINT
            ) AS bucket_id

        FROM src
        WHERE event_date IS NOT NULL
            {date_filter_sql}
    )
    """

    # 3.1 user-bucket overall
    con.execute(f"""
    COPY (
        {base_cte}
        SELECT
            user_id,
            bucket_id,
            COUNT(*) AS events,
            SUM(CASE WHEN event_type_clean IN ({positive_sql}) THEN 1 ELSE 0 END) AS positive_events,
            SUM(CASE WHEN event_type_clean IN ({strict_sql}) THEN 1 ELSE 0 END) AS strict_contact_events
        FROM base
        GROUP BY user_id, bucket_id
    )
    TO '{ub_out}' (FORMAT PARQUET, COMPRESSION ZSTD)
    """)

    # 3.2 city counts
    con.execute(f"""
    COPY (
        {base_cte}
        SELECT
            user_id,
            bucket_id,
            city_clean,
            COUNT(*) AS events,
            SUM(CASE WHEN event_type_clean IN ({positive_sql}) THEN 1 ELSE 0 END) AS positive_events
        FROM base
        WHERE city_clean IS NOT NULL
        GROUP BY user_id, bucket_id, city_clean
    )
    TO '{city_out}' (FORMAT PARQUET, COMPRESSION ZSTD)
    """)

    # 3.3 category counts
    con.execute(f"""
    COPY (
        {base_cte}
        SELECT
            user_id,
            bucket_id,
            category_clean,
            COUNT(*) AS events,
            SUM(CASE WHEN event_type_clean IN ({positive_sql}) THEN 1 ELSE 0 END) AS positive_events
        FROM base
        WHERE category_clean IS NOT NULL
        GROUP BY user_id, bucket_id, category_clean
    )
    TO '{cat_out}' (FORMAT PARQUET, COMPRESSION ZSTD)
    """)

    # 3.4 ad_type counts: sell / let
    con.execute(f"""
    COPY (
        {base_cte}
        SELECT
            user_id,
            bucket_id,
            ad_type_clean,
            COUNT(*) AS events,
            SUM(CASE WHEN event_type_clean IN ({positive_sql}) THEN 1 ELSE 0 END) AS positive_events
        FROM base
        WHERE ad_type_clean IN ('sell', 'let')
        GROUP BY user_id, bucket_id, ad_type_clean
    )
    TO '{ad_out}' (FORMAT PARQUET, COMPRESSION ZSTD)
    """)

print("\nPer-file aggregation done.")

# ============================================================
# 4. MERGE PARTS INTO FINAL PROFILE
# ============================================================

print("\n[3/8] Merge user-bucket overall...")

UB_GLOB = qpath(os.path.join(PARTS_DIR, "ub_*.parquet"))
CITY_GLOB = qpath(os.path.join(PARTS_DIR, "city_*.parquet"))
CAT_GLOB = qpath(os.path.join(PARTS_DIR, "cat_*.parquet"))
AD_GLOB = qpath(os.path.join(PARTS_DIR, "ad_*.parquet"))

con.execute(f"""
CREATE OR REPLACE TABLE user_bucket_base AS
SELECT
    user_id,
    bucket_id,
    SUM(events) AS events,
    SUM(positive_events) AS positive_events,
    SUM(strict_contact_events) AS strict_contact_events
FROM read_parquet('{UB_GLOB}')
GROUP BY user_id, bucket_id
""")

# Xóa ub parts sau khi merge để giải phóng disk
for f in glob.glob(os.path.join(PARTS_DIR, "ub_*.parquet")):
    os.remove(f)

print("\n[4/8] Merge city profile...")

con.execute(f"""
CREATE OR REPLACE TABLE city_counts AS
SELECT
    user_id,
    bucket_id,
    city_clean,
    SUM(events) AS events,
    SUM(positive_events) AS positive_events
FROM read_parquet('{CITY_GLOB}')
GROUP BY user_id, bucket_id, city_clean
""")

con.execute("""
CREATE OR REPLACE TABLE city_profile AS
SELECT
    user_id,
    bucket_id,
    COUNT(*) AS distinct_cities_seen
FROM city_counts
GROUP BY user_id, bucket_id
""")

con.execute("""
CREATE OR REPLACE TABLE city_pref AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY user_id, bucket_id
            ORDER BY events DESC, positive_events DESC, city_clean
        ) AS rn
    FROM city_counts
)
SELECT
    user_id,
    bucket_id,
    city_clean AS city_mode,
    events AS city_mode_events
FROM ranked
WHERE rn = 1
""")

con.execute("DROP TABLE city_counts")
con.execute("CHECKPOINT")

for f in glob.glob(os.path.join(PARTS_DIR, "city_*.parquet")):
    os.remove(f)

print("\n[5/8] Merge category profile...")

con.execute(f"""
CREATE OR REPLACE TABLE cat_counts AS
SELECT
    user_id,
    bucket_id,
    category_clean,
    SUM(events) AS events,
    SUM(positive_events) AS positive_events
FROM read_parquet('{CAT_GLOB}')
GROUP BY user_id, bucket_id, category_clean
""")

con.execute("""
CREATE OR REPLACE TABLE cat_profile AS
SELECT
    user_id,
    bucket_id,
    COUNT(*) AS distinct_categories_seen
FROM cat_counts
GROUP BY user_id, bucket_id
""")

con.execute("""
CREATE OR REPLACE TABLE cat_pref AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY user_id, bucket_id
            ORDER BY events DESC, positive_events DESC, category_clean
        ) AS rn
    FROM cat_counts
)
SELECT
    user_id,
    bucket_id,
    category_clean AS category_mode,
    events AS category_mode_events
FROM ranked
WHERE rn = 1
""")

con.execute("DROP TABLE cat_counts")
con.execute("CHECKPOINT")

for f in glob.glob(os.path.join(PARTS_DIR, "cat_*.parquet")):
    os.remove(f)

print("\n[6/8] Merge ad_type profile...")

con.execute(f"""
CREATE OR REPLACE TABLE ad_counts AS
SELECT
    user_id,
    bucket_id,
    ad_type_clean,
    SUM(events) AS events,
    SUM(positive_events) AS positive_events
FROM read_parquet('{AD_GLOB}')
GROUP BY user_id, bucket_id, ad_type_clean
""")

con.execute("""
CREATE OR REPLACE TABLE ad_profile AS
SELECT
    user_id,
    bucket_id,
    COUNT(*) AS distinct_ad_types_seen
FROM ad_counts
GROUP BY user_id, bucket_id
""")

con.execute("""
CREATE OR REPLACE TABLE ad_pref AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY user_id, bucket_id
            ORDER BY events DESC, positive_events DESC, ad_type_clean
        ) AS rn
    FROM ad_counts
)
SELECT
    user_id,
    bucket_id,
    ad_type_clean AS ad_type_mode,
    events AS ad_type_mode_events
FROM ranked
WHERE rn = 1
""")

con.execute("DROP TABLE ad_counts")
con.execute("CHECKPOINT")

for f in glob.glob(os.path.join(PARTS_DIR, "ad_*.parquet")):
    os.remove(f)

# Remove empty parts dir
try:
    os.rmdir(PARTS_DIR)
except Exception:
    pass

# Final profile
con.execute("""
CREATE OR REPLACE TABLE user_bucket_profile AS
SELECT
    b.user_id,
    b.bucket_id,

    b.events,
    b.positive_events,
    b.strict_contact_events,

    COALESCE(cp.distinct_cities_seen, 0) AS distinct_cities_seen,
    COALESCE(kp.distinct_categories_seen, 0) AS distinct_categories_seen,
    COALESCE(ap.distinct_ad_types_seen, 0) AS distinct_ad_types_seen,

    city.city_mode,
    cat.category_mode,
    ad.ad_type_mode,

    CASE WHEN COALESCE(cp.distinct_cities_seen, 0) >= 2 THEN 1 ELSE 0 END AS is_multi_city_2plus,
    CASE WHEN COALESCE(cp.distinct_cities_seen, 0) >= 3 THEN 1 ELSE 0 END AS is_multi_city_3plus,
    CASE WHEN COALESCE(ap.distinct_ad_types_seen, 0) >= 2 THEN 1 ELSE 0 END AS is_mixed_sell_let

FROM user_bucket_base b
LEFT JOIN city_profile cp
    ON b.user_id = cp.user_id
    AND b.bucket_id = cp.bucket_id
LEFT JOIN cat_profile kp
    ON b.user_id = kp.user_id
    AND b.bucket_id = kp.bucket_id
LEFT JOIN ad_profile ap
    ON b.user_id = ap.user_id
    AND b.bucket_id = ap.bucket_id
LEFT JOIN city_pref city
    ON b.user_id = city.user_id
    AND b.bucket_id = city.bucket_id
LEFT JOIN cat_pref cat
    ON b.user_id = cat.user_id
    AND b.bucket_id = cat.bucket_id
LEFT JOIN ad_pref ad
    ON b.user_id = ad.user_id
    AND b.bucket_id = ad.bucket_id
""")

profile_check = con.execute("""
SELECT
    COUNT(*) AS user_bucket_rows,
    COUNT(DISTINCT user_id) AS users,
    MIN(bucket_id) AS min_bucket_id,
    MAX(bucket_id) AS max_bucket_id,
    AVG(distinct_cities_seen) AS avg_cities_per_user_bucket,
    AVG(distinct_categories_seen) AS avg_categories_per_user_bucket,
    AVG(distinct_ad_types_seen) AS avg_ad_types_per_user_bucket,
    SUM(is_multi_city_2plus) * 1.0 / COUNT(*) AS multi_city_2plus_rate,
    SUM(is_multi_city_3plus) * 1.0 / COUNT(*) AS multi_city_3plus_rate,
    SUM(is_mixed_sell_let) * 1.0 / COUNT(*) AS mixed_sell_let_rate
FROM user_bucket_profile
""").df()

display(profile_check)
profile_check.to_csv(os.path.join(OUTPUT_DIR, "01_user_bucket_profile_check.csv"), index=False, encoding="utf-8-sig")

# ============================================================
# 5. BUCKET CALENDAR + COHORT
# ============================================================

print("\n[7/8] Build cohort and retained state...")

con.execute("""
CREATE OR REPLACE TABLE bucket_calendar AS
WITH lim AS (
    SELECT MIN(bucket_id) AS min_bucket_id, MAX(bucket_id) AS max_bucket_id
    FROM user_bucket_profile
),
ids AS (
    SELECT r.bucket_id
    FROM lim
    CROSS JOIN LATERAL range(
        CAST(min_bucket_id AS BIGINT),
        CAST(max_bucket_id + 1 AS BIGINT)
    ) AS r(bucket_id)
),
parts AS (
    SELECT
        bucket_id,
        CAST(FLOOR(bucket_id / 24) AS INTEGER) AS yy,
        CAST(FLOOR((bucket_id % 24) / 2) + 1 AS INTEGER) AS mm,
        CAST(bucket_id % 2 AS INTEGER) AS half_idx
    FROM ids
),
starts AS (
    SELECT
        bucket_id,
        yy,
        mm,
        half_idx,
        CAST(
            CAST(yy AS VARCHAR)
            || '-'
            || LPAD(CAST(mm AS VARCHAR), 2, '0')
            || '-01'
            AS DATE
        )
        + CASE WHEN half_idx = 1 THEN INTERVAL '15 days' ELSE INTERVAL '0 days' END AS bucket_start
    FROM parts
)
SELECT
    bucket_id,
    CAST(bucket_start AS DATE) AS bucket_start,
    CASE
        WHEN half_idx = 0 THEN CAST(bucket_start + INTERVAL '14 days' AS DATE)
        ELSE CAST(DATE_TRUNC('month', bucket_start) + INTERVAL '1 month' - INTERVAL '1 day' AS DATE)
    END AS bucket_end,
    STRFTIME(bucket_start, '%Y-%m')
        || CASE WHEN half_idx = 0 THEN '-H1' ELSE '-H2' END AS bucket_label
FROM starts
ORDER BY bucket_id
""")

bucket_calendar_df = con.execute("SELECT * FROM bucket_calendar ORDER BY bucket_id").df()
display(bucket_calendar_df)
bucket_calendar_df.to_csv(os.path.join(OUTPUT_DIR, "02_bucket_calendar.csv"), index=False, encoding="utf-8-sig")

con.execute("""
CREATE OR REPLACE TABLE user_cohort AS
WITH ranked AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY bucket_id
        ) AS rn
    FROM user_bucket_profile
)
SELECT
    user_id,
    bucket_id AS cohort_bucket_id,

    city_mode AS cohort_city_mode,
    category_mode AS cohort_category_mode,
    ad_type_mode AS cohort_ad_type_mode,

    distinct_cities_seen AS cohort_distinct_cities_seen,
    distinct_categories_seen AS cohort_distinct_categories_seen,
    distinct_ad_types_seen AS cohort_distinct_ad_types_seen,

    is_multi_city_2plus AS cohort_is_multi_city_2plus,
    is_multi_city_3plus AS cohort_is_multi_city_3plus,
    is_mixed_sell_let AS cohort_is_mixed_sell_let
FROM ranked
WHERE rn = 1
""")

con.execute("""
CREATE OR REPLACE TABLE retained_user_state AS
SELECT
    c.user_id,

    c.cohort_bucket_id,
    bc0.bucket_label AS cohort_label,

    p.bucket_id AS active_bucket_id,
    bc1.bucket_label AS active_bucket_label,

    p.bucket_id - c.cohort_bucket_id AS bucket_offset,
    '+' || CAST(p.bucket_id - c.cohort_bucket_id AS VARCHAR) AS offset_label,

    c.cohort_city_mode,
    c.cohort_category_mode,
    c.cohort_ad_type_mode,

    c.cohort_distinct_cities_seen,
    c.cohort_distinct_categories_seen,
    c.cohort_distinct_ad_types_seen,

    c.cohort_is_multi_city_2plus,
    c.cohort_is_multi_city_3plus,
    c.cohort_is_mixed_sell_let,

    p.city_mode,
    p.category_mode,
    p.ad_type_mode,

    p.events,
    p.positive_events,
    p.strict_contact_events,

    p.distinct_cities_seen,
    p.distinct_categories_seen,
    p.distinct_ad_types_seen,

    p.is_multi_city_2plus,
    p.is_multi_city_3plus,
    p.is_mixed_sell_let,

    CASE
        WHEN c.cohort_city_mode IS NOT NULL
             AND p.city_mode IS NOT NULL
             AND c.cohort_city_mode <> p.city_mode
        THEN 1 ELSE 0
    END AS city_switched,

    CASE
        WHEN c.cohort_category_mode IS NOT NULL
             AND p.category_mode IS NOT NULL
             AND c.cohort_category_mode <> p.category_mode
        THEN 1 ELSE 0
    END AS category_switched,

    CASE
        WHEN c.cohort_ad_type_mode IN ('sell', 'let')
             AND p.ad_type_mode IN ('sell', 'let')
             AND c.cohort_ad_type_mode <> p.ad_type_mode
        THEN 1 ELSE 0
    END AS ad_type_switched

FROM user_cohort c
JOIN user_bucket_profile p
    ON c.user_id = p.user_id
    AND p.bucket_id >= c.cohort_bucket_id
LEFT JOIN bucket_calendar bc0
    ON c.cohort_bucket_id = bc0.bucket_id
LEFT JOIN bucket_calendar bc1
    ON p.bucket_id = bc1.bucket_id
""")

state_check = con.execute("""
SELECT
    COUNT(*) AS retained_user_bucket_rows,
    COUNT(DISTINCT user_id) AS users,
    MIN(bucket_offset) AS min_offset,
    MAX(bucket_offset) AS max_offset
FROM retained_user_state
""").df()

display(state_check)
state_check.to_csv(os.path.join(OUTPUT_DIR, "03_retained_state_check.csv"), index=False, encoding="utf-8-sig")

# ============================================================
# 6. SUMMARY TABLES
# ============================================================

print("\n[8/8] Build summaries...")

overall_offset_df = con.execute("""
SELECT
    bucket_offset,
    offset_label,

    COUNT(*) AS active_user_buckets,

    SUM(city_switched) AS city_switched_users,
    SUM(category_switched) AS category_switched_users,
    SUM(ad_type_switched) AS ad_type_switched_users,

    SUM(is_multi_city_2plus) AS current_multi_city_2plus_users,
    SUM(is_multi_city_3plus) AS current_multi_city_3plus_users,
    SUM(is_mixed_sell_let) AS current_mixed_sell_let_users,

    SUM(CASE WHEN city_switched = 1 AND is_multi_city_2plus = 1 THEN 1 ELSE 0 END)
        AS city_switch_and_multi_city_2plus,

    SUM(CASE WHEN city_switched = 1 AND is_multi_city_3plus = 1 THEN 1 ELSE 0 END)
        AS city_switch_and_multi_city_3plus,

    SUM(CASE WHEN category_switched = 1 AND ad_type_switched = 1 THEN 1 ELSE 0 END)
        AS category_switch_and_ad_type_switch,

    SUM(CASE WHEN category_switched = 1 AND is_mixed_sell_let = 1 THEN 1 ELSE 0 END)
        AS category_switch_and_mixed_sell_let

FROM retained_user_state
GROUP BY bucket_offset, offset_label
ORDER BY bucket_offset
""").df()

overall_offset_df["city_switch_rate"] = (
    overall_offset_df["city_switched_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["category_switch_rate"] = (
    overall_offset_df["category_switched_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["ad_type_switch_rate"] = (
    overall_offset_df["ad_type_switched_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["current_multi_city_2plus_rate"] = (
    overall_offset_df["current_multi_city_2plus_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["current_multi_city_3plus_rate"] = (
    overall_offset_df["current_multi_city_3plus_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["current_mixed_sell_let_rate"] = (
    overall_offset_df["current_mixed_sell_let_users"] /
    overall_offset_df["active_user_buckets"].replace(0, np.nan)
)
overall_offset_df["multi_city_2plus_share_among_city_switch"] = (
    overall_offset_df["city_switch_and_multi_city_2plus"] /
    overall_offset_df["city_switched_users"].replace(0, np.nan)
)
overall_offset_df["multi_city_3plus_share_among_city_switch"] = (
    overall_offset_df["city_switch_and_multi_city_3plus"] /
    overall_offset_df["city_switched_users"].replace(0, np.nan)
)
overall_offset_df["ad_type_switch_share_among_category_switch"] = (
    overall_offset_df["category_switch_and_ad_type_switch"] /
    overall_offset_df["category_switched_users"].replace(0, np.nan)
)
overall_offset_df["mixed_sell_let_share_among_category_switch"] = (
    overall_offset_df["category_switch_and_mixed_sell_let"] /
    overall_offset_df["category_switched_users"].replace(0, np.nan)
)

display(overall_offset_df)
overall_offset_df.to_csv(
    os.path.join(OUTPUT_DIR, "04_overall_offset_switch_diagnosis.csv"),
    index=False,
    encoding="utf-8-sig"
)

# Retention by first-seen ad_type
retention_by_ad_type_df = con.execute("""
WITH maxb AS (
    SELECT MAX(bucket_id) AS max_bucket_id
    FROM bucket_calendar
),
cohort_ad AS (
    SELECT
        COALESCE(cohort_ad_type_mode, 'unknown') AS cohort_ad_type_mode,
        cohort_bucket_id,
        COUNT(*) AS cohort_users
    FROM user_cohort
    GROUP BY
        COALESCE(cohort_ad_type_mode, 'unknown'),
        cohort_bucket_id
),
grid AS (
    SELECT
        ca.cohort_ad_type_mode,
        ca.cohort_bucket_id,
        ca.cohort_users,
        r.bucket_offset
    FROM cohort_ad ca
    CROSS JOIN maxb
    CROSS JOIN LATERAL range(
        0,
        CAST(maxb.max_bucket_id - ca.cohort_bucket_id + 1 AS BIGINT)
    ) AS r(bucket_offset)
),
active AS (
    SELECT
        COALESCE(cohort_ad_type_mode, 'unknown') AS cohort_ad_type_mode,
        cohort_bucket_id,
        bucket_offset,
        COUNT(*) AS active_users
    FROM retained_user_state
    GROUP BY
        COALESCE(cohort_ad_type_mode, 'unknown'),
        cohort_bucket_id,
        bucket_offset
)
SELECT
    g.cohort_ad_type_mode,
    g.bucket_offset,
    '+' || CAST(g.bucket_offset AS VARCHAR) AS offset_label,
    SUM(COALESCE(a.active_users, 0)) AS active_users,
    SUM(g.cohort_users) AS eligible_cohort_users,
    SUM(COALESCE(a.active_users, 0)) * 1.0 / NULLIF(SUM(g.cohort_users), 0)
        AS exact_retention_rate
FROM grid g
LEFT JOIN active a
    ON g.cohort_ad_type_mode = a.cohort_ad_type_mode
    AND g.cohort_bucket_id = a.cohort_bucket_id
    AND g.bucket_offset = a.bucket_offset
GROUP BY
    g.cohort_ad_type_mode,
    g.bucket_offset
ORDER BY
    g.cohort_ad_type_mode,
    g.bucket_offset
""").df()

display(retention_by_ad_type_df)
retention_by_ad_type_df.to_csv(
    os.path.join(OUTPUT_DIR, "05_retention_by_first_seen_ad_type.csv"),
    index=False,
    encoding="utf-8-sig"
)

# Category switch decomposition
category_switch_decomp_df = con.execute("""
SELECT
    bucket_offset,
    offset_label,

    CASE
        WHEN category_switched = 1 AND ad_type_switched = 1
            THEN 'category switch + sell/let switch'
        WHEN category_switched = 1 AND ad_type_switched = 0
            THEN 'category switch only'
        WHEN category_switched = 0 AND ad_type_switched = 1
            THEN 'sell/let switch only'
        ELSE 'no category/ad_type switch'
    END AS switch_decomp,

    COUNT(*) AS active_user_buckets
FROM retained_user_state
GROUP BY
    bucket_offset,
    offset_label,
    CASE
        WHEN category_switched = 1 AND ad_type_switched = 1
            THEN 'category switch + sell/let switch'
        WHEN category_switched = 1 AND ad_type_switched = 0
            THEN 'category switch only'
        WHEN category_switched = 0 AND ad_type_switched = 1
            THEN 'sell/let switch only'
        ELSE 'no category/ad_type switch'
    END
ORDER BY bucket_offset, active_user_buckets DESC
""").df()

category_switch_decomp_df["share_within_offset"] = (
    category_switch_decomp_df["active_user_buckets"] /
    category_switch_decomp_df.groupby("bucket_offset")["active_user_buckets"].transform("sum")
)

display(category_switch_decomp_df)
category_switch_decomp_df.to_csv(
    os.path.join(OUTPUT_DIR, "06_category_switch_decomposition.csv"),
    index=False,
    encoding="utf-8-sig"
)

# City breadth diagnosis
city_breadth_df = con.execute("""
SELECT
    bucket_offset,
    offset_label,

    CASE
        WHEN distinct_cities_seen <= 1 THEN '1 city'
        WHEN distinct_cities_seen = 2 THEN '2 cities'
        WHEN distinct_cities_seen >= 3 THEN '3+ cities'
        ELSE 'unknown'
    END AS city_breadth,

    COUNT(*) AS active_user_buckets,
    SUM(city_switched) AS city_switched_users,
    SUM(category_switched) AS category_switched_users,
    SUM(ad_type_switched) AS ad_type_switched_users
FROM retained_user_state
GROUP BY
    bucket_offset,
    offset_label,
    CASE
        WHEN distinct_cities_seen <= 1 THEN '1 city'
        WHEN distinct_cities_seen = 2 THEN '2 cities'
        WHEN distinct_cities_seen >= 3 THEN '3+ cities'
        ELSE 'unknown'
    END
ORDER BY bucket_offset, city_breadth
""").df()

city_breadth_df["city_switch_rate"] = (
    city_breadth_df["city_switched_users"] /
    city_breadth_df["active_user_buckets"].replace(0, np.nan)
)
city_breadth_df["category_switch_rate"] = (
    city_breadth_df["category_switched_users"] /
    city_breadth_df["active_user_buckets"].replace(0, np.nan)
)
city_breadth_df["ad_type_switch_rate"] = (
    city_breadth_df["ad_type_switched_users"] /
    city_breadth_df["active_user_buckets"].replace(0, np.nan)
)

display(city_breadth_df)
city_breadth_df.to_csv(
    os.path.join(OUTPUT_DIR, "07_switch_by_city_breadth.csv"),
    index=False,
    encoding="utf-8-sig"
)

# Top transitions
top_city_transitions_df = con.execute("""
SELECT
    bucket_offset,
    offset_label,
    cohort_city_mode,
    city_mode AS current_city_mode,
    COUNT(*) AS users
FROM retained_user_state
WHERE city_switched = 1
GROUP BY
    bucket_offset,
    offset_label,
    cohort_city_mode,
    city_mode
ORDER BY bucket_offset, users DESC
""").df()

top_city_transitions_df.to_csv(
    os.path.join(OUTPUT_DIR, "08_top_city_transitions.csv"),
    index=False,
    encoding="utf-8-sig"
)

top_category_transitions_df = con.execute("""
SELECT
    bucket_offset,
    offset_label,
    CAST(cohort_category_mode AS VARCHAR) AS cohort_category_mode,
    CAST(category_mode AS VARCHAR) AS current_category_mode,
    COUNT(*) AS users
FROM retained_user_state
WHERE category_switched = 1
GROUP BY
    bucket_offset,
    offset_label,
    CAST(cohort_category_mode AS VARCHAR),
    CAST(category_mode AS VARCHAR)
ORDER BY bucket_offset, users DESC
""").df()

top_category_transitions_df.to_csv(
    os.path.join(OUTPUT_DIR, "09_top_category_transitions.csv"),
    index=False,
    encoding="utf-8-sig"
)

# Quick key offsets
important_offsets = [1, 2, 3, 4, 6, 8, 10]
quick_df = overall_offset_df[overall_offset_df["bucket_offset"].isin(important_offsets)].copy()

display(quick_df)
quick_df.to_csv(
    os.path.join(OUTPUT_DIR, "10_quick_key_offsets.csv"),
    index=False,
    encoding="utf-8-sig"
)

# ============================================================
# 7. PLOTS
# ============================================================

def save_plotly(fig, name):
    html_path = os.path.join(OUTPUT_DIR, f"{name}.html")
    fig.write_html(html_path)
    print("[SAVE HTML]", html_path)

    try:
        png_path = os.path.join(OUTPUT_DIR, f"{name}.png")
        fig.write_image(png_path, scale=2)
        print("[SAVE PNG ]", png_path)
    except Exception as e:
        print("[SKIP PNG]", name, str(e)[:100])


# 7.1 Overall switch
plot_df = overall_offset_df.melt(
    id_vars=["bucket_offset", "offset_label"],
    value_vars=[
        "city_switch_rate",
        "category_switch_rate",
        "ad_type_switch_rate",
        "current_multi_city_2plus_rate",
        "current_multi_city_3plus_rate",
        "current_mixed_sell_let_rate",
    ],
    var_name="metric",
    value_name="rate"
)

name_map = {
    "city_switch_rate": "Dominant city switched",
    "category_switch_rate": "Dominant category switched",
    "ad_type_switch_rate": "Dominant sell/let switched",
    "current_multi_city_2plus_rate": "Current bucket: 2+ cities",
    "current_multi_city_3plus_rate": "Current bucket: 3+ cities",
    "current_mixed_sell_let_rate": "Current bucket: mixed sell+let",
}
plot_df["metric"] = plot_df["metric"].map(name_map)

fig = px.line(
    plot_df,
    x="offset_label",
    y="rate",
    color="metric",
    markers=True,
    title="Switch & Multi-city Rate Among Retained Users",
    hover_data={"bucket_offset": True, "rate": ":.2%"}
)
fig.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Rate among retained active users",
    yaxis_tickformat=".0%",
    height=600,
    width=1150
)
fig.show()
save_plotly(fig, "01_switch_and_multicity_overall")

# 7.2 City switch diagnosis
plot_df = overall_offset_df.melt(
    id_vars=["bucket_offset", "offset_label"],
    value_vars=[
        "current_multi_city_2plus_rate",
        "multi_city_2plus_share_among_city_switch",
        "current_multi_city_3plus_rate",
        "multi_city_3plus_share_among_city_switch",
    ],
    var_name="metric",
    value_name="rate"
)

name_map = {
    "current_multi_city_2plus_rate": "All retained: 2+ cities",
    "multi_city_2plus_share_among_city_switch": "City switchers: 2+ cities",
    "current_multi_city_3plus_rate": "All retained: 3+ cities",
    "multi_city_3plus_share_among_city_switch": "City switchers: 3+ cities",
}
plot_df["metric"] = plot_df["metric"].map(name_map)

fig = px.line(
    plot_df,
    x="offset_label",
    y="rate",
    color="metric",
    markers=True,
    title="Does City Switching Come From Multi-city Users?",
    hover_data={"bucket_offset": True, "rate": ":.2%"}
)
fig.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Rate",
    yaxis_tickformat=".0%",
    height=600,
    width=1150
)
fig.show()
save_plotly(fig, "02_city_switch_multicity_diagnosis")

# 7.3 Retention by let/sell
fig = px.line(
    retention_by_ad_type_df,
    x="offset_label",
    y="exact_retention_rate",
    color="cohort_ad_type_mode",
    markers=True,
    title="Exact Retention by First-seen Dominant ad_type: let vs sell",
    hover_data={
        "bucket_offset": True,
        "active_users": ":,",
        "eligible_cohort_users": ":,",
        "exact_retention_rate": ":.2%",
    }
)
fig.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Exact retention rate",
    yaxis_tickformat=".0%",
    height=550,
    width=1100
)
fig.show()
save_plotly(fig, "03_retention_by_first_seen_ad_type")

# 7.4 Category decomposition
fig = px.bar(
    category_switch_decomp_df,
    x="offset_label",
    y="share_within_offset",
    color="switch_decomp",
    title="Category Switch Decomposition: Is It Actually Sell/Let Switch?",
    hover_data={
        "bucket_offset": True,
        "active_user_buckets": ":,",
        "share_within_offset": ":.2%",
    }
)
fig.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Share among retained active users",
    yaxis_tickformat=".0%",
    barmode="stack",
    height=600,
    width=1150
)
fig.show()
save_plotly(fig, "04_category_switch_decomposition")

# 7.5 City breadth
plot_df = city_breadth_df.melt(
    id_vars=["bucket_offset", "offset_label", "city_breadth"],
    value_vars=[
        "city_switch_rate",
        "category_switch_rate",
        "ad_type_switch_rate",
    ],
    var_name="metric",
    value_name="rate"
)

name_map = {
    "city_switch_rate": "City switch rate",
    "category_switch_rate": "Category switch rate",
    "ad_type_switch_rate": "Sell/let switch rate",
}
plot_df["metric"] = plot_df["metric"].map(name_map)

fig = px.line(
    plot_df,
    x="offset_label",
    y="rate",
    color="city_breadth",
    line_dash="metric",
    markers=True,
    title="Switch Rates by Current Bucket City Breadth",
    hover_data={"bucket_offset": True, "rate": ":.2%"}
)
fig.update_layout(
    xaxis_title="Bucket offset",
    yaxis_title="Switch rate",
    yaxis_tickformat=".0%",
    height=650,
    width=1200
)
fig.show()
save_plotly(fig, "05_switch_by_city_breadth")

# ============================================================
# 8. DONE
# ============================================================

print("\nDONE.")
print("Output folder:", OUTPUT_DIR)

print("""
CÁCH ĐỌC NHANH:

1) 10_quick_key_offsets.csv
   - Nhìn các offset +1, +2, +4, +6, +8, +10.
   - city_switch_rate: bao nhiêu retained user đổi dominant city.
   - category_switch_rate: bao nhiêu retained user đổi dominant category.
   - ad_type_switch_rate: bao nhiêu retained user đổi dominant sell/let.

2) 02_city_switch_multicity_diagnosis.html
   - Nếu "City switchers: 2+ cities" cao hơn nhiều "All retained: 2+ cities":
     city switch đang bị nhóm xem nhiều city kéo lên.
   - Nếu không cao hơn nhiều:
     city switch có thể là đổi khu vực thật.

3) 03_retention_by_first_seen_ad_type.html
   - So let vs sell.
   - Nếu sell giữ chân lâu hơn let:
     mua nhà có journey dài hơn thuê.
   - Nếu let rớt nhanh:
     thuê có thể là nhu cầu ngắn hạn, quyết định nhanh hơn.

4) 04_category_switch_decomposition.html
   - Nếu phần "category switch only" lớn:
     user đổi phân khúc nhưng vẫn cùng thuê hoặc cùng mua.
   - Nếu "category switch + sell/let switch" lớn:
     user đổi cả intent lớn: thuê <-> mua.

5) 05_switch_by_city_breadth.html
   - Nhóm 3+ cities mà switch rate cao bất thường:
     có thể là broad search / professional browsing / cò-like behavior.
""")

print("Saved CSV/HTML:")
for f in sorted(os.listdir(OUTPUT_DIR)):
    if f.endswith(".csv") or f.endswith(".html"):
        print("-", f)

con.close()

EVENTS_PATH: /kaggle/input/datasets/kimkhanhnguyen214/datathon2026-2/fact_user_events
DIM_PATH   : /kaggle/input/datasets/kimkhanhnguyen214/datathon2026-1/dim_listing
EVENT_FILES: 500
OUTPUT_DIR : /kaggle/working/retention_lowdisk_sell_let_multicity

[1/8] Build dim_lite...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

      rows    items  sell_items  let_items  unknown_ad_type_items
0  3107114  3107114   1620385.0  1486729.0                    0.0

[2/8] Per-file aggregation...
[1/500] datathon_fact_user_events-000000000000.parquet
[2/500] datathon_fact_user_events-000000000001.parquet
[3/500] datathon_fact_user_events-000000000002.parquet
[4/500] datathon_fact_user_events-000000000003.parquet
[5/500] datathon_fact_user_events-000000000004.parquet
[6/500] datathon_fact_user_events-000000000005.parquet
[7/500] datathon_fact_user_events-000000000006.parquet
[8/500] datathon_fact_user_events-000000000007.parquet
[9/500] datathon_fact_user_events-000000000008.parquet
[10/500] datathon_fact_user_events-000000000009.parquet
[11/500] datathon_fact_user_events-000000000010.parquet
[12/500] datathon_fact_user_events-000000000011.parquet
[13/500] datathon_fact_user_events-000000000012.parquet
[14/500] datathon_fact_user_events-000000000013.parquet
[15/500] datathon_fact_user_events-000000000014.parquet
[16/500] datathon_fact_user_events-000000000015.parquet
[17/500] datathon_fact_user_events-000000000016.parquet
[18/500] datathon_fact_user_events-000000000017.parquet
[19/500] datathon_fact_user_events-000000000018.parquet
[20/500] datathon_fact_user_events-000000000019.parquet
[21/500] datathon_fact_user_events-000000000020.parquet
[22/500] datathon_fact_user_events-000000000021.parquet
[23/500] datathon_fact_user_events-000000000022.parquet
[24/500] datathon_fact_user_events-000000000023.parquet
[25/500] datathon_fact_user_events-000000000024.parquet
[26/500] datathon_fact_user_events-000000000025.parquet
[27/500] datathon_fact_user_events-000000000026.parquet
[28/500] datathon_fact_user_events-000000000027.parquet
[29/500] datathon_fact_user_events-000000000028.parquet
[30/500] datathon_fact_user_events-000000000029.parquet
[31/500] datathon_fact_user_events-000000000030.parquet
[32/500] datathon_fact_user_events-000000000031.parquet
[33/500] datathon_fact_user_events-000000000032.parquet
[34/500] datathon_fact_user_events-000000000033.parquet
[35/500] datathon_fact_user_events-000000000034.parquet
[36/500] datathon_fact_user_events-000000000035.parquet
[37/500] datathon_fact_user_events-000000000036.parquet
[38/500] datathon_fact_user_events-000000000037.parquet
[39/500] datathon_fact_user_events-000000000038.parquet
[40/500] datathon_fact_user_events-000000000039.parquet
[41/500] datathon_fact_user_events-000000000040.parquet
[42/500] datathon_fact_user_events-000000000041.parquet
[43/500] datathon_fact_user_events-000000000042.parquet
[44/500] datathon_fact_user_events-000000000043.parquet
[45/500] datathon_fact_user_events-000000000044.parquet
[46/500] datathon_fact_user_events-000000000045.parquet
[47/500] datathon_fact_user_events-000000000046.parquet
[48/500] datathon_fact_user_events-000000000047.parquet
[49/500] datathon_fact_user_events-000000000048.parquet
[50/500] datathon_fact_user_events-000000000049.parquet
[51/500] datathon_fact_user_events-000000000050.parquet
[52/500] datathon_fact_user_events-000000000051.parquet
[53/500] datathon_fact_user_events-000000000052.parquet
[54/500] datathon_fact_user_events-000000000053.parquet
[55/500] datathon_fact_user_events-000000000054.parquet
[56/500] datathon_fact_user_events-000000000055.parquet
[57/500] datathon_fact_user_events-000000000056.parquet
[58/500] datathon_fact_user_events-000000000057.parquet
[59/500] datathon_fact_user_events-000000000058.parquet
[60/500] datathon_fact_user_events-000000000059.parquet
[61/500] datathon_fact_user_events-000000000060.parquet
[62/500] datathon_fact_user_events-000000000061.parquet
[63/500] datathon_fact_user_events-000000000062.parquet
[64/500] datathon_fact_user_events-000000000063.parquet
[65/500] datathon_fact_user_events-000000000064.parquet
[66/500] datathon_fact_user_events-000000000065.parquet
[67/500] datathon_fact_user_events-000000000066.parquet
[68/500] datathon_fact_user_events-000000000067.parquet
[69/500] datathon_fact_user_events-000000000068.parquet
[70/500] datathon_fact_user_events-000000000069.parquet
[71/500] datathon_fact_user_events-000000000070.parquet
[72/500] datathon_fact_user_events-000000000071.parquet
[73/500] datathon_fact_user_events-000000000072.parquet
[74/500] datathon_fact_user_events-000000000073.parquet
[75/500] datathon_fact_user_events-000000000074.parquet
[76/500] datathon_fact_user_events-000000000075.parquet
[77/500] datathon_fact_user_events-000000000076.parquet
[78/500] datathon_fact_user_events-000000000077.parquet
[79/500] datathon_fact_user_events-000000000078.parquet
[80/500] datathon_fact_user_events-000000000079.parquet
[81/500] datathon_fact_user_events-000000000080.parquet
[82/500] datathon_fact_user_events-000000000081.parquet
[83/500] datathon_fact_user_events-000000000082.parquet
[84/500] datathon_fact_user_events-000000000083.parquet
[85/500] datathon_fact_user_events-000000000084.parquet
[86/500] datathon_fact_user_events-000000000085.parquet
[87/500] datathon_fact_user_events-000000000086.parquet
[88/500] datathon_fact_user_events-000000000087.parquet
[89/500] datathon_fact_user_events-000000000088.parquet
[90/500] datathon_fact_user_events-000000000089.parquet
[91/500] datathon_fact_user_events-000000000090.parquet
[92/500] datathon_fact_user_events-000000000091.parquet
[93/500] datathon_fact_user_events-000000000092.parquet
[94/500] datathon_fact_user_events-000000000093.parquet
[95/500] datathon_fact_user_events-000000000094.parquet
[96/500] datathon_fact_user_events-000000000095.parquet
[97/500] datathon_fact_user_events-000000000096.parquet
[98/500] datathon_fact_user_events-000000000097.parquet
[99/500] datathon_fact_user_events-000000000098.parquet
[100/500] datathon_fact_user_events-000000000099.parquet
[101/500] datathon_fact_user_events-000000000100.parquet
[102/500] datathon_fact_user_events-000000000101.parquet
[103/500] datathon_fact_user_events-000000000102.parquet
[104/500] datathon_fact_user_events-000000000103.parquet
[105/500] datathon_fact_user_events-000000000104.parquet
[106/500] datathon_fact_user_events-000000000105.parquet
[107/500] datathon_fact_user_events-000000000106.parquet
[108/500] datathon_fact_user_events-000000000107.parquet
[109/500] datathon_fact_user_events-000000000108.parquet
[110/500] datathon_fact_user_events-000000000109.parquet
[111/500] datathon_fact_user_events-000000000110.parquet
[112/500] datathon_fact_user_events-000000000111.parquet
[113/500] datathon_fact_user_events-000000000112.parquet
[114/500] datathon_fact_user_events-000000000113.parquet
[115/500] datathon_fact_user_events-000000000114.parquet
[116/500] datathon_fact_user_events-000000000115.parquet
[117/500] datathon_fact_user_events-000000000116.parquet
[118/500] datathon_fact_user_events-000000000117.parquet
[119/500] datathon_fact_user_events-000000000118.parquet
[120/500] datathon_fact_user_events-000000000119.parquet
[121/500] datathon_fact_user_events-000000000120.parquet
[122/500] datathon_fact_user_events-000000000121.parquet
[123/500] datathon_fact_user_events-000000000122.parquet
[124/500] datathon_fact_user_events-000000000123.parquet
[125/500] datathon_fact_user_events-000000000124.parquet
[126/500] datathon_fact_user_events-000000000125.parquet
[127/500] datathon_fact_user_events-000000000126.parquet
[128/500] datathon_fact_user_events-000000000127.parquet
[129/500] datathon_fact_user_events-000000000128.parquet
[130/500] datathon_fact_user_events-000000000129.parquet
[131/500] datathon_fact_user_events-000000000130.parquet
[132/500] datathon_fact_user_events-000000000131.parquet
[133/500] datathon_fact_user_events-000000000132.parquet
[134/500] datathon_fact_user_events-000000000133.parquet
[135/500] datathon_fact_user_events-000000000134.parquet
[136/500] datathon_fact_user_events-000000000135.parquet
[137/500] datathon_fact_user_events-000000000136.parquet
[138/500] datathon_fact_user_events-000000000137.parquet
[139/500] datathon_fact_user_events-000000000138.parquet
[140/500] datathon_fact_user_events-000000000139.parquet
[141/500] datathon_fact_user_events-000000000140.parquet
[142/500] datathon_fact_user_events-000000000141.parquet
[143/500] datathon_fact_user_events-000000000142.parquet
[144/500] datathon_fact_user_events-000000000143.parquet
[145/500] datathon_fact_user_events-000000000144.parquet
[146/500] datathon_fact_user_events-000000000145.parquet
[147/500] datathon_fact_user_events-000000000146.parquet
[148/500] datathon_fact_user_events-000000000147.parquet
[149/500] datathon_fact_user_events-000000000148.parquet
[150/500] datathon_fact_user_events-000000000149.parquet
[151/500] datathon_fact_user_events-000000000150.parquet
[152/500] datathon_fact_user_events-000000000151.parquet
[153/500] datathon_fact_user_events-000000000152.parquet
[154/500] datathon_fact_user_events-000000000153.parquet
[155/500] datathon_fact_user_events-000000000154.parquet
[156/500] datathon_fact_user_events-000000000155.parquet
[157/500] datathon_fact_user_events-000000000156.parquet
[158/500] datathon_fact_user_events-000000000157.parquet
[159/500] datathon_fact_user_events-000000000158.parquet
[160/500] datathon_fact_user_events-000000000159.parquet
[161/500] datathon_fact_user_events-000000000160.parquet
[162/500] datathon_fact_user_events-000000000161.parquet
[163/500] datathon_fact_user_events-000000000162.parquet
[164/500] datathon_fact_user_events-000000000163.parquet
[165/500] datathon_fact_user_events-000000000164.parquet
[166/500] datathon_fact_user_events-000000000165.parquet
[167/500] datathon_fact_user_events-000000000166.parquet
[168/500] datathon_fact_user_events-000000000167.parquet
[169/500] datathon_fact_user_events-000000000168.parquet
[170/500] datathon_fact_user_events-000000000169.parquet
[171/500] datathon_fact_user_events-000000000170.parquet
[172/500] datathon_fact_user_events-000000000171.parquet
[173/500] datathon_fact_user_events-000000000172.parquet
[174/500] datathon_fact_user_events-000000000173.parquet
[175/500] datathon_fact_user_events-000000000174.parquet
[176/500] datathon_fact_user_events-000000000175.parquet
[177/500] datathon_fact_user_events-000000000176.parquet
[178/500] datathon_fact_user_events-000000000177.parquet
[179/500] datathon_fact_user_events-000000000178.parquet
[180/500] datathon_fact_user_events-000000000179.parquet
[181/500] datathon_fact_user_events-000000000180.parquet
[182/500] datathon_fact_user_events-000000000181.parquet
[183/500] datathon_fact_user_events-000000000182.parquet
[184/500] datathon_fact_user_events-000000000183.parquet
[185/500] datathon_fact_user_events-000000000184.parquet
[186/500] datathon_fact_user_events-000000000185.parquet
[187/500] datathon_fact_user_events-000000000186.parquet
[188/500] datathon_fact_user_events-000000000187.parquet
[189/500] datathon_fact_user_events-000000000188.parquet
[190/500] datathon_fact_user_events-000000000189.parquet
[191/500] datathon_fact_user_events-000000000190.parquet
[192/500] datathon_fact_user_events-000000000191.parquet
[193/500] datathon_fact_user_events-000000000192.parquet
[194/500] datathon_fact_user_events-000000000193.parquet
[195/500] datathon_fact_user_events-000000000194.parquet
[196/500] datathon_fact_user_events-000000000195.parquet
[197/500] datathon_fact_user_events-000000000196.parquet
[198/500] datathon_fact_user_events-000000000197.parquet
[199/500] datathon_fact_user_events-000000000198.parquet
[200/500] datathon_fact_user_events-000000000199.parquet
[201/500] datathon_fact_user_events-000000000200.parquet
[202/500] datathon_fact_user_events-000000000201.parquet
[203/500] datathon_fact_user_events-000000000202.parquet
[204/500] datathon_fact_user_events-000000000203.parquet
[205/500] datathon_fact_user_events-000000000204.parquet
[206/500] datathon_fact_user_events-000000000205.parquet
[207/500] datathon_fact_user_events-000000000206.parquet
[208/500] datathon_fact_user_events-000000000207.parquet
[209/500] datathon_fact_user_events-000000000208.parquet
[210/500] datathon_fact_user_events-000000000209.parquet
[211/500] datathon_fact_user_events-000000000210.parquet
[212/500] datathon_fact_user_events-000000000211.parquet
[213/500] datathon_fact_user_events-000000000212.parquet
[214/500] datathon_fact_user_events-000000000213.parquet
[215/500] datathon_fact_user_events-000000000214.parquet
[216/500] datathon_fact_user_events-000000000215.parquet
[217/500] datathon_fact_user_events-000000000216.parquet
[218/500] datathon_fact_user_events-000000000217.parquet
[219/500] datathon_fact_user_events-000000000218.parquet
[220/500] datathon_fact_user_events-000000000219.parquet
[221/500] datathon_fact_user_events-000000000220.parquet
[222/500] datathon_fact_user_events-000000000221.parquet
[223/500] datathon_fact_user_events-000000000222.parquet
[224/500] datathon_fact_user_events-000000000223.parquet
[225/500] datathon_fact_user_events-000000000224.parquet
[226/500] datathon_fact_user_events-000000000225.parquet
[227/500] datathon_fact_user_events-000000000226.parquet
[228/500] datathon_fact_user_events-000000000227.parquet
[229/500] datathon_fact_user_events-000000000228.parquet
[230/500] datathon_fact_user_events-000000000229.parquet
[231/500] datathon_fact_user_events-000000000230.parquet
[232/500] datathon_fact_user_events-000000000231.parquet
[233/500] datathon_fact_user_events-000000000232.parquet
[234/500] datathon_fact_user_events-000000000233.parquet
[235/500] datathon_fact_user_events-000000000234.parquet
[236/500] datathon_fact_user_events-000000000235.parquet
[237/500] datathon_fact_user_events-000000000236.parquet
[238/500] datathon_fact_user_events-000000000237.parquet
[239/500] datathon_fact_user_events-000000000238.parquet
[240/500] datathon_fact_user_events-000000000239.parquet
[241/500] datathon_fact_user_events-000000000240.parquet
[242/500] datathon_fact_user_events-000000000241.parquet
[243/500] datathon_fact_user_events-000000000242.parquet
[244/500] datathon_fact_user_events-000000000243.parquet
[245/500] datathon_fact_user_events-000000000244.parquet
[246/500] datathon_fact_user_events-000000000245.parquet
[247/500] datathon_fact_user_events-000000000246.parquet
[248/500] datathon_fact_user_events-000000000247.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[249/500] datathon_fact_user_events-000000000248.parquet
[250/500] datathon_fact_user_events-000000000249.parquet
[251/500] datathon_fact_user_events-000000000250.parquet
[252/500] datathon_fact_user_events-000000000251.parquet
[253/500] datathon_fact_user_events-000000000252.parquet
[254/500] datathon_fact_user_events-000000000253.parquet
[255/500] datathon_fact_user_events-000000000254.parquet
[256/500] datathon_fact_user_events-000000000255.parquet
[257/500] datathon_fact_user_events-000000000256.parquet
[258/500] datathon_fact_user_events-000000000257.parquet
[259/500] datathon_fact_user_events-000000000258.parquet
[260/500] datathon_fact_user_events-000000000259.parquet
[261/500] datathon_fact_user_events-000000000260.parquet
[262/500] datathon_fact_user_events-000000000261.parquet
[263/500] datathon_fact_user_events-000000000262.parquet
[264/500] datathon_fact_user_events-000000000263.parquet
[265/500] datathon_fact_user_events-000000000264.parquet
[266/500] datathon_fact_user_events-000000000265.parquet
[267/500] datathon_fact_user_events-000000000266.parquet
[268/500] datathon_fact_user_events-000000000267.parquet
[269/500] datathon_fact_user_events-000000000268.parquet
[270/500] datathon_fact_user_events-000000000269.parquet
[271/500] datathon_fact_user_events-000000000270.parquet
[272/500] datathon_fact_user_events-000000000271.parquet
[273/500] datathon_fact_user_events-000000000272.parquet
[274/500] datathon_fact_user_events-000000000273.parquet
[275/500] datathon_fact_user_events-000000000274.parquet
[276/500] datathon_fact_user_events-000000000275.parquet
[277/500] datathon_fact_user_events-000000000276.parquet
[278/500] datathon_fact_user_events-000000000277.parquet
[279/500] datathon_fact_user_events-000000000278.parquet
[280/500] datathon_fact_user_events-000000000279.parquet
[281/500] datathon_fact_user_events-000000000280.parquet
[282/500] datathon_fact_user_events-000000000281.parquet
[283/500] datathon_fact_user_events-000000000282.parquet
[284/500] datathon_fact_user_events-000000000283.parquet
[285/500] datathon_fact_user_events-000000000284.parquet
[286/500] datathon_fact_user_events-000000000285.parquet
[287/500] datathon_fact_user_events-000000000286.parquet
[288/500] datathon_fact_user_events-000000000287.parquet
[289/500] datathon_fact_user_events-000000000288.parquet
[290/500] datathon_fact_user_events-000000000289.parquet
[291/500] datathon_fact_user_events-000000000290.parquet
[292/500] datathon_fact_user_events-000000000291.parquet
[293/500] datathon_fact_user_events-000000000292.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[294/500] datathon_fact_user_events-000000000293.parquet
[295/500] datathon_fact_user_events-000000000294.parquet
[296/500] datathon_fact_user_events-000000000295.parquet
[297/500] datathon_fact_user_events-000000000296.parquet
[298/500] datathon_fact_user_events-000000000297.parquet
[299/500] datathon_fact_user_events-000000000298.parquet
[300/500] datathon_fact_user_events-000000000299.parquet
[301/500] datathon_fact_user_events-000000000300.parquet
[302/500] datathon_fact_user_events-000000000301.parquet
[303/500] datathon_fact_user_events-000000000302.parquet
[304/500] datathon_fact_user_events-000000000303.parquet
[305/500] datathon_fact_user_events-000000000304.parquet
[306/500] datathon_fact_user_events-000000000305.parquet
[307/500] datathon_fact_user_events-000000000306.parquet
[308/500] datathon_fact_user_events-000000000307.parquet
[309/500] datathon_fact_user_events-000000000308.parquet
[310/500] datathon_fact_user_events-000000000309.parquet
[311/500] datathon_fact_user_events-000000000310.parquet
[312/500] datathon_fact_user_events-000000000311.parquet
[313/500] datathon_fact_user_events-000000000312.parquet
[314/500] datathon_fact_user_events-000000000313.parquet
[315/500] datathon_fact_user_events-000000000314.parquet
[316/500] datathon_fact_user_events-000000000315.parquet
[317/500] datathon_fact_user_events-000000000316.parquet
[318/500] datathon_fact_user_events-000000000317.parquet
[319/500] datathon_fact_user_events-000000000318.parquet
[320/500] datathon_fact_user_events-000000000319.parquet
[321/500] datathon_fact_user_events-000000000320.parquet
[322/500] datathon_fact_user_events-000000000321.parquet
[323/500] datathon_fact_user_events-000000000322.parquet
[324/500] datathon_fact_user_events-000000000323.parquet
[325/500] datathon_fact_user_events-000000000324.parquet
[326/500] datathon_fact_user_events-000000000325.parquet
[327/500] datathon_fact_user_events-000000000326.parquet
[328/500] datathon_fact_user_events-000000000327.parquet
[329/500] datathon_fact_user_events-000000000328.parquet
[330/500] datathon_fact_user_events-000000000329.parquet
[331/500] datathon_fact_user_events-000000000330.parquet
[332/500] datathon_fact_user_events-000000000331.parquet
[333/500] datathon_fact_user_events-000000000332.parquet
[334/500] datathon_fact_user_events-000000000333.parquet
[335/500] datathon_fact_user_events-000000000334.parquet
[336/500] datathon_fact_user_events-000000000335.parquet
[337/500] datathon_fact_user_events-000000000336.parquet
[338/500] datathon_fact_user_events-000000000337.parquet
[339/500] datathon_fact_user_events-000000000338.parquet
[340/500] datathon_fact_user_events-000000000339.parquet
[341/500] datathon_fact_user_events-000000000340.parquet
[342/500] datathon_fact_user_events-000000000341.parquet
[343/500] datathon_fact_user_events-000000000342.parquet
[344/500] datathon_fact_user_events-000000000343.parquet
[345/500] datathon_fact_user_events-000000000344.parquet
[346/500] datathon_fact_user_events-000000000345.parquet
[347/500] datathon_fact_user_events-000000000346.parquet
[348/500] datathon_fact_user_events-000000000347.parquet
[349/500] datathon_fact_user_events-000000000348.parquet
[350/500] datathon_fact_user_events-000000000349.parquet
[351/500] datathon_fact_user_events-000000000350.parquet
[352/500] datathon_fact_user_events-000000000351.parquet
[353/500] datathon_fact_user_events-000000000352.parquet
[354/500] datathon_fact_user_events-000000000353.parquet
[355/500] datathon_fact_user_events-000000000354.parquet
[356/500] datathon_fact_user_events-000000000355.parquet
[357/500] datathon_fact_user_events-000000000356.parquet
[358/500] datathon_fact_user_events-000000000357.parquet
[359/500] datathon_fact_user_events-000000000358.parquet
[360/500] datathon_fact_user_events-000000000359.parquet
[361/500] datathon_fact_user_events-000000000360.parquet
[362/500] datathon_fact_user_events-000000000361.parquet
[363/500] datathon_fact_user_events-000000000362.parquet
[364/500] datathon_fact_user_events-000000000363.parquet
[365/500] datathon_fact_user_events-000000000364.parquet
[366/500] datathon_fact_user_events-000000000365.parquet
[367/500] datathon_fact_user_events-000000000366.parquet
[368/500] datathon_fact_user_events-000000000367.parquet
[369/500] datathon_fact_user_events-000000000368.parquet
[370/500] datathon_fact_user_events-000000000369.parquet
[371/500] datathon_fact_user_events-000000000370.parquet
[372/500] datathon_fact_user_events-000000000371.parquet
[373/500] datathon_fact_user_events-000000000372.parquet
[374/500] datathon_fact_user_events-000000000373.parquet
[375/500] datathon_fact_user_events-000000000374.parquet
[376/500] datathon_fact_user_events-000000000375.parquet
[377/500] datathon_fact_user_events-000000000376.parquet
[378/500] datathon_fact_user_events-000000000377.parquet
[379/500] datathon_fact_user_events-000000000378.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[380/500] datathon_fact_user_events-000000000379.parquet

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[381/500] datathon_fact_user_events-000000000380.parquet
[382/500] datathon_fact_user_events-000000000381.parquet
[383/500] datathon_fact_user_events-000000000382.parquet
[384/500] datathon_fact_user_events-000000000383.parquet
[385/500] datathon_fact_user_events-000000000384.parquet
[386/500] datathon_fact_user_events-000000000385.parquet
[387/500] datathon_fact_user_events-000000000386.parquet
[388/500] datathon_fact_user_events-000000000387.parquet
[389/500] datathon_fact_user_events-000000000388.parquet
[390/500] datathon_fact_user_events-000000000389.parquet
[391/500] datathon_fact_user_events-000000000390.parquet
[392/500] datathon_fact_user_events-000000000391.parquet
[393/500] datathon_fact_user_events-000000000392.parquet
[394/500] datathon_fact_user_events-000000000393.parquet
[395/500] datathon_fact_user_events-000000000394.parquet
[396/500] datathon_fact_user_events-000000000395.parquet
[397/500] datathon_fact_user_events-000000000396.parquet
[398/500] datathon_fact_user_events-000000000397.parquet
[399/500] datathon_fact_user_events-000000000398.parquet
[400/500] datathon_fact_user_events-000000000399.parquet
[401/500] datathon_fact_user_events-000000000400.parquet
[402/500] datathon_fact_user_events-000000000401.parquet
[403/500] datathon_fact_user_events-000000000402.parquet
[404/500] datathon_fact_user_events-000000000403.parquet
[405/500] datathon_fact_user_events-000000000404.parquet
[406/500] datathon_fact_user_events-000000000405.parquet
[407/500] datathon_fact_user_events-000000000406.parquet
[408/500] datathon_fact_user_events-000000000407.parquet
[409/500] datathon_fact_user_events-000000000408.parquet
[410/500] datathon_fact_user_events-000000000409.parquet
[411/500] datathon_fact_user_events-000000000410.parquet
[412/500] datathon_fact_user_events-000000000411.parquet
[413/500] datathon_fact_user_events-000000000412.parquet
[414/500] datathon_fact_user_events-000000000413.parquet
[415/500] datathon_fact_user_events-000000000414.parquet
[416/500] datathon_fact_user_events-000000000415.parquet
[417/500] datathon_fact_user_events-000000000416.parquet
[418/500] datathon_fact_user_events-000000000417.parquet
[419/500] datathon_fact_user_events-000000000418.parquet
[420/500] datathon_fact_user_events-000000000419.parquet
[421/500] datathon_fact_user_events-000000000420.parquet
[422/500] datathon_fact_user_events-000000000421.parquet
[423/500] datathon_fact_user_events-000000000422.parquet
[424/500] datathon_fact_user_events-000000000423.parquet
[425/500] datathon_fact_user_events-000000000424.parquet
[426/500] datathon_fact_user_events-000000000425.parquet
[427/500] datathon_fact_user_events-000000000426.parquet
[428/500] datathon_fact_user_events-000000000427.parquet
[429/500] datathon_fact_user_events-000000000428.parquet
[430/500] datathon_fact_user_events-000000000429.parquet
[431/500] datathon_fact_user_events-000000000430.parquet
[432/500] datathon_fact_user_events-000000000431.parquet
[433/500] datathon_fact_user_events-000000000432.parquet
[434/500] datathon_fact_user_events-000000000433.parquet
[435/500] datathon_fact_user_events-000000000434.parquet
[436/500] datathon_fact_user_events-000000000435.parquet
[437/500] datathon_fact_user_events-000000000436.parquet
[438/500] datathon_fact_user_events-000000000437.parquet
[439/500] datathon_fact_user_events-000000000438.parquet
[440/500] datathon_fact_user_events-000000000439.parquet
[441/500] datathon_fact_user_events-000000000440.parquet
[442/500] datathon_fact_user_events-000000000441.parquet
[443/500] datathon_fact_user_events-000000000442.parquet
[444/500] datathon_fact_user_events-000000000443.parquet
[445/500] datathon_fact_user_events-000000000444.parquet
[446/500] datathon_fact_user_events-000000000445.parquet
[447/500] datathon_fact_user_events-000000000446.parquet
[448/500] datathon_fact_user_events-000000000447.parquet
[449/500] datathon_fact_user_events-000000000448.parquet
[450/500] datathon_fact_user_events-000000000449.parquet
[451/500] datathon_fact_user_events-000000000450.parquet
[452/500] datathon_fact_user_events-000000000451.parquet
[453/500] datathon_fact_user_events-000000000452.parquet
[454/500] datathon_fact_user_events-000000000453.parquet
[455/500] datathon_fact_user_events-000000000454.parquet
[456/500] datathon_fact_user_events-000000000455.parquet
[457/500] datathon_fact_user_events-000000000456.parquet
[458/500] datathon_fact_user_events-000000000457.parquet
[459/500] datathon_fact_user_events-000000000458.parquet
[460/500] datathon_fact_user_events-000000000459.parquet
[461/500] datathon_fact_user_events-000000000460.parquet
[462/500] datathon_fact_user_events-000000000461.parquet
[463/500] datathon_fact_user_events-000000000462.parquet
[464/500] datathon_fact_user_events-000000000463.parquet
[465/500] datathon_fact_user_events-000000000464.parquet
[466/500] datathon_fact_user_events-000000000465.parquet
[467/500] datathon_fact_user_events-000000000466.parquet
[468/500] datathon_fact_user_events-000000000467.parquet
[469/500] datathon_fact_user_events-000000000468.parquet
[470/500] datathon_fact_user_events-000000000469.parquet
[471/500] datathon_fact_user_events-000000000470.parquet
[472/500] datathon_fact_user_events-000000000471.parquet
[473/500] datathon_fact_user_events-000000000472.parquet
[474/500] datathon_fact_user_events-000000000473.parquet
[475/500] datathon_fact_user_events-000000000474.parquet
[476/500] datathon_fact_user_events-000000000475.parquet
[477/500] datathon_fact_user_events-000000000476.parquet
[478/500] datathon_fact_user_events-000000000477.parquet
[479/500] datathon_fact_user_events-000000000478.parquet
[480/500] datathon_fact_user_events-000000000479.parquet
[481/500] datathon_fact_user_events-000000000480.parquet
[482/500] datathon_fact_user_events-000000000481.parquet
[483/500] datathon_fact_user_events-000000000482.parquet
[484/500] datathon_fact_user_events-000000000483.parquet
[485/500] datathon_fact_user_events-000000000484.parquet
[486/500] datathon_fact_user_events-000000000485.parquet
[487/500] datathon_fact_user_events-000000000486.parquet
[488/500] datathon_fact_user_events-000000000487.parquet
[489/500] datathon_fact_user_events-000000000488.parquet
[490/500] datathon_fact_user_events-000000000489.parquet
[491/500] datathon_fact_user_events-000000000490.parquet
[492/500] datathon_fact_user_events-000000000491.parquet
[493/500] datathon_fact_user_events-000000000492.parquet
[494/500] datathon_fact_user_events-000000000493.parquet
[495/500] datathon_fact_user_events-000000000494.parquet
[496/500] datathon_fact_user_events-000000000495.parquet
[497/500] datathon_fact_user_events-000000000496.parquet
[498/500] datathon_fact_user_events-000000000497.parquet
[499/500] datathon_fact_user_events-000000000498.parquet
[500/500] datathon_fact_user_events-000000000499.parquet

Per-file aggregation done.

[3/8] Merge user-bucket overall...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[4/8] Merge city profile...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[5/8] Merge category profile...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

[6/8] Merge ad_type profile...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,user_bucket_rows,users,min_bucket_id,max_bucket_id,avg_cities_per_user_bucket,avg_categories_per_user_bucket,avg_ad_types_per_user_bucket,multi_city_2plus_rate,multi_city_3plus_rate,mixed_sell_let_rate
0,2199205,994892,48620,48630,1.242167,1.605327,1.03295,0.145897,0.044179,0.122027

[7/8] Build cohort and retained state...

    bucket_id bucket_start bucket_end bucket_label
0       48620   2025-11-01 2025-11-15   2025-11-H1
1       48621   2025-11-16 2025-11-30   2025-11-H2
2       48622   2025-12-01 2025-12-15   2025-12-H1
3       48623   2025-12-16 2025-12-31   2025-12-H2
4       48624   2026-01-01 2026-01-15   2026-01-H1
5       48625   2026-01-16 2026-01-31   2026-01-H2
6       48626   2026-02-01 2026-02-15   2026-02-H1
7       48627   2026-02-16 2026-02-28   2026-02-H2
8       48628   2026-03-01 2026-03-15   2026-03-H1
9       48629   2026-03-16 2026-03-31   2026-03-H2
10      48630   2026-04-01 2026-04-15   2026-04-H1

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   retained_user_bucket_rows   users  min_offset  max_offset
0                    2199205  994892           0          10

[8/8] Build summaries...

,bucket_offset,offset_label,active_user_buckets,city_switched_users,category_switched_users,ad_type_switched_users,current_multi_city_2plus_users,current_multi_city_3plus_users,current_mixed_sell_let_users,city_switch_and_multi_city_2plus,...,city_switch_rate,category_switch_rate,ad_type_switch_rate,current_multi_city_2plus_rate,current_multi_city_3plus_rate,current_mixed_sell_let_rate,multi_city_2plus_share_among_city_switch,multi_city_3plus_share_among_city_switch,ad_type_switch_share_among_category_switch,mixed_sell_let_share_among_category_switch
0,0,+0,994892,0.0,0.0,0.0,118511.0,32040.0,91014.0,0.0,...,0.000000,0.000000,0.000000,0.119119,0.032205,0.091481,NaN,NaN,NaN,NaN
1,1,+1,289837,43363.0,90068.0,28639.0,47361.0,15223.0,40895.0,18633.0,...,0.149612,0.310754,0.098811,0.163406,0.052523,0.141097,0.429698,0.162973,0.197284,0.154439
2,2,+2,192533,34395.0,70779.0,24761.0,32089.0,10277.0,27450.0,13665.0,...,0.178645,0.367620,0.128607,0.166668,0.053378,0.142573,0.397296,0.148510,0.223682,0.147516
3,3,+3,149958,29051.0,59308.0,21759.0,25673.0,8426.0,21606.0,11200.0,...,0.193728,0.395497,0.145101,0.171201,0.056189,0.144080,0.385529,0.147017,0.236916,0.146371
4,4,+4,125355,25013.0,51027.0,19314.0,21801.0,7127.0,17892.0,9672.0,...,0.199537,0.407060,0.154074,0.173914,0.056855,0.142731,0.386679,0.147803,0.243910,0.142415
5,5,+5,106880,21606.0,44739.0,17134.0,18262.0,6004.0,15304.0,8147.0,...,0.202152,0.418591,0.160311,0.170865,0.056175,0.143189,0.377071,0.140841,0.247569,0.143946
6,6,+6,90296,18458.0,38594.0,15081.0,14585.0,4537.0,12378.0,6641.0,...,0.204417,0.427416,0.167017,0.161524,0.050246,0.137082,0.359790,0.128725,0.254625,0.140929
7,7,+7,84871,17004.0,36456.0,15023.0,14062.0,4399.0,12778.0,6276.0,...,0.200351,0.429546,0.177010,0.165687,0.051832,0.150558,0.369090,0.138379,0.267089,0.155338
8,8,+8,77650,14950.0,33154.0,13824.0,13712.0,4415.0,13635.0,5720.0,...,0.192531,0.426967,0.178030,0.176587,0.056858,0.175596,0.382609,0.146288,0.269771,0.172347
9,9,+9,57164,10759.0,23903.0,9785.0,10161.0,3318.0,10424.0,4260.0,...,0.188213,0.418148,0.171174,0.177752,0.058044,0.182353,0.395948,0.153639,0.263356,0.177635
10,10,+10,29769,5049.0,11633.0,4808.0,4641.0,1392.0,4987.0,1952.0,...,0.169606,0.390776,0.161510,0.155900,0.046760,0.167523,0.386611,0.140424,0.251784,0.161265

,cohort_ad_type_mode,bucket_offset,offset_label,active_users,eligible_cohort_users,exact_retention_rate
0,let,0,+0,562200.0,562200.0,1.000000
1,let,1,+1,157130.0,533362.0,0.294603
2,let,2,+2,96375.0,478168.0,0.201551
3,let,3,+3,72134.0,415157.0,0.173751
4,let,4,+4,59828.0,374250.0,0.159861
5,let,5,+5,50699.0,349479.0,0.145070
6,let,6,+6,43084.0,313047.0,0.137628
7,let,7,+7,40767.0,270510.0,0.150704
8,let,8,+8,36540.0,224764.0,0.162571
9,let,9,+9,25966.0,166237.0,0.156199
10,let,10,+10,12741.0,76539.0,0.166464
11,sell,0,+0,330881.0,330881.0,1.000000
12,sell,1,+1,109718.0,317668.0,0.345386
13,sell,2,+2,80574.0,291192.0,0.276704
14,sell,3,+3,65675.0,264484.0,0.248314
15,sell,4,+4,55635.0,246504.0,0.225696
16,sell,5,+5,47945.0,232753.0,0.205991
17,sell,6,+6,40547.0,211615.0,0.191607
18,sell,7,+7,38364.0,186556.0,0.205643
19,sell,8,+8,36343.0,155686.0,0.233438
20,sell,9,+9,27846.0,117594.0,0.236798
21,sell,10,+10,15490.0,60770.0,0.254896
22,unknown,0,+0,101811.0,101811.0,1.000000
23,unknown,1,+1,22989.0,97084.0,0.236795
24,unknown,2,+2,15584.0,88074.0,0.176942
25,unknown,3,+3,12149.0,77667.0,0.156424
26,unknown,4,+4,9892.0,69093.0,0.143169
27,unknown,5,+5,8236.0,62340.0,0.132114
28,unknown,6,+6,6665.0,53701.0,0.124113
29,unknown,7,+7,5740.0,44916.0,0.127794
30,unknown,8,+8,4767.0,35142.0,0.135650
31,unknown,9,+9,3352.0,24283.0,0.138039
32,unknown,10,+10,1538.0,11335.0,0.135686

,bucket_offset,offset_label,switch_decomp,active_user_buckets,share_within_offset
0,0,+0,no category/ad_type switch,994892,1.000000
1,1,+1,no category/ad_type switch,188899,0.651742
2,1,+1,category switch only,72299,0.249447
3,1,+1,category switch + sell/let switch,17769,0.061307
4,1,+1,sell/let switch only,10870,0.037504
5,2,+2,no category/ad_type switch,112825,0.586003
6,2,+2,category switch only,54947,0.285390
7,2,+2,category switch + sell/let switch,15832,0.082230
8,2,+2,sell/let switch only,8929,0.046376
9,3,+3,no category/ad_type switch,82942,0.553102
10,3,+3,category switch only,45257,0.301798
11,3,+3,category switch + sell/let switch,14051,0.093700
12,3,+3,sell/let switch only,7708,0.051401
13,4,+4,no category/ad_type switch,67460,0.538152
14,4,+4,category switch only,38581,0.307774
15,4,+4,category switch + sell/let switch,12446,0.099286
16,4,+4,sell/let switch only,6868,0.054788
17,5,+5,no category/ad_type switch,56083,0.524729
18,5,+5,category switch only,33663,0.314961
19,5,+5,category switch + sell/let switch,11076,0.103630
20,5,+5,sell/let switch only,6058,0.056680
21,6,+6,no category/ad_type switch,46448,0.514397
22,6,+6,category switch only,28767,0.318586
23,6,+6,category switch + sell/let switch,9827,0.108831
24,6,+6,sell/let switch only,5254,0.058186
25,7,+7,no category/ad_type switch,43129,0.508171
26,7,+7,category switch only,26719,0.314819
27,7,+7,category switch + sell/let switch,9737,0.114727
28,7,+7,sell/let switch only,5286,0.062283
29,8,+8,no category/ad_type switch,39616,0.510187
30,8,+8,category switch only,24210,0.311784
31,8,+8,category switch + sell/let switch,8944,0.115184
32,8,+8,sell/let switch only,4880,0.062846
33,9,+9,no category/ad_type switch,29771,0.520800
34,9,+9,category switch only,17608,0.308026
35,9,+9,category switch + sell/let switch,6295,0.110122
36,9,+9,sell/let switch only,3490,0.061052
37,10,+10,no category/ad_type switch,16257,0.546105
38,10,+10,category switch only,8704,0.292385
39,10,+10,category switch + sell/let switch,2929,0.098391
40,10,+10,sell/let switch only,1879,0.063119

,bucket_offset,offset_label,city_breadth,active_user_buckets,city_switched_users,category_switched_users,ad_type_switched_users,city_switch_rate,category_switch_rate,ad_type_switch_rate
0,0,+0,1 city,876381,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,0,+0,2 cities,86471,0.0,0.0,0.0,0.000000,0.000000,0.000000
2,0,+0,3+ cities,32040,0.0,0.0,0.0,0.000000,0.000000,0.000000
3,1,+1,1 city,242476,24730.0,70767.0,23593.0,0.101989,0.291852,0.097300
4,1,+1,2 cities,32138,11566.0,12525.0,3669.0,0.359885,0.389726,0.114164
5,1,+1,3+ cities,15223,7067.0,6776.0,1377.0,0.464232,0.445116,0.090455
6,2,+2,1 city,160444,20730.0,56258.0,20550.0,0.129204,0.350639,0.128082
7,2,+2,2 cities,21812,8557.0,9457.0,3107.0,0.392307,0.433569,0.142445
8,2,+2,3+ cities,10277,5108.0,5064.0,1104.0,0.497032,0.492751,0.107424
9,3,+3,1 city,124285,17851.0,47107.0,18126.0,0.143630,0.379024,0.145842
10,3,+3,2 cities,17247,6929.0,7973.0,2622.0,0.401751,0.462283,0.152026
11,3,+3,3+ cities,8426,4271.0,4228.0,1011.0,0.506883,0.501780,0.119986
12,4,+4,1 city,103554,15341.0,40492.0,16093.0,0.148145,0.391023,0.155407
13,4,+4,2 cities,14674,5975.0,6870.0,2406.0,0.407183,0.468175,0.163963
14,4,+4,3+ cities,7127,3697.0,3665.0,815.0,0.518732,0.514242,0.114354
15,5,+5,1 city,88618,13459.0,35746.0,14284.0,0.151877,0.403372,0.161186
16,5,+5,2 cities,12258,5104.0,5890.0,2108.0,0.416381,0.480503,0.171969
17,5,+5,3+ cities,6004,3043.0,3103.0,742.0,0.506829,0.516822,0.123584
18,6,+6,1 city,75711,11817.0,31177.0,12718.0,0.156080,0.411790,0.167981
19,6,+6,2 cities,10048,4265.0,4959.0,1732.0,0.424463,0.493531,0.172373
20,6,+6,3+ cities,4537,2376.0,2458.0,631.0,0.523694,0.541768,0.139079
21,7,+7,1 city,70809,10728.0,29392.0,12534.0,0.151506,0.415088,0.177011
22,7,+7,2 cities,9663,3923.0,4715.0,1836.0,0.405982,0.487944,0.190003
23,7,+7,3+ cities,4399,2353.0,2349.0,653.0,0.534894,0.533985,0.148443
24,8,+8,1 city,63938,9230.0,26496.0,11387.0,0.144359,0.414401,0.178094
25,8,+8,2 cities,9297,3533.0,4378.0,1763.0,0.380015,0.470905,0.189631
26,8,+8,3+ cities,4415,2187.0,2280.0,674.0,0.495357,0.516421,0.152661
27,9,+9,1 city,47003,6499.0,19036.0,8105.0,0.138268,0.404995,0.172436
28,9,+9,2 cities,6843,2607.0,3164.0,1220.0,0.380973,0.462370,0.178284
29,9,+9,3+ cities,3318,1653.0,1703.0,460.0,0.498192,0.513261,0.138638
30,10,+10,1 city,25128,3097.0,9483.0,4097.0,0.123249,0.377388,0.163045
31,10,+10,2 cities,3249,1243.0,1457.0,542.0,0.382579,0.448446,0.166821
32,10,+10,3+ cities,1392,709.0,693.0,169.0,0.509339,0.497845,0.121408

,bucket_offset,offset_label,active_user_buckets,city_switched_users,category_switched_users,ad_type_switched_users,current_multi_city_2plus_users,current_multi_city_3plus_users,current_mixed_sell_let_users,city_switch_and_multi_city_2plus,...,city_switch_rate,category_switch_rate,ad_type_switch_rate,current_multi_city_2plus_rate,current_multi_city_3plus_rate,current_mixed_sell_let_rate,multi_city_2plus_share_among_city_switch,multi_city_3plus_share_among_city_switch,ad_type_switch_share_among_category_switch,mixed_sell_let_share_among_category_switch
1,1,+1,289837,43363.0,90068.0,28639.0,47361.0,15223.0,40895.0,18633.0,...,0.149612,0.310754,0.098811,0.163406,0.052523,0.141097,0.429698,0.162973,0.197284,0.154439
2,2,+2,192533,34395.0,70779.0,24761.0,32089.0,10277.0,27450.0,13665.0,...,0.178645,0.367620,0.128607,0.166668,0.053378,0.142573,0.397296,0.148510,0.223682,0.147516
3,3,+3,149958,29051.0,59308.0,21759.0,25673.0,8426.0,21606.0,11200.0,...,0.193728,0.395497,0.145101,0.171201,0.056189,0.144080,0.385529,0.147017,0.236916,0.146371
4,4,+4,125355,25013.0,51027.0,19314.0,21801.0,7127.0,17892.0,9672.0,...,0.199537,0.407060,0.154074,0.173914,0.056855,0.142731,0.386679,0.147803,0.243910,0.142415
6,6,+6,90296,18458.0,38594.0,15081.0,14585.0,4537.0,12378.0,6641.0,...,0.204417,0.427416,0.167017,0.161524,0.050246,0.137082,0.359790,0.128725,0.254625,0.140929
8,8,+8,77650,14950.0,33154.0,13824.0,13712.0,4415.0,13635.0,5720.0,...,0.192531,0.426967,0.178030,0.176587,0.056858,0.175596,0.382609,0.146288,0.269771,0.172347
10,10,+10,29769,5049.0,11633.0,4808.0,4641.0,1392.0,4987.0,1952.0,...,0.169606,0.390776,0.161510,0.155900,0.046760,0.167523,0.386611,0.140424,0.251784,0.161265

[SAVE HTML] /kaggle/working/retention_lowdisk_sell_let_multicity/01_switch_and_multicity_overall.html
[SKIP PNG] 01_switch_and_multicity_overall
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using

[SAVE HTML] /kaggle/working/retention_lowdisk_sell_let_multicity/02_city_switch_multicity_diagnosis.html
[SKIP PNG] 02_city_switch_multicity_diagnosis
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using

[SAVE HTML] /kaggle/working/retention_lowdisk_sell_let_multicity/03_retention_by_first_seen_ad_type.html
[SKIP PNG] 03_retention_by_first_seen_ad_type
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using

[SAVE HTML] /kaggle/working/retention_lowdisk_sell_let_multicity/04_category_switch_decomposition.html
[SKIP PNG] 04_category_switch_decomposition
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using

[SAVE HTML] /kaggle/working/retention_lowdisk_sell_let_multicity/05_switch_by_city_breadth.html
[SKIP PNG] 05_switch_by_city_breadth
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using

DONE.
Output folder: /kaggle/working/retention_lowdisk_sell_let_multicity

CÁCH ĐỌC NHANH:

1) 10_quick_key_offsets.csv
   - Nhìn các offset +1, +2, +4, +6, +8, +10.
   - city_switch_rate: bao nhiêu retained user đổi dominant city.
   - category_switch_rate: bao nhiêu retained user đổi dominant category.
   - ad_type_switch_rate: bao nhiêu retained user đổi dominant sell/let.

2) 02_city_switch_multicity_diagnosis.html
   - Nếu "City switchers: 2+ cities" cao hơn nhiều "All retained: 2+ cities":
     city switch đang bị nhóm xem nhiều city kéo lên.
   - Nếu không cao hơn nhiều:
     city switch có thể là đổi khu vực thật.

3) 03_retention_by_first_seen_ad_type.html
   - So let vs sell.
   - Nếu sell giữ chân lâu hơn let:
     mua nhà có journey dài hơn thuê.
   - Nếu let rớt nhanh:
     thuê có thể là nhu cầu ngắn hạn, quyết định nhanh hơn.

4) 04_category_switch_decomposition.html
   - Nếu phần "category switch only" lớn:
     user đổi phân khúc nhưng vẫn cùng thuê hoặc cùng mua.
   - Nếu "category switch + sell/let switch" lớn:
     user đổi cả intent lớn: thuê <-> mua.

5) 05_switch_by_city_breadth.html
   - Nhóm 3+ cities mà switch rate cao bất thường:
     có thể là broad search / professional browsing / cò-like behavior.

Saved CSV/HTML:
- 00_dim_check.csv
- 01_switch_and_multicity_overall.html
- 01_user_bucket_profile_check.csv
- 02_bucket_calendar.csv
- 02_city_switch_multicity_diagnosis.html
- 03_retained_state_check.csv
- 03_retention_by_first_seen_ad_type.html
- 04_category_switch_decomposition.html
- 04_overall_offset_switch_diagnosis.csv
- 05_retention_by_first_seen_ad_type.csv
- 05_switch_by_city_breadth.html
- 06_category_switch_decomposition.csv
- 07_switch_by_city_breadth.csv
- 08_top_city_transitions.csv
- 09_top_category_transitions.csv
- 10_quick_key_offsets.csv